### ISSUE TITLE
Pressing Tab while renaming a file to bring me to the next file

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1020]
I had this feature in Windows Explorer where if I pressed the Tab button while I was renaming a file it would actually rename that file (if I made any changes in the name of course) and bring me to the next file so I can rename that one as well immediately without having to press F2 or use right click menu. Obviously this feature comes handy when renaming multiple files one after another.

**Comment by Asday** [comment]
Huh, I just typed out a whole issue for this, and only just saw it's already open.  Should it help, I've reproduced it below:

```
 * Nemo version (nemo --version): 3.0.6
 * Is issue with desktop or windowed nemo?  Windowed.  (What's desktop nemo?  :astonished:)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint 18.
 * Graphics hardware *and* driver used:  AMD RX580, `amdgpu` (I think).
 * 32 or 64 bit:  64 I assume, not sure how to tell.
 ```

**Issue**

In Windows, when renaming a file, one can press F2 to confirm the filename change, and progress directly to renaming the next file in the list.  I would love to see this in nemo, but I can't quite figure out how to do it myself, hence the issue instead of PR.

**Steps to reproduce**

0. Select a file in a directory with multiple files;
0. Press F2;
0. Press TAB.

**Expected behaviour**

* The next file in the list is selected for renaming, allowing the user to press TAB, instead of Enter, Down, F2, (and have to deal with the auto-sort if they forgot to disable it).

**Other information**

Given this template, I'm concerned that this isn't the right place for feature requests.  I'd be happy to be redirected.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
