### ISSUE TITLE
Enable rectangle selection in List View as well

### ISSUE THREAD

**Issue by ngabor7** [linuxmint/nemo#1028]
In Icon and Compact View you can select files with mouse by forming a rectangle. I think the same should be possible in List View as well.

**Comment by JosephMcc** [comment]
I've seen this request before and I'm curious as to how people expect this to work. To do a marquee select you first need an empty area to click so you can start the drag. In many cases with the list view there is no empty area since clicking anywhere on a row will activate that row.

In addition the functionality to do the same as a marquee select already exists. Click on the first item you want selected and then shift+click on the second and everything in between will be selected.

**Comment by ngabor7** [comment]
When the list is not populated all the way than it is obvious how. For when it is populated all the way I would suggest appending a blank margin on the end of the list with a thickness of about half of what a file has. Or better yet it can be implemented the same way as in icon and compact view: add a little padding around every file so that there is a little neutral clickable area between them.

**Comment by Garibaldo** [comment]
https://github.com/linuxmint/nemo/issues/416

**Comment by ManIVIctorious** [comment]
@josephmcc i think in Windows they solved this by making the Name column the only selectable, i am not sure though, since the last time i used windows was about 6 years ago... 
Maybe someone else could tell how this was solved in different filebrowsers/operating systems?
