### ISSUE TITLE
need to click twice when opening file in inactive pane

### ISSUE THREAD

**Issue by denispr** [linuxmint/nemo#1030]
In dual pane mode, nemo being configured to "single click to open file", one has to click twice to open a file or a folder in the inactive pane: once to make the pane active, and once to open the file or folder.
One should have to click only once instead, the way caja behaves.

**Comment by tflori** [comment]
the same appears when you have "double click to open file". you need to klick three times then.

on one side this is correct - the first click activates the pane (btw. you can click anywhere the file gets not selected).

on the other side: i want this feature too. it is annoying to click three times - especially because you don't see very clear which pane is active and sometimes you click twice and nothing happens.

another feature that will be nice for dual-pane mode: "tab"-key changes between the panes (for better keyboard support)

**Comment by denispr** [comment]
I just wondered if that should not be considered as a bug, rather than a feature request. 
Other file managers offering dual pane view - like caja, dolphin, pcmanfm.. - all behave that way, avoiding the user to click twice, which is what one naturally expects.

**Comment by motoschifo** [comment]
It's probably a bug, because if I do a double click on a window that has not the focus, the action is always taken by file manager (ex. view a file, open a folder, etc) and it doensn't require a triple click.
Only if you click on the second pane, there is an additional click to do.
This behavior can be added as an extra option, and the TAB key (or CTRL+TAG) can be useful to change pane without mouse click (F6 is not so comfortable).

**Comment by icarter09** [comment]
@denispr are you still experiencing this issue on the latest version of nemo?

**Comment by denispr** [comment]
It's still there in nemo 4.4.2 (LMDE 4). I'm not sure if it's nemo last version, but this is the only one I can test.

**Comment by motoschifo** [comment]
My experience with latest Mint 19.3 Cinnamon is the same as 3 years ago.

**Comment by icarter09** [comment]
@denispr @motoschifo thanks for the update.

**Comment by JosephMcc** [comment]
This isn't really an issue. It's the way things work and I'm not sure if you can get around it or not.
