### ISSUE TITLE
trying to overwrite '/usr/share/glib-2.0/schemas/gschemas.compiled', which is also in package virt-manager

### ISSUE THREAD

**Issue by jean-christophe-manciot** [linuxmint/nemo#1046]
System: 4.2.0-19-generic #23-Ubuntu SMP Wed Nov 11 11:39:30 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Installing the home-brewed nemo package leads to:
trying to overwrite '/usr/share/glib-2.0/schemas/gschemas.compiled', which is also in package virt-manager 1:1.3.1-11

What should be the most adequate way to avoid "force-overwrite" and solve that issue?

**Comment by lukefromdc** [comment]
The issue here is in the creation of the .deb package, I use Checkinstall and it is notorious for this. Checkinstall picks up files like gschemas.compiled and icon cache files and adds them to the package.You have to have at least TWO such packages to get this error.  This particular problem you can get around by building with 
--disable-schemas-compile in the configuration options, but there is another checkinstall bug which is worse.

With nemo you are also copying everything in /usr/share/mime to the package if you are using checkinstall. Usually this won't hurt anything if you only have one such package (two won't be coninstallable) but removal of the package can trash your whole /usr/share/mime directory! Usually the necessary files are regenerated but sometimes that fails and leaves un unusable desktop. I would advise backing up all of /usr/share/mime to a directory somwhere just in case if you don't have a full backup partition.

I pack these troublesome debs by hand from the directory checkinstall makes in /var/tmp, and delete from the package files (NOT the filesystem!) everything in (packagedir)/usr/share/mime except for (packagedir)/usr/share/mime/packages. I then make sure that icon cache files and gschemas.compiled did not get into the package and delete them if they did. Finally I run dpkg -b on the directory I copied everything to and I have my package.

**Comment by jean-christophe-manciot** [comment]
In the meantime, I've realized there are at least 3 other options:
- use debian control files when they are available to build the package with **dpkg-buildpackage** instead of checkinstall: problems solved with the best option by far.
-  use checkinstall with a mix of "--exclude" & "--include" options to deal with those issues
- or use **fpm** instead of checkinstall for packages with such potential issues;
