### ISSUE TITLE
Disable nemo thumnnail cache

### ISSUE THREAD

**Issue by citycobra42** [linuxmint/nemo#1075]
For users who disable their thumnail cache with immutable /cache/thumbnail folder it would be nice to see the thumnails like in pcmanfm

in nemo there is no option to disable thumbnail cache
i get a blue message on top of nemo
A problem has been detected with your thumbnail cache. Fixing it will admire administrative priviledges

please ad an option to disable generating thumbs or to disable the error message

**Comment by alexanderdd** [comment]
Under edit-preferences-preview you can set 'show thumbnails' to 'never'.

I don't think this is a valid feature request since it is already implemented.

**Comment by Lupinus** [comment]
@alexanderdd That does in fact not disable the permission check. The notification will appear regardless of this setting.

**Comment by leigh123linux** [comment]
I don't see why we should accommodate user made issues 

> For users who disable their thumnail cache with immutable /cache/thumbnail folder

**Comment by mtwebster** [comment]
I'll fix it so the check doesn't occur if thumbnails are disabled - that's a bug, since from nemo's perspective, it shouldn't care if it's not thumbnailing.  I misread this a bit initially.

I did some work on possibly making the entire thumbnail problem go away (mainly by having us use a different thumbnail storage location, and making it configurable in some way) but it all came to a halt once I realized that Gvfs, which is the filesystem backend for Gio, hardcodes that `~/.cache/*` location.
