### ISSUE TITLE
Images features

### ISSUE THREAD

**Issue by Translator5** [linuxmint/nemo#1087]
My request belongs the images/pictures.
- Rotate selected Pictures 90° right/left
- Enable/Disable Preview of Images trough closed Folder-Icon like in Doplhin
- Draw files with the right-mouse button and open on release the Menu to move/copy the drawn files or to create shortcuts/launchers.

***Why I do not use Dolphin, because I like Thunar and Nemo more.

**Comment by dg1727** [comment]
The 3rd bullet point seems to be like issue #1289

**Comment by nswearin** [comment]
'Tis true that bullet point 3 seems to be like issue #1289.
Though I'm noob and don't have much say in the development but ... It would be even nicer if right click & drag + "context" menu after drop showed, instead of the 4 option menu of: 
move
copy
shortcut
cancel

The Context menu refers, at least in my mind, to the right click menu where one has options such as 
open
open with
cut
copy
duplicate
make link
rename
copy to
move to
move to trash
delete
compress
properties 

and in the case of archives "extract here"

Being able to right click and drag and drop then have the open to extract an archive to the dropped location would be quite helpful. *yes this would be what I'm ultimately looking for but simply right-click  drag and drop would be a good start*

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
