### ISSUE TITLE
Viewing Files by Tags

### ISSUE THREAD

**Issue by mrbrahman** [linuxmint/nemo#1092]
Nowadays, we tag photos and videos quite a lot. While there are search features (to get to the files with specific tags), there doesn't seem to be tools to view/browse those media files by tags (similar to folders).

Can Nemo be enhanced to toggle to "tag" view from "folder" view?

**Comment by xenopeek** [comment]
Programs will likely stores such tags in their own tag database. So the file manager would have to be aware of all those databases or the programs would all have to use the same tag database.

There's a good article about filesystems and file managers on Linux that support tagging: http://www.makeuseof.com/tag/tag-youre-manage-files-linux-tagspaces/

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by DIMFLIX** [comment]
@mrbrahman @xenopeek  If the problem is still relevant for you, I have come up with a small solution. The [nemo-tags plugin](https://github.com/meowrch/nemo-tags) adds full tag support.

Unfortunately, I was unable to implement a drag-and-drop system or create a more attractive interface due to Nemo's limitations. But overall, I think it turned out to be quite usable and even convenient.

I would appreciate a star on GitHub repository as support.

<img width="1086" height="658" alt="Image" src="https://github.com/user-attachments/assets/df6468b8-55a6-4af9-8432-86fcf0075b38" />
