### ISSUE TITLE
"Move to trash" confirmation dialog option

### ISSUE THREAD

**Issue by jez9999** [linuxmint/nemo#1135]
There should be an option in Preferences -> Behaviour to display a confirmation dialog when delete is pressed and the file would be sent to trash, similar to the dialog when shift-delete is pressed.

I'm aware that the reasoning for not showing this is that sending to trash is a safer operation, but it is still a dangeous operation.  If the file is silently trashed when delete is pressed it is VERY easy for a user to trash a file without noticing.  If they then routinely empty their trash and there are many items there it is very easy to delete the file completely and only notice the file is missing later on, when it's too late.

**Comment by ElectricRCAircraftGuy** [comment]
+1000.

**This is a highly desirable option in my opinion.** If I had 1000 votes to upvote this, I would. I have accidentally hit the delete key while files were selected, and I didn't know where they went or what happened. I also have kids. Weird things can happen, and having the "move to trash confirmation dialogue box" would save a lot of headache.

**Comment by mohhhh** [comment]
**Much needed,** please provide an option for a confirmation dialog when delete is pressed and file(s) moved to trash.

**Comment by alentsch** [comment]
I also missing such a "safety lock" extremely much - please add this option! If a file accidentally gets into the trash-bin because the DEL key is hit without noticing it (that happens to me occasionally) the file risks to be lost forever because who reviews his trash-bin before deleting it? Anything which can go wrong, does go wrong - it is just a question of time. I suspect that many people did not even notice how many files they have already lost due to the lack of this option! Adding this option would not "hurt" anyone, especially if it is off by default. But it would be a great relief for people who have lost files in this way.

**Comment by rubo77** [comment]
The option is already there, but it didn't work: http://unix.stackexchange.com/q/195682/20661

Anything happened on this critical but?

**Comment by federicocode** [comment]
Is extremely dangerous as is it now. I have accidentally delete one file whitout see any notification! Some days later I've empty the trash-bin... and puff, I lose my data. This is really crazy for me. Okay, that option can be not enabled by default.. but the possibility to use an ask button before deleting files is really, really, realy needed.

**Comment by phavel** [comment]
Much needed!

**Comment by LinuxZoo** [comment]
yes - if you have kids / woman - you need this option.

**Comment by acritum** [comment]
# Excuse me, the topic was started 2 years ago and still there is no solution?!! Is it too difficult to add a checkbox in the prefs window? Please add it, it is really very unsafe to delete without a confirmation.

**Comment by LinuxZoo2** [comment]
My Solution was simple: I am using Windows 7 further :-) In the future I will never use Cinnamon as Desktop GUI. Cinnamon is much to unprofessional for productive usage.

**Comment by acritum** [comment]
Actually, I switched from Windows 7 to Linux just a couple of days ago. Unfortunately, Win7 becomes real spyware like Win10 if you install MS updates, and it is too vulnerable to hacker attacks if you don't install MS updates. So we have no choice... I'll keep Win7 for powerful apps to be used offline but will use Linux for browsing internet.

**Comment by happyniko** [comment]
In Nemo 3.6.5 there is a confirm dialog, when you delete files via right mouse click and choosing "Delete". Unfortunately, when using the delete-key there doesn't appear a confirm dialog, even this option can be checked in the **File Management Preferences > Behavior > Trash > "_Ask before emptying the Trash or deleting files_"**. I suppose it is quite easy to change/improve this by adding the command for showing the same dialog when pressing "delete" like clicking "delete" with the mouse. Who can confirm this?

**Comment by JosephMcc** [comment]
At least in Nemo 3.8, you will get the dialog if you also have "Bypass the trash when delete key is pressed". Otherwise it's just going to the trash when you use the delete key. Not sure you need a dialog for that.

**Comment by ElectricRCAircraftGuy** [comment]
I am sure we need a dialog for that. There have been repeated arguments and reasons given for years and I, as well as many many others, do need a dialog for that.

**Comment by federicocode** [comment]
[...]
Pressing "del" = importance for choosing to show confirm dialog (there is the possibility of pressing "del" unintended!)
According number 2: The function "Ask before emptying the Trash or deleting files" is not working, if checked. I never see the dialog when pressing "del", only when using "Shift" + "del".
[...]
quote and quote. It's really needed, also for me the function "ask before emptying the Trash or deleting files" is not working. I can't understand why this problem appear so strange, in my opinion that's a basilar function needed in every "everyday OS" for every kind of user. Everyone can press "del" accidentally.
I hope this function start working in some new version, thank you!

**Comment by Tyco72** [comment]
I am also very angry about this missing elementary safety option. Where I have to click to vote this issue?

**Comment by pyranhas** [comment]
Deleting without confirmation when pressing "delete" button is a serious problem. Anyone can accidentally click on delete button - especially on laptops where all keys are close together - and not even realize that a file or folder was deleted. And if that is on an NTFS partition then bye bye for good as data from such partitions get deleted directly and not through trash folder. Please add this feature of confirmation on delete ASAP.

**Comment by acritum** [comment]
> Please add this feature of confirmation on delete ASAP.

ASAP?!! LOL, This thread is already 3+ years old. A always wonder how come the smartest people who write OS low-level code cannot add a simple dialog window with 2 buttons... It's a matter of 10 minutes, but for some unknown reason this issue is always ignored during years... it's magic! Because of this stupid negligence I had to find another file manager to work with files.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/pull/2020/commits/7946a64e69f9eb62d70b441e03599aebd249a959

**Comment by NikoKrause** [comment]
> It's a matter of 10 minutes

I guess you didn't had 10 minutes in the last 3+ years to add this feature?

**Comment by happyniko** [comment]
After the last comments I would like to know if the "Move to trash" confirmation dialog will be added in future or not. The most annoying is the missing answer for all these requests. If there is no will to add this function everyone would like to know the reason. But nearly all the other file manager have this confirmation on delete integrated.
Additionally I'm interested if the following tab issues will be added/fixed [https://github.com/linuxmint/nemo/issues/2047] and [https://github.com/linuxmint/nemo/issues/1873]. Also it would be great to add a function to open external devices like USB Stick in a new tab as default.

Because nemo is on of the most used file managers it would be so great to add/improve these functions, so nemo will become the best of all!

**Comment by rubo77** [comment]
It is added in the latest nemo build, I guess in the next mint release this will be included

see #2020 - Add Move to Trash Option

**Comment by happyniko** [comment]
@rubo77: Thanks for your post! I can see clearly now the rain is gone… Best regards from Austria.

**Comment by Tyco72** [comment]
Great! Would it be possible to install in advance the newer version of Nemo directly form its repository? I am a beginner, but I would try. It is a very desired update for me.

**Comment by rubo77** [comment]
Create a directory where you want to keep it and then

Code: Select all

git clone https://github.com/linuxmint/nemo.git

Once it's cloned

Code: Select all

cd nemo

then

Code: Select all

git fetch origin 2.8-maintenance

That will grab the branch you want. Next

Code: Select all

git checkout 2.8-maintenance

That will checkout the branch and then you can just build it. When you first run this it will probably complain about libs you are missing. Keep installing what it asks for until it builds.

Code: Select all

dpkg-buildpackage

Once you get it to build, all the needed debs will be on level up, so

Code: Select all

cd ..

Now install

Code: Select all

sudo dpkg -i *.deb

Once you install it, the update manager will want to install the repo version. You can block that by blacklisting it in the update manager.
