### ISSUE TITLE
No option to preview files larger than 8GB

### ISSUE THREAD

**Issue by DominicMe** [linuxmint/nemo#1181]
There are many files now, especially with the arrival of 4K that will exceed 8GB meraning no thumbnail is generated. This is a really annoying and I see no reason to limit to 8GB since thumbnails are generated on the host. Why isn't there "Any Size" option? It's a silly limitation to have, and I hope a no limit option is added soon.

**Comment by stefan-niedermann** [comment]
I strongly agree with @DominicMe - the limitation makes sense for a default user because it costs much performance to process large files. But for advanced users there should be definitely the option to set "Any size" at all - because they know what they are doing and ressources may be no problem for them.

Maybe a warning or hint message can be displayed in the settings if "Any size" is selected like "Selecting any size can cause performance issues."?

**Comment by DominicMe** [comment]
I should also mention that in Gnome files the maximum limit is 4GB in the options menu however it is not enforced and files well over 8GB have a thumbnail preview generated with no noticeable performance decrease.

**Comment by namankanakiya** [comment]
Agree with what everyone has said so for. For now, I'm forced to open up another File Manager to generate the thumbnails, which is a big hassle

**Comment by DominicMe** [comment]
Great to see that it has finally been fixed, can't believe how little code change it required. Still I feel that adding hard-coded options is a temporary solution. There should be "unlimited" option as even now there are already 4k movies that are well over 32GB so it is already an issue again.
