### ISSUE TITLE
save as / open dialogue impropvements

### ISSUE THREAD

**Issue by timmie** [linuxmint/nemo#1221]
Please add to "save as" open file dialogues:

- ability to rename & delete files
- ability to open the directory after saving a file

**Comment by JosephMcc** [comment]
Are you talking about the dialogs that show when opening/saving files from other applications like xed, gedit, gimp, or whatever?

**Comment by timmie** [comment]
Yes, exactly.

**Comment by JosephMcc** [comment]
Those dialogs come from the toolkit each app is created with. In most cases gtk. They have nothing to do with Nemo. You would have to file a feature request with upstream gnome/gtk for that.

**Comment by Piiit** [comment]
Hi, this bug is already filed:
https://bugzilla.gnome.org/show_bug.cgi?id=325150

**Comment by GitHubIsToxic** [comment]
Bumping this. This feature seems to never have trickled down to Mint Cinnamon. This is one of the few remaining basic UI features where Mint is inferior to Windows.

I understand this is an upstream issue, but Mint devs are in a better position to petition the GTK gnomes to finally bring this to reality. It's been 13 years since this feature request was first made!

**Comment by JosephMcc** [comment]
Bumping closed issue that belong to upstream isn't going to do any good here.
