### ISSUE TITLE
translation string added

### ISSUE THREAD

**Issue by jonorthwash** [linuxmint/nemo#1224]
I corrected [the Kazakh string for number of seconds on launchpad](https://translations.launchpad.net/linuxmint/latest/+pots/nemo/kk/840/+translate), but it converted my `&` to `&amp;`.  The correct string is `%&#x27;d секунд` for the Kazakh plural (the same as the singular).

**Comment by xenopeek** [comment]
I don't know what you can do about this but I note that this string translated to other languages doesn't have the `&amp;` replacement (I looked at Dutch and French). Perhaps try reaching out to other translators?

**Comment by Pjotr123** [comment]
I'm a translator as well (Dutch). What happens when you simply copy the English string, by means of the Copy button in Launchpad, and then correct only the word "seconds" into "секунд"?

**Comment by NikoKrause** [comment]
I reported it here, since it's a launchpad issue:
https://answers.launchpad.net/launchpad/+question/649806

**Comment by NikoKrause** [comment]
@jonorthwash I needed to suggest `%'d секунд'` instead of `%&#x27;d секунд` and launchpad converted it on it's own to this weird `%&#x27;d секунд`.

Is the suggestion right? Both strings are same in singular and plural as you mentioned above?
![screenshot-area-2017-07-19-105912](https://user-images.githubusercontent.com/8415124/28359163-a4f6afac-6c71-11e7-886c-feed20296106.png)

The suggestion needs to be accepted by somebody from the translation team. After that it will get it's way into LM 18.3

**Comment by jonorthwash** [comment]
Yeah, that looks about right.

**Comment by jonorthwash** [comment]
Just for record keeping:
The index seems to've changed; now the translation in question is [here](https://translations.launchpad.net/linuxmint/latest/+pots/nemo/kk/843/+translate).

**Comment by NikoKrause** [comment]
@jonorthwash The translation has been approved and will be available in Mint 19

**Comment by jonorthwash** [comment]
Yeah, I figured something like that was the case.  I was just updating the issue because the id (and the the url) of the translation string changed from 840 to 843.  So that if someone finds this bug in the future wondering about it, they won't think I was purposely linking to the "_Merge" string instead of the "seconds" string.
