### ISSUE TITLE
nemo scrolls in the opposite direction than all other apps

### ISSUE THREAD

**Issue by hipunk** [linuxmint/nemo#1226]
Hello,

I am using 17.3 xfce and have natural scrolling enabled.
nemo is the only application that scrolls in the wrong direction, e.g. scrollwheel up is content down and vice versa.
There are no major other settings I changed, at least not that I can remember.

Bear in mind, that nemo is the only app having the issue.

Edit: The version of nemo I am running is 2.8.7 /Edit
If there is any other info you need from me, just ask.

Thank you.

Edit2: I tried going up to level 5 of updates, but there is no nemo update to be found. IRC doesn't know. How do I update to latest nemo in 17.3 xfce? /Edit2

**Comment by xenopeek** [comment]
You could retest with newer Nemo version by booting from Linux Mint 18 Xfce DVD / USB thumb drive, installing Nemo there, and toggling natural scrolling. I tried that in VirtualBox and it didn't do anything at all, for any program.

**Comment by nick-s-b** [comment]
I've noticed the same thing as @hipunk . Basically, in Cinnamon, Nemo is one of the few apps that doesn't respect scroll wheel direction from Xorg. Easiest way to set natural scrolling (which makes perfect sense if you use tablets/phones) is by doing this and loading it up with xmodmap:

`pointer = 1 2 3 5 4 7 6 8 9 10 11 12`

This however does not work in Nemo but it works in every browser I tried and myriad of other GTK applications.

I have no idea how to fix this but I'm willing to help because it's driving me nuts :)

**Comment by xenopeek** [comment]
On Linux Mint 20 Cinnamon inverting the mouse scroll direction through System Settings > Mouse and Touchpad > Mouse > Reverse scrolling direction works as expected: I have to scroll away from me (up) to make Nemo scroll down.
