### ISSUE TITLE
One tab Jumps to home directory when search a file in another tab. Both tabs in same dir. (LM 18 Cinnamon)

### ISSUE THREAD

**Issue by deepsidhu1313** [linuxmint/nemo#1242]
One tab jumps to home directory, whenever i extract file using "extract here" option. Both tabs are pointing to same directory. I am using Linux Mint 18 cinnamon 64 bit.

**Comment by xenopeek** [comment]
I can't manage to reproduce it. I open two tabs on Downloads directory. I tried from both tabs the "extract here" option on a zip file but none of the tabs change jump through the home directory. I also tried with three tabs and that doesn't make a difference.
Can you try creating a new user account, logging in to that, and retesting it there? To confirm if this is a system-wide issue or an issue only on your own user account.

**Comment by deepsidhu1313** [comment]
My apologies, 

Minor update

*  try with search in one tab.


I will retry with new user asap. But it may take some time.

**Comment by deepsidhu1313** [comment]
@xenopeek  yes i tried search in one tab with new user. This bug exist.

**Comment by xenopeek** [comment]
It's even simpler to reproduce and unrelated to extracting an archive file.

Steps to reproduce:
1. Open Nemo and go to a subdirectory in your home directory (say go to Downloads)
2. Open a second tab, it should open on that same subdirectory
3. Click the magnifying glass or press Ctrl+F to toggle showing the search bar
4. Go to the first tab and it will show your home directory instead of the subdirectory
5. If the first tab still shows the subdirectory, switch back to the second tab and toggle search again and then switch back to the first tab (I sometimes need to do it twice to trigger the issue).

After reproducing the issue and the first tab showing your home directory, if you switch back to the second tab note that the search bar is still displayed but the magnifying icon isn't lit up to indicate that.

**Comment by Timmy93** [comment]
Just for information, on Linux Mint 17.3, Cinnamon 2.8.8, Nemo 2.8.7 the bug cannot be reproduced.

**Comment by laex333** [comment]
thanks for already posting this! it is bothering my workflow all the time...

**Comment by Swiftpaw** [comment]
Was just about to report this myself.  Some additional information:

1. Open Nemo up. Open three or four different tabs and have them all browsing locations other than your home folder.
2. Click the search button to make the search box appear.
3. Click on any other tab and watch how it forces that tab back to the home folder. It undoes your work, pretty annoying.
4. Click back on the tab that you opened the search box on, it will still be open, and then select some other tab. It no longer messes up that tab you select. So, the bug only happens one time to one other tab, then starts behaving itself.

**Comment by xenopeek** [comment]
Not reproducible in Nemo 4.6.4 with my above steps. Appears to have been fixed.
