### ISSUE TITLE
Nemo pop-up says "Contains: 0 items" on all non-empty folders

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/nemo#1254]
What happens: within Nemo windows (though not the desktop, where the pop-up in question does not appear at all), when the pointer is over a non-empty folder, a tool-tip appears that erroneously reports the folder as empty.

Linux Mint 18 x64 Cinnamon.

**Comment by ChrisJAllan** [comment]
Could not reproduce with Nemo 3.0.6 on Arch Linux.

As for it not showing up on the desktop, 'Show tooltips on the desktop' is a separate option in the 'Preview' tab.

**Comment by ACinnamonUserInUK** [comment]
> Make sure you have 'Count number of items' in the 'Preview' options turned on, otherwise it will always show zero.

Ah. That was it. Yet, isn't the behaviour rather bizarre and misleading? 'Contains: 0 items' suggests that Nemo has counted and made the tally zero, whereas, in fact, it has not counted at all. When counting is disabled, it would make more sense, surely, either to (1) show no tooltip, or (2) show a tooltip that says, 'Number of items: unknown' or 'Counting of items disabled' or some such.

**Comment by xenopeek** [comment]
Forgetting about when a directory actually is empty, there are various reason 'Contains: 0 items' will be displayed:
- When "Count number of items" in preview preferences is set to "Never";
- When "Count number of items" in preview preferences is set to "Local Files Only" and the directory is on a remote filesystem;
- When the directory isn't accessible (e.g., no permissions).

The code that does the counting actually checks for that but the code that adds the count to the tooltip doesn't use that knowledge. I've added that in the PR, so that the 'Contains: 0 items' text isn't added if the contents of the directory shouldn't or couldn't be counted.
