### ISSUE TITLE
Switching with F6 between the 2 panes: Only partially working

### ISSUE THREAD

**Issue by Cos-mo** [linuxmint/nemo#1263]
You can switch between the 2 panes in Nemo by pressing F6 (so far so good), but this does only work with one of the 2 preconditions:

Either you have set in the preferences to always open Nemo with 2 panes.
Or (after having opened the second pane manually) after you have switched between the panes one time with the mouse.

There is indeed a workaround, if you do not want to use the mouse: go into one folder, than back into the parent folder (backspace key), after that F6 works.

Expected: F6 has to work without any of the mentioned conditions / workaround.

The issue is valid for all supported versions of Nemo, that means in LM 17.x and LM 18. (Not tested in LM 13.)

**Comment by ivangretsky** [comment]
Nemo could be a perfect solution for file management - it can be turned into 2-pane file-browser, has tabs. But this bug with pane switching makes everyone I know go for krusader, doublecmd or something else. Switching between sidebar tree and file pane(s) should be easy (and preferably done with Tab). Solving this one issue will make Nemo a usable solutions for many.

Right now it is even hard to say where the bug is. F6 works and does not work time to time, depending on what is open and what you have done before.

**Comment by herrdeh** [comment]
I'm using nemo on ubuntu 17.10. Great app BTW!!

This is the first time I learned about this shortcut which I so urgently was searching for. It's very unintuitive, therefore hidden well. Nice it exists - but why F6? - For historical reasons, I guess?
I'm placing a strong vote for using TAB and Shift-TAB instead. That's what many people would expect.

On my machine F6 works great with only one pane open. When two panes are open (F3), F6 only switches between the two panes, not from the column at the very left side to the panes - which I think is a flaw. 

BTW: Some kind of highlighting the active pane would be a great thing as well. But GNOME seems to  lack this in general.

Cheers,
Wolf
