### ISSUE TITLE
After selecting few files, create a new folder and move the selected files into it

### ISSUE THREAD

**Issue by nick-s-b** [linuxmint/nemo#1279]
Coming from Mac, this is one of my biggest feature requests for Nemo. Say you select few files and want to quickly move them to a new folder... well, to do it in Nemo is hard & labor intensive. In Finder, it's as simple as hitting Ctrl-Cmd-N. Would love it if Nemo had "New Folder with Selection" option.

**Comment by onlycparra** [comment]
Nautilus also do that, I would love to see this feature in Nemo :)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by TylerRick** [comment]
Has the Linux Mint team decided whether it might please add this sorely missed feature?

I'm keeping Nautilus around in addition to Nemo just for this one feature.

This feature is _so_ much more efficient than other methods  when you have a giant folder of many files and want to organize it into subfolders (which you can then easily move or rename afterwards — but at least this helps with the first step, which is to get the correct files into a folder together).

P.S. This was also requested in #560.

**Comment by Jeremy7701** [comment]
Simple enough to cut your selected files, create new folder, paste the files to your new folder.

**Comment by TylerRick** [comment]
Sure, the slow way is always good enough — until you learn a better way of doing things.

By your logic, then, we shouldn't have the option of including "Move to" in our context menus either — because any move operation could be performed using the cut and paste operations instead?

> ![image](https://user-images.githubusercontent.com/14151/124989635-2fafd980-dff4-11eb-93f8-d0e77099255a.png)

The method you proposed is 7 steps long, with step 4 being the most onerous when you're in a hurry:
1. Select files
2. "Cut"
3. "Create New Folder"
4. **Think of a name for the new folder.** _Manually_ type in that name, without any help from the tool. (We can't even use copy and paste to copy some part of one of the file names, for example, because the clipboard buffer is already being used for the file selection.)
5. Press Enter
6. Press Enter again to enter the new folder
7. "Paste"

The method that [Nautilus](https://wiki.gnome.org/action/show/Apps/Files) provides (which I and others love) is much more efficient, especially because it makes step 4 above _optional_ by providing a default name based on the selection:
1. Select files
2. Bring up context menu (a direct shortcut key would make this even sweeter)
3. Choose "New Folder With Selection"
    ![image](https://user-images.githubusercontent.com/14151/124990280-ff1c6f80-dff4-11eb-8f90-14b6a32fce2e.png)
4. Either accept the default name or choose a different name (_optional_) 
    ![image](https://user-images.githubusercontent.com/14151/124990468-44d93800-dff5-11eb-838d-342200bae4e8.png)
5. Press Enter

Assuming "Sort folders before files" option is unchecked, you can continue working/sorting in this outer folder, right where you left off:
> ![image](https://user-images.githubusercontent.com/14151/124990634-7b16b780-dff5-11eb-9691-ab314eca61cd.png)

Can you see how this method might be preferable when you have a folder with 100s or 1000s of files you want to organize it into subfolders? Especially when there is already a common filename prefix (such as a date) that you can use to group related files together.

And since Nemo kindly allows us to choose which commands to include in our context menu, those that don't use/like this workflow can be free to exclude it from their menus... Having more than one way to accomplish something isn't _necessarily_ a bad thing.

**Comment by Jeremy7701** [comment]
I make sure that no folder is allowed to have more than 30-40 items in it (with few exceptions).
But for those who aren't as organised as me, I can understand that they would need assistance. ;)

This isn't going to happen soon, since the Mint beta appears to be near to the end of testing.
Perhaps in the next release or two or three?

**Comment by kmpatel** [comment]
This is an old post but...

Enabling 'Move to' would do the trick but you have to select the path from $HOME.
Here's a alternative quick fix (assuming you have Zenity installed) that starts in the selected file directory.

Putting the bash script in your '~/.local/share/nemo/scripts' folder. 

> #!/bin/bash
> 
> NEW_FOLDER=\`zenity --file-selection --directory\` --title="Select destination"
> [[ $NEW_FOLDER ]] || exit 0;
> mv "$@" "$NEW_FOLDER" 

I'm sure there is  more elegant solution using "nemo_action".
