### ISSUE TITLE
Feature request: Nautilus-like title bar

### ISSUE THREAD

**Issue by jmgomezpoveda** [linuxmint/nemo#1363]
In the last few releases, the UI of Nautilus has evolved significantly.
Whereas some aspects may not please everybody, I think it is clear it makes a much more efficient use of space, including the menu, location and other buttons on the title bar.
Is there any plan of merging the new title bar and maybe other UI enhancements of Nautilus into Nemo?

**Comment by leigh123linux** [comment]
There is no chance that the lame nautilus changes will ever be merged into nemo

**Comment by jmgomezpoveda** [comment]
I personally think Nemo's UI feels outdated compared to Nautilus, especially the title bar.
In any case, I respect your point of view while I switch back to Nautilus.

**Comment by feren** [comment]
@jmgomezpoveda While I think Headerbars are a good idea for some apps, I agree and support @leigh123linux 's view on it, for example:
- XApps were built to look traditional and familiar for LM and Linux Noob users to fix what GNOME did to their GUIs on Apps and if it were for Nemo to have headerbars, it'd make it look inconsistent with everything else...
- GTK Headerbars are themed solely by their GTK themes, NOT METACITY THEMES, which causes issues in terms of noobs being confused that their metacity theme changing isn't affecting a said Headerbar-ed Application...

**Comment by robertbeal** [comment]
Hmmm I think mixing using and not using header bars is very poor UX regardless if some apps suit it or not. 

The ideal here would be that Nemo respected the Window settings. That way users can theme their DE how they like and have a consistent UI. Everybody is happy!

**Comment by JosephMcc** [comment]
> The ideal here would be that Nemo respected the Window settings. That way users can theme their DE how they like and have a consistent UI. Everybody is happy!

That just isn't going to happen. While I personally don't mind header bars, they impose serious design restrictions. If an app has a decent number of menu items, stuffing it into a header bar simply doesn't work. Nemo not only has that it also allows quite a few buttons on the actual toolbar and all of that would have to be stuffed into a header bar. Gnome has made it work by essentially making their app fit their UI design instead of the other way around. How do you think apps like gimp or inkscape are going to be with a header bar?. They offer a huge number of menu options. Would you endlessly nest them under a single menu button? Header bars work for simple applications. For complicated ones the design starts to fall apart. I suppose we could go the route some other apps have and simple remove all the options so we could use them :)

Besides all of that, Nemo would need a massive redesign internally to do something I'm not sure many people actually want.
