### ISSUE TITLE
Nemo sluggish on dragging shortcuts on desktop; cpu usage up to 49%

### ISSUE THREAD

**Issue by ghost** [linuxmint/nemo#1365]
Linux Mint 18.1, on a core2duo processor with SSD and 8GB RAM.

When I drag a 'link to' file (not a normal file), on the desktop (not elsewhere) the movement is often sluggish and jerky and Nemo uses up to 49% of my total CPU usage.

If someone could direct me towards video-recording software, I could show the problem in action.

I didn't have this problem before doing an in-place upgrade to Mint 18.1 from Mint 18, although admittedly I made some other changes around the same time (including installing and removing a kernel - because the newer kernel did not work).

EDIT: _Nemo is using up to some 40% CPU every few seconds, **whatever** I do!_ Indeed, when I do _nothing_ it does it!

**Comment by ACinnamonUserInUK** [comment]
Here is some more information.

The CPU spikes and concomittant lag do occur when dragging certain items, but seem to persist somewhat afterwards.

I attach two files containing debugging output.

[StackDump.zip](https://github.com/linuxmint/nemo/files/666919/StackDump.zip)
[strace_results.zip](https://github.com/linuxmint/nemo/files/666920/strace_results.zip)

**Comment by rcote98** [comment]
I can confirm this is happening to me too, tried to drag some "link to" files to desktop and nemo freezed completely. Also, now I am noticing regular CPU spikes too, that seem to coincide with the nemo freezes. Rest of the system was perfectly responsive though. I don't really know how to sent console output, but I will do so as soon  as I figure it out.

**Comment by rcote98** [comment]
Well, here's a screenshot of the CPU usage peaks. That was by just _attempting_ to move the link around in the desktop.

Also, I've noticed its pretty slow at opening links such as the ones in the image from the desktop (got an SSD, too), to the point where it is **faster** to enter the Home shortcut and navigate to the folder. 

Running in a Celeron 3050 processor with LM18.1.

![screenshot](https://cloud.githubusercontent.com/assets/21984207/22388566/64309450-e4e1-11e6-8853-7bf56be555ef.png)

**Comment by rcote98** [comment]
Can confirm this only happens to links, as there is no hangs once they're deleted, so maybe its due to some bug regarding links in general?

This assumption is enforced by the fact that similar hangs occur when clicking the back arrow in the browser itself (As I guess it kinda works as a link to the previous folder)

**Comment by tsjnachos117** [comment]
IDK if this report is about nemo or nemo-desktop, but I've had similar issues with the latter that I thought I should report.

I can confirm this happens with nemo-desktop everytime I try to drag a file. It also happens when I right-click a file.

I've also noticed that nemo-desktop sucks up my CPU if I download a video. (Because, IMHO, web browsers aren't particularly great video players, I prefer to save videos to my desktop, and delete them when I'm done watching them.) I think in that case, nemo-desktop is re-thumbnailing the file over and over.

@rcote98: When you say "links" are you referring to symbolic links? I don't have any symbolic links, and I still get major lag and CPU spikes.

**Comment by CottonEaster** [comment]
> IDK if this report is about nemo or nemo-desktop

When I reported this problem I was on Mint 18.1, on which nemo-desktop did not exist. I do not seem to have the probem on Mint 18.2.

**Comment by tsjnachos117** [comment]
I don't know much about Mint versions because I use Ubuntu 16.04 (I installed Cinnamon via the embrosyn/cinnamon ppa). Thank you for clarifying that.
