### ISSUE TITLE
No folders on 2nd monitor

### ISSUE THREAD

**Issue by foremancr** [linuxmint/nemo#1385]
I have placed folder on the 2nd monitors and after a reboot the folders are no long visible.  They also don't appear in the tool bar at the bottom of the desktop.   I am using the Linux 18.1 64 bit software download, with a Nvidia 1070 video card

**Comment by tonywhelan** [comment]
Linux Mint Cinnamon 18.1 64 bit, Cinnamon 3.2.7, kernel 4.4.0-31-generic. Onboard graphics card Xeon E3-1200, two monitors, primary is a 23" Asus connected via DVI, secondary is a 24" AOC connected via HDMI cable. Both monitors are set to same resolution.

Under the "Desktop setting" I selected "show desktop icons on all monitors", but when I create or move a desktop icon (or a folder) on/to the non-primary monitor, then log off and back in again, the icon or folder does not display any more on the non-primary monitor.

If I use Nemo to look in the Desktop folder, the icon or folder is actually still there, and I can drag it from Nemo back to the primary desktop.

**Comment by ovari** [comment]
This may be related:

Linux Mint 18.1 Cinnamon 64-bit with 2 monitors does not show the first 5 files/folders on the Desktop after restart; however, it shows all the files when using Nemo 3.2.2.

Using 2 monitors where the primary monitor is smaller as shown in:
![image](https://cloud.githubusercontent.com/assets/17465872/21748993/f5e85670-d5e7-11e6-8553-620fd8e2ec91.png)


Files and folders are shown when created on the Desktop on the primary monitor (smaller Laptop eDP1 monitor); however, once the computer is shut down, and then the computer is turned on **some** of the files do **not show** on the Desktop (primary Laptop eDP1 monitor).

An explanation could be that the first 5 files/folders not shown could be displayed to the left of the primary monitor as the secondary monitor shows more to the left than the primary monitor.

Can you reproduce this? Hopefully it can be fixed too. Please advise if you need more information.

Thank you

**Comment by Mint1864** [comment]
Hello:
This is probably related.

Mint 18.0 64bit.
Cinnamon 3.0.7
NVIDIA Corporation G84GL [Quadro FX 370] (rev a1) card
Twin SyncMaster 940N monitors.

Same thing happens when creating a new document on the secondary monitor.
ie: right click -> Create new Document -> New XXXX document = no document is created on the secondary monitor but it does show up in the file manager (Nemo).

Creating a new document on the primary monitor works as intended.

Funny thing is that this happens _only_ until I create a new document on the primary monitor and stays that way _only_ while this new document is there.

If I delete the new document from the primary dersktop, the issue persists. 
ie: no document is created on the secondary monitor but it shows up in the file manager.

Desktop options has "Allow icons from missing monitors to be displayed on the existion ones" set to ON.

Thanks in advance.

Mint1864

**Comment by thatlhurt** [comment]
Same problem for me with 18.1 with disappearing icons.  No issue with prior releases.  Dual monitor setup with one 22" LG connected via DVI and a 27" Dell connected via HDMI.  Graphics card is a Nvidia GTX970.  Problem can be replicated booting from the 18.1 live image using software rendering.  Problem does seem to be related to having changed the primary display from the default.

**Comment by thatlhurt** [comment]
This is also reported as Cinnamon issues 5978 and 6113.

**Comment by foremancr** [comment]
I went back to Linux Mint 18.0 and all works well. The second Monitor works as it should.   I was using Linux Mint 18.1 64 bit with Nvidia 1070 video card.

**Comment by thobin71** [comment]
Both me and my boy have the same issue with 18.1 on our dual monitors setups.  It also rearranges the icons when I do get them back up.

**Comment by Timmy93** [comment]
* Nemo version (nemo --version) - nemo 3.4.5
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 18.2 - Cinnamon
 * Graphics hardware *and* driver used - Intel i5 5200u integrated gpu and default driver
 * 32 or 64 bit - 64bit

Still have the same problem! 
2 monitor of different size and at reboot the icons are rearranged.

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4 on Linux Mint 20. Assuming auto-arrange off, after reboot icons on 2nd display are in the same place as before reboot.
