### ISSUE TITLE
Bookmark of Deleted Folder Causes Nemo to Take 100% of CPU Resources

### ISSUE THREAD

**Issue by carltda** [linuxmint/nemo#1398]
If a folder on a 2nd hard drive (not the boot drive) is bookmarked and then later deleted from the hard drive, but NOT the bookmark, CPU resources devoted to Nemo jump to 100% and stay there until the 2nd hard drive is unmounted. Also, while all CPU resources are taken by Nemo, file retrevial speed from the 2nd hard drive dramatically decreases from milliseconds to minutes.  If the orphaned bookmark is removed, both Nemo and hard drive performance return to normal.   If is as though Nemo gets stuck looking for a link that is not there and will not time-out

**Comment by xenopeek** [comment]
We believe this issue is fixed. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.

**Comment by carltda** [comment]
Ok, 
Thanks
