### ISSUE TITLE
Strange renaming bug

### ISSUE THREAD

**Issue by donlencho** [linuxmint/nemo#1401]
I'm sorry I cannot be more precise but I find it hard myself to reproduce this bug, although I've experienced it several times in Mint 18.1.
It's about renaming a file or folder in icon view (haven't tried in other views) either by pressing F2 or via the contextual menu.
Sometimes it just doesn't work, meaning nothing happens when trying to rename it (the name is not selected as an editable text).
I thought it was linked to extension-less files because I had it several times with such files, but it's not so clear.
Also, when it happens, it's happening for the whole folder (all files and sub-folders alike), I cannot rename anything. Then going to another folder and there it works, same Nemo window. And it's not about permissions, I have write access on all files in question.

As anyone else experienced something like this?

**Comment by sparkchaser** [comment]
I thought I was having this problem in the past.  I eventually noticed that rename was indeed working, only the default color scheme for selected, editable text was almost identical to that of normal, non-editable text.  The text was slightly bolder, but lacked the clear visual cues I was expecting.  Files with an extension are _slightly_ less confusing because the filename will be highlighted but not the extension, and the contrast between them might be more noticeable.

Try this as a test.  With Nemo in either "icon" view or "compact" view, select a file, press F2, then just start typing.  If the file name changes, then rename is working and this is simply a lack of appropriate visual feedback.

For me at least, "list" view uses a completely different color scheme and doesn't present this problem.

**Comment by donlencho** [comment]
Just to clarify, this is not about visual feedback, I know how to rename files and find the visual feedback pretty clear. I'm just talking about situations where it does not work.
If I can reproduce it more clearly, I will post here again.

**Comment by Hangarter35** [comment]
Hi 

I had this problem too some days ago : Sometimes, within one folder, nore F2 or right clic/rename could edit the text of the name. Nothing happened ... 
But renaming worked in all other places.
Of course it is not a problem of Rights since my user owns all drives, and since this problems appears randomly and fortunately rarely.

**Comment by xenopeek** [comment]
There's not enough here for us to go on. If the issue still happens, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.

**Comment by pols12** [comment]
I have found a way to reproduce this bug at home:

1. Open `Images` folder.
2. Open an other directory (or `Images` too) in another tab.
3. Try to rename a file in `Images` folder→ it’s impossible.
4. If you close all other tabs, or if you go in another directory, renaming works well.

@donlencho Can you reproduce your bug like me with these steps?

Note that I’ve updated Nemo to 3.8.5 yesterday and I believe it the first time I encounter this bug.

**Comment by donlencho** [comment]
Hi,
No sorry, I followed your procedure and it worked fine. On my side, this is really happening rarely and I have not found a pattern, I just don't get it.

**Comment by pols12** [comment]
I think I have a different bug than you (probably #1948), but I just want to fix the reproducing way: `Images` folder is not required, nor multitabs opening.
The only required element is to make a vertical scrollbar display, reducing vertical size of the window.
