### ISSUE TITLE
[Feature Request] Open vs Execute

### ISSUE THREAD

**Issue by MathewAlden** [linuxmint/nemo#1417]
This is a feature request. Do with it whatever you'd like.

With Nemo, say I have a shell script or some other plaintext executable, and it's NOT set to be executable at the moment. When I right click it, Nemo give me the option to Open it with my default text editor, or to Open With -> other text editors. This is all great.

Now I set the plaintext to be executable. I right click it, and I have the option to Open it, as in run it, or to Open With -> other text editors. I no longer have the option to open it with my default text editor, because now the Open button runs the application instead. This is unintuitive. It should give me three options: Run, Open with default text editor, or Open with -> other text editors.

I poked around in the source code trying to add the feature, but I didn't know what I was looking for.

So if you guys wanted to consider this, that'd be awesome. Thanks

**Comment by zeehio** [comment]
My current solution is:

- Edit/Preferences
- Behavior tab
- Executable text files: Ask each time

But I agree that the optimal solution for executable text files would be:
- On right click show three options: Edit, Run, Edit with... (I suggest "Edit" instead of "Open" because "Open" may be confused with "Run")
- On double click: Whatever is set in the "Executable text files" option in preferences

**Comment by AugustZellmer** [comment]
Oh I forgot that was even an option. Maybe that's the solution I was looking for. Huh.

**Comment by xenopeek** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed. For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
