### ISSUE TITLE
[Feature Request] If Nemo Desktop is NOT running, launch it on Nemo Files Startup

### ISSUE THREAD

**Issue by feren** [linuxmint/nemo#1511]
Right now, the last time I checked, after running `nemo -q` in 3.4, and then running Nemo's File Browser Process, the Desktop process isn't run, which is inconsistent with the Nemo Versions before the Desktop was a separate process, so could Nemo check if the Desktop Process is running at Startup, and then start it up automatically if the Process isn't found to be running?

**Comment by leigh123linux** [comment]
Why do we need to do this? cinnamon session files start nemo-desktop.

**Comment by feren** [comment]
@leigh123linux Sometimes, people may want to quit Nemo for a certain reason, so they do, but they may not know that Nemo now has a separate Desktop Process, and so they then may be wondering where their Desktop Icons are, so if a feature to add nemo-desktop running if not running would make the process more seamless and would add some more consistency with older Nemo Releases, where starting Nemo would being back the Desktop Icons too, unlike Nemo 3.4 right now...

**Comment by mtwebster** [comment]
The whole point was to separate out the behavior of the desktop and normal windows.  If they 'kill' nemo, it won't affect the desktop.  If nemo crashes, it won't affect the desktop.  I don't see the point of tying them back together.

**Comment by feren** [comment]
@mtwebster Sorry, meant to say kill as in 'nemo -q' it...

**Comment by mtwebster** [comment]
But even that doesn't have any effect on the desktop process.  What confused people before was that messing around with 'nemo' *would* affect their desktop.  *"How come when nemo crashes, my desktop icons disappear?"*

The only behavior we've really altered (which was never actually defined) is that starting `nemo` from a terminal or script won't return immediately, if nemo wasn't already running (because previously, the desktop window would maintain the process.)  I have a fix for that on a branch but we've decided to wait if it's really missed or not - people should be using `xdg-open` which will achieve the same thing (unless for whatever reason, nemo isn't their default mimetype handler for folders.)

**Comment by feren** [comment]
@mtwebster Odd, I tried it once before on the Embroysn PPA, and it killed both Desktop and normal Nemo, and then when Nemo was ran, Desktop didn't start automatically...

**Comment by feren** [comment]
Nevermind, if it's fixed now, it's fixed...
