### ISSUE TITLE
Mint 18.2: changing icon size re-arranges all of the desktop icons

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/nemo#1539]
I find this somewhat trying. At the least, Cinnamon could warn you that it will (or may?) happen.

Thanks.

**Comment by mtwebster** [comment]
This is on purpose.  Due to how icon positions are stored currently, there's no elegant way to re-position the icons when they're resized.  Re-sorting hides this ugliness for now.  As mentioned in https://github.com/linuxmint/nemo/issues/1540, there's still quite a bit of work planned, some of which should take care of this issue also.

I really don't expect resizing icons is going to be a common thing, once an appealing size is found for a user, so it wasn't a huge concern at the moment.  Showing a warning is overkill for this.
