### ISSUE TITLE
WebDAV: Nemo uses old password and ignores a new one

### ISSUE THREAD

**Issue by shred** [linuxmint/nemo#1556]
```
 * Nemo version: nemo-3.4.4-2.fc25.x86_64
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - Fedora 25
 * Graphics hardware *and* driver used: Intel, vanilla driver
 * 32 or 64 bit: 64 bit
 ```

**Issue**
After changing my password on a NextCloud server, Nemo is unable to connect via WebDAV, but shows error "Unauthorized" in spite of entering the correct new password.

**Steps to reproduce**
- Use Nemo to connect to a password protected WebDAV server. Check "Remember this password" in the connection dialog. Nemo connects to the server and correctly shows the files.
- Unmount the connection.
- Change your password on the WebDAV server.
- Use Nemo and try to connect to the server again, using the new password. Nemo now refuses the connection and shows error "Unauthorized".

**Expected behaviour**
- Nemo accepts the new password and successfully connects to the WebDAV server.

**Other information**
When I used Wireshark to check the WebDAV connection, I found out that Nemo asks for the new password, but then **still sends the old password** to the server. The server correctly refuses the connection with an "Unauthorized" error.

I openend the Gnome "Password and Keys" tool (seahorse). There I found the connection in the "Passwords" section and deleted it. 

After that, I could successfully use Nemo to connect to the WebDAV server again, with the new password.

**Comment by leigh123linux** [comment]
gnome-keyring is responsible for password handling not nemo.

**Comment by mind-overflow** [comment]
Removing the old password from the keyring fixes it. The issue, as described by OP, is that when I am on the "Connect to server" window, and I type the new password, the old one is instead used. This is obviously not the intended way for it to work - when I type a password, it should be used - not a different one that I have to open another app to even know is there.

And yes, I understand that this is just how gnome-keyring works - but the implementation feels unintuitive and wrong. I wonder what an inexperienced user would do in this case. I am a dev and it took me various hours of Nextcloud/Apache troubleshooting (nothing looked wrong, and nothing *was* wrong indeed) to finally come to the conclusion that the issue comes from my machine. And then I found this issue.

I type a password -> the password is used. This is how it should work. So, either remove all older password for the same login, or show me a list with all the saved passwords directly on that window so that I can delete it or choose the correct one.

**Comment by chesamo** [comment]
I am commenting here, 5 years later, because the issue persists in 6.6.3 and has clearly been ignored. mind-overflow is correct in that this is VERY confusing behaviour for the end user. If a new password is supplied, gnome-keyring should NOT be consulted and this NEW password should be used instead.

These are basic UX principles. The settings on-screen should always override settings hidden off-screen (esp. if they're in a different program entirely).
