### ISSUE TITLE
Feature Request: readability improvements for desktop icon text

### ISSUE THREAD

**Issue by x11x** [linuxmint/nemo#1658]
Hi,
I would like to suggest some ideas to make desktop icons more readable on any background.
I use the background slideshow feature with a variety of different images. Some backgrounds make the desktop icons very hard to read and I have several ideas that could reliably make desktop icons more readable on any background.
The simplest would be a semi-transparent background behind the text. This could be just the label part, or it could be a box around the label and icon. The color would have to be opaque enough that the chosen text color (white by default) would stand out. I think this would have the effect that if you were trying to focus on the icons, you could read them easily, but you could still see the background through it.
I know how to style the icon text color using .nemo-canvas-item selector in gtk.css file. I tried using a background-color property to change the label background but that only works when the icon is selected, so it looks like this probably can't be done in CSS.
Another idea I had was to compute the average color of the background image and then compute a complementary color that would contrast well with the average color and set that as the text color. This is a bit more complicated but would be a cool feature.

**Comment by brownsr** [comment]
It sounds like you are talking about text shadow.  Here's an example showing some uses you might want to explore and adapt   https://designshack.net/articles/css/12-fun-css-text-shadows-you-can-copy-and-paste/

**Comment by mtwebster** [comment]
As of e59cae7bd231b the desktop icons are styled the same way regardless of current theme.  The classes are in [src/nemo-style-application.css](https://github.com/linuxmint/nemo/blob/master/src/nemo-style-application.css), and any theme-level overrides are ignored.

This is pretty much the only way to guarantee readable text at all times.  Many distros ship with Adwaita theme as the default, which will never support Nemo.  There were attempts (https://github.com/linuxmint/nemo/pull/782) to embed Adwaita support but this would just complicate things for the sake of a single obstinate theme.  Other 'dynamic' solutions I'm sure could work, but they're honestly not worth the time, effort, and probably side effects that would result from trying to implement them.  

So this current situation, while not ideal, at least prevents complete failure of readability on any theme or background color/image.  Due to ~~a bug~~ an issue with how style priorities are handled  in Gtk, it's not possible to guarantee this while still allowing individual themes to do their own thing.

There are a number of closed bug reports discussing this in the nemo and Cinnamon github pages.

**Comment by x11x** [comment]
Agreed that this is not worth time and effort if its not a simple thing. The default _is_ already very good it should be said — legible on a range of different backgrounds.
I don't know much about themes but I can understand the complexities of upstream dependencies, didn't realise this was an issue here.
I've played a bit with the text-shadow and will share what I came up with in case anyone else needs this.
It improves legibility against light backgrounds but having a big black shadow might look a bit odd to some (but to me its better than being unreadable). I like that it blends in to dark backgrounds so you don't notice it at all in those cases.
```
.nemo-desktop.nemo-canvas-item {
  text-shadow:  1px  -1px   2px  rgba(0,0,0,0.4),
               -1px   1px   2px  rgba(0,0,0,0.4),
                1px   1px   2px  rgba(0,0,0,0.4),
               -1px  -1px   2px  rgba(0,0,0,0.4),
                2px  -2px   2px  rgba(0,0,0,0.4),
               -2px   2px   2px  rgba(0,0,0,0.4),
                2px   2px   2px  rgba(0,0,0,0.4),
               -2px  -2px   2px  rgba(0,0,0,0.4);
  /* A simpler version, looks almost the same:
  text-shadow: 0px 0px 2px #000, 0px 0px 2px #000;*/
}
```
If I wanted to try the always-visible label background idea, it sounds like I could edit nemo-style-application.css and rebuild? I won't do this just now because the text shadow gets the job done.
As for the dynamic text color idea, I could almost do this in a standalone script as long as I could find some way to get notified of Cinnamon background changes (maybe this is published on D-Bus?) and get the path to the background image, but again, not worth the time and effort.
