### ISSUE TITLE
Selecting a folder and directly hitting Return crashes nemo sometimes

### ISSUE THREAD

**Issue by bpiepiora** [linuxmint/nemo#1673]
```
 * Nemo version 3.6.4
 * Windowed nemo
 * Distribution - Fedora 27
 * Graphics hardware *and* driver used: Can be submitted, if necessary for this issue
 * 64 bit
 ```

**Issue**

Selecting a folder and directly hitting Return crashes nemo sometimes

**Steps to reproduce**
1. Choose a deep folder
2. Select the next folder in the window and quickly hit Return to enter that folder
3. Sometimes it crashes directly, sometimes after a few tries

**Expected behaviour**

No crash at all

**Other information**

**Comment by xenopeek** [comment]
That's not a lot to go on. Is this issue still happening for you with Nemo 3.6.5? If so could you try starting Nemo from the terminal to collect its output and share that if you managed to reproduce the issue. Run `killall nemo` first to kill any already running Nemo session as otherwise starting Nemo will just attach a new window to the running session and not give you that output.

**Comment by clefebvre** [comment]
This needs a stacktrace.
