### ISSUE TITLE
[Improvement] Format a partition from the right click menu.

### ISSUE THREAD

**Issue by SiamSami** [linuxmint/nemo#1713]
It's not an issue but rather an improvement. While using nemo, we sometimes want to format a partition from the nemo file manager. We don't want to format the partition from "other" programs. Even Windows has this feature.

So please add this feature as soon as possible

**Comment by leigh123linux** [comment]
Even if we did add something to the right click menu it would just call another program to format.

-1 to adding format to nemo

**Comment by SiamSami** [comment]
@leigh123linux  Well, why don't you take a look at Nautilus File Manager's code. I mean Nautilus has this "Format" feature.

**Comment by mtwebster** [comment]
Not sure what distro you're on (Please don't ignore the issue template.)

In Mint, we've had this capability for some time, which integrates Mintstick, but a bug cropped up in the last couple releases that prevented the format entry from appearing in the context menus in the sidebar.

This bug is now [fixed](https://github.com/linuxmint/nemo/commit/e0cd29e71f01860992a51b670e7dd6a47c03e3a0) for the next release.  If you're on a different distro, this is something that is trivial to add (again, with a patched version,) using Nemo Actions.

See [this file](https://github.com/linuxmint/mintstick/blob/master/share/nemo/actions/mintstick-format.nemo_action) for an example.  Additional info can be found by opening the Plugin window and clicking the folder button below the Actions list.
