### ISSUE TITLE
[Feature Request]: .nemo_action for alt-drag context menu

### ISSUE THREAD

**Issue by SubhutiBottleneck** [linuxmint/nemo#1799]
Background:

I am using the Nemo which comes with Linux Mint Cinnamon 18.3.  I am a complete novice, but I really would like to add an "add to archive here" or "extract archive here" to the drag context menu, just like I have grown to appreciate very much in Windows.

Requested feature:

I would like to be able to add custom menu items to the context menu which appears when when I drag a file or a group of files with the left button and the alt-key pressed.  When I release the left button, a context menu appears asking if one wished to copy here, move here, or make link here.

It would be such a nice feature to be able to add a command to decompress an archive to the specified destination directory, or to compress the files into a new archive file in that same destination.

Background:

In Windows, when one installs an archiving utility, it often integrates with the context menus in this fashion, for instance 7-zip, and I also believe WinZip and WinRar do the same.   It saves a heap of typing and mousing, and ever since I discovered this, I have almost exclusively extracted and created archives by this shortcut.

I really would like to be able to move away from Windows, as I see where it's going with Windows 10. Eventually, Windows 7 probably won't work any longer, and it would be wonderful to enter a world of freedom and configurability.   So I hope it is possible to achieve this functioning in Nemo as well.

Question:

Is it possible already to alter a .nemo_action file, so that the command is added to the context menu in question?

If not, is it something you would consider adding to the design?  I can only say that I find it immensely useful for mundane tasks like working with archives. It really saves a bunch of tedious typing, and it uses the nature of the GUI to do things which take much longer "by hand," whereas many GUI programs are no quicker or better than command-line programs.  It seems a feature a graphical file manager ought to have.

**Comment by revast** [comment]
It is quite easy to add actions in nemo. I actually made "extract to" and "extract here" actions, because I like the position they are placed in the menu as actions.

[actions.tar.gz](https://github.com/linuxmint/nemo/files/1810479/actions.tar.gz)

```
[Nemo Action]
Active=true
Name=Extract here
Comment=Extract "%f" here
Exec=file-roller --extract-here %F
Icon-Name=gnome-mime-application-x-compress
Selection=notnone
Extensions=zip;7z;ar;cbz;cpio;exe;iso;jar;tar;tar.Z;tar.bz2;tar.gz;tar.lz;tar.lzma;tar.xz;tgz;rpm
Quote=double
```
```
[Nemo Action]
Active=true
Name=Extract to...
Comment=Extract to a folder of your choice.
Exec=file-roller --extract %F
Icon-Name=gnome-mime-application-x-compress
Selection=notnone
Extensions=zip;7z;ar;cbz;cpio;exe;iso;jar;tar;tar.Z;tar.bz2;tar.gz;tar.lz;tar.lzma;tar.xz;tgz;rpm
Quote=double
```
Put these into $HOME/.local/share/nemo/actions and you are done.

About the customizing of "drag & drop with ALT pressed"-menu popup:  

I also support this idea, though I guess its not the top priority for now. Also I do not know how complicated it would be to achieve that code-wise. If someone tackles it, It would be nice to add icons as well, and that one can use nemo actions syntax with a special key which lets the action be shown in this menu.

PS: it would be cool to add a screen-shot or a mock-up of what you want to achieve, github supports drag&drop of graphics, like this:

![screenshot_2018-03-14_04-00-31](https://user-images.githubusercontent.com/8189198/37396940-a50e221c-277a-11e8-8777-083ff27fc8f1.png)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
