### ISSUE TITLE
An option to use normal icons in menus instead of symbolic ones

### ISSUE THREAD

**Issue by POPCORNS1068** [linuxmint/nemo#1877]
```
 * Nemo version: 3.8.3
 * Is issue with desktop or windowed nemo? Both.
 * Distribution: Arch Linux
 * Graphics hardware *and* driver used: NVIDIA Geforce GTX 1080, driver version 396.24
 * 64 bit
 ```

**Issue**
The icons in menus are now symbolic, but can I please at least have an option to use the normal ones?

Old:
![old](https://user-images.githubusercontent.com/40209997/41363357-3efd3524-6f66-11e8-8035-924f9b66876b.png)

New:
![new](https://user-images.githubusercontent.com/40209997/41363365-436653fc-6f66-11e8-976d-75c3ca2b2b6c.png)

**Comment by JosephMcc** [comment]
Thanks for the request but I don't think we are going to add an option to change this.

**Comment by POPCORNS1068** [comment]
Not sure if I should open a new issue for this.

Are the documents, music, images, videos and downloads folder icons supposed to be like this? Or are their symbolic counterparts going to be added in the future?

**Comment by JosephMcc** [comment]
> Are the documents, music, images, videos and downloads folder icons supposed to be like this? Or are their symbolic counterparts going to be added in the future?

Not sure what you're asking.

**Comment by POPCORNS1068** [comment]
I have set the bookmarked folders' icons to match their names. (e.g. `folder-downloads` for the downloads folder), these icons show up normally in the file explorer but not the sidebar.

![image](https://user-images.githubusercontent.com/40209997/41366278-27c8fff2-6f6e-11e8-8012-a1a388088ff5.png)

**Comment by JosephMcc** [comment]
Try setting it to folder-downloads-symbolic and see if that fixes the issue.

**Comment by JosephMcc** [comment]
Oh wait, no you don't want to do that. Changing that could be complicated since not all icons you could choose would have a symbolic counterpart.

**Comment by mtwebster** [comment]
The custom icon set for a given folder is irrelevant in the sidebar.  It goes by the uri and if it matches an XDG location I believe.  So, your sidebar downloads folder should always be a download-type icon.  The only reason this wouldn't be the case is if the icon theme has no -symbolic icon for a given location.

**Comment by JosephMcc** [comment]
If I move downloads into my bookmarks it gives me the proper icon here.

**Comment by POPCORNS1068** [comment]
I'm using Mint X Aqua icons. Changing it specifically to symbolic makes it use the symbolic icon everywhere

**Comment by NikoKrause** [comment]
You are using Arch, maybe that's why?
In Mint there are symbolic versions of default icons as Download, Music, Videos, etc.
![screenshot-area-2018-06-13-215226](https://user-images.githubusercontent.com/8415124/41374762-623baf1e-6f54-11e8-9eeb-ffd78b4879eb.png)

It might also be something different, namely what mtwebster said. Maybe your version of Mint-X has no -symbolic icon for those locations.
Look in `/usr/share/icons/Mint-X/places/scalable`, if there's `folder-videos-symbolic` `folder-pictures-symbolic` etc.

**Comment by POPCORNS1068** [comment]
![image](https://user-images.githubusercontent.com/40209997/41389425-5fea348c-6fc3-11e8-897e-fe8f03879028.png)

These icons are present.

**Comment by POPCORNS1068** [comment]
Ok, I got the icons to show after using `xdg-user-dirs` to change these folders' locations to the custom location I'm using. Thanks for helping.

**Comment by Cyborgscode** [comment]
Sorry, but symbolic icons are just crap! Have an option to EASLY revert this change would be nice. We are not Windows10 .. we do not want black and white symbols for the systems.

**Comment by mtwebster** [comment]
No, sorry.

It's not trivial to change back and forth.  It only looks trivial to you because all you see is the end result.

I'm sorry you feel this way - we're not trying to be Windows 10, don't be dramatic.  They don't have to be black and white - the colors can be controlled by the Gtk theme.  The whole point of this is so they can be integrated into themes better.  This also only affects the sidebar and various UI elements, *not* the actual file views.

**Comment by sc44** [comment]
@NikoKrause 
Arch has a great build system, that's why i am using Arch.
@Cyborgscode
in Nemo 3.8.4 you can use bouth svg and png.

**Comment by sc44** [comment]
@NikoKrause
Arch has a great build system, that's why i am using Arch.

@Cyborgscode
in Nemo 3.8.4 you can use bouth svg and png.
![bildschirmfoto vom 2018-07-11 17-23-44](https://user-images.githubusercontent.com/38653443/42584120-c8f7a7d2-8532-11e8-86b5-024ff01e0c67.png)
