### ISSUE TITLE
Sorting order

### ISSUE THREAD

**Issue by vstepaniuk** [linuxmint/nemo#1883]
```
 * nemo 3.4.7
 * desktop
 * Ubuntu 17.10 (64 bit)
 ```
Could you please point to a place in source code, or explain it yourself, what is the sorting order used in Nemo? Like, what characters go before what?

**Comment by damian101** [comment]
Nemo uses the same sorting order as the ls command in terminal.
Dolphin is the only file manager for Linux I know of that can sort files in another way.
Dolphin calls his default sorting order "Natural". It is the same sorting order I know from Microsoft Windows Explorer.
I switched to Plasma because of that reason.
I always put an underscore in front of a folder name if that folder should show up at the top.
Nemo just seems to ignore everything but letters and numbers for sorting.

**Comment by damian101** [comment]
#2128

**Comment by xenopeek** [comment]
Nemo sorting functions are found among others in https://github.com/linuxmint/nemo/blob/master/libnemo-private/nemo-file.c. Nemo converts names to collation keys (based on your locale) before sorting, using functions from https://gitlab.gnome.org/GNOME/glib/-/blob/master/glib/gunicollate.c. This allows for example for natural number sorting e.g., so that "42towels" is sorted before "1024towels". Files starting with a '.' or '#' are considered special and are always sorted last.

Downside comparing collation keys is that some are accustomed to prefixing filenames with some special character to make them sort at the top of the list. That may not give expected outcome. You can instead achieve this in Nemo by pinning a file (from the context menu or the Edit menu select Pin, or press Shift+Ctrl+D).

There is a detailed discussion in #2135 about Nemo sorting.
