### ISSUE TITLE
Create desktop shortcuts

### ISSUE THREAD

**Issue by rypz79** [linuxmint/nemo#1887]
```
 * Nemo version: 3.6.5
 * Issue with: Desktop Nemo
 * Distribution: Ubuntu 18.04 x64
 * Desktop Environment: GNOME 3.28.1
 * Graphics: lspci -nnk | grep -iA2 vga 
   00:02.0 VGA compatible controller [0300]: Intel Corporation HD Graphics 5500 [8086:1616] (rev 09)
   Subsystem: Hewlett-Packard Company HD Graphics 5500 [103c:802d]
   Kernel driver in use: i915
```
**Issue**
Can't create any desktop shortcuts (context menu -> create desktop shortcut) or enable some useful ones like  Home , Music , Download ,Network , Mounted volumes etc... (similar to GNOME tweaks for Nautilus)
Only icon dragging works

**Steps to reproduce**
Right-click on any file or folder icon  

**Expected behaviour**
Create desktop shortcut on context-menu

**Other information**
![screenshot from 2018-07-05 08-18-19](https://user-images.githubusercontent.com/28814757/42303898-285c9b80-802c-11e8-827a-1ac7116d9eb8.png)

**Addendum:**
Creating desktop shortcuts (drag&drop , other than those in GNOME tweaks) makes duplicate icons as seen in the picture. The red marked icons are inaccessible and redundant 

![screenshot from 2018-07-05 13-03-36](https://user-images.githubusercontent.com/28814757/42317340-cc313d6a-8054-11e8-8960-fa8a2ef48cc0.png)

**Comment by mtwebster** [comment]
First, either uninstall nautilus or at least disable it from trying to manage the desktop:
```
gsettings set org.gnome.desktop.background show-desktop-icons false
```
The inaccessible icons are likely from the fact that both nautilus and nemo are running on the desktop (nemo is smart enough to detect something else is managing the desktop, nautilus is not)

You probably should log out/in to reset the desktop after this.

Gnome Tweaks is useless for anything nemo-related.

Since you're not using Cinnamon (I think?) you can enable some special icons using dconf-editor or from a terminal at `org.nemo.desktop.`  These are normally accessible via cinnamon-settings.

There is no 'make link on desktop' context item, but there is a simple 'make link' - if you click the (+) symbol next to the Open context item at the top of the menu, it will show additional menu items, including this one.

**Comment by rypz79** [comment]
You're right. Just remove Nautilus and got that settled.
Just one more little thing the font is black and I prefer white. couldn't find any setting for that in d.conf
![screenshot from 2018-07-10 17-07-50](https://user-images.githubusercontent.com/28814757/42515366-480bacbe-8464-11e8-96bb-ccb459636ce7.png)
Thanks
