### ISSUE TITLE
Uneven distribution when switching to manual arrange mode for the first time

### ISSUE THREAD

**Issue by NicoWeio** [linuxmint/nemo#1908]
```
 * Nemo version 3.8.3 (reproduced on 4.6.4, see @xenopeek)
 * Linux Mint 19 (live USB) 
 ```

**Issue**

When switching to manual arrangement for the first time, all files appear as a giant pile, not distributed evenly at all.

**Steps to reproduce**

Navigate to a folder whose files haven't been arranged manually so far. Then switch to manual arrange mode.

**Expected behaviour**

I'd expect some kind of spread across the free space.

**Screenshots**

![screenshot from 2018-07-24 12-43-40](https://user-images.githubusercontent.com/12870528/43138817-64be5ab8-8f50-11e8-8789-a392b8692ed7.png)
![screenshot from 2018-07-24 12-43-53](https://user-images.githubusercontent.com/12870528/43138819-64de863a-8f50-11e8-94e2-601a74877cb1.png)

**Comment by xenopeek** [comment]
Confirmed this still happens on Nemo 4.6.4.

If in my home directory in Nemo and toggle View > Arrange Items > Manually it randomly puts some folder scrolled _waaaay_ far to the right. See the width of the scrollbar at the bottom in screenshot. I could also reproduce it throwing icons all on top of each other (top icon obscuring everything below it). 

![image](https://user-images.githubusercontent.com/21159972/85927469-8e515c00-b8a6-11ea-8bf9-2d5f87191a2a.png)

Should manually arranging not inherit icon locations from the previous arrangement? Otherwise maybe this option needs removing.

**Comment by icarter09** [comment]
I'm noticing several things with "Manually" arrange mode. 

1) First time selecting "Manually" in directory will cause all the items in that directory to stack on top of one another.

2) After you have manually moved things around, the second time you select "Manually" it is supposed to go back to back to whatever arrangement you set the first time. But that is not happening. Sometimes it's spaced far apart or just spaced in a different arrangement. I also had a directory vanish, but eventually reappeared after several "Manually" toggles.

3) If you select "Manually", then select another option...I noticed that is not setting the radio button selection to the new option, but instead "Manually" is still selected.

**Comment by icarter09** [comment]
I put up a PR that should address the issue of first selecting "Manually" and all the directories/files are stacked on top of one another.
