### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by sergiozar** [linuxmint/nemo#1913]
```
 * Nemo version (nemo --version): All
 * Is issue with desktop or windowed nemo? Desktop for sure, but windowed also (I think)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) All Mint Cinnamon
 * Graphics hardware *and* driver used: not relevant
 * 32 or 64 bit: 64
 ```
First of all I really apologize for my English and for the lenght of the post, but I want to make those two issue clearer that I can. 

**Issue**
So I must say there is two Issue connected and a feature request...
"First Issue":
When I make (from nemo, any version I think) a multiple folder selection, I can simply and correctly change the colour of the selected folders, choosing it via the appropriate menu voice (rmb ecc) and this is ok BUT when I install an upgraded distribution in a different partition (say for instance I install the new Mint 19 Cinnamon edition in a new partition), the Nemo of the new version (Mint 19 in this case) DO NOT SEE the changed colours of those folder (EVER in a disk different form the system disk) so they appears all green. And I must do the work of colouring them from zero.

"Second  Issue": (all nemo versions, all mint versions ecc)
I make large use of the possibility to change the icon of the folders (NOT system disk, my archives), and I am forced to do so one by one, selecting the folder with rmb, selecting "properties", clicking in the green folder and then selecting the icon of my choice, made by me. I use 3 or 4 of them, all made by me, for personal use. So, here it is the second "Issue": I've done this with Mint 18.3, and he still see those folders in that way (I speech of **_Hundreds_** of them personalized one at once) but when I enter the Nemo version of Mint 19 partition all I see is hundreds of green folders, all the same (beautiful, if you want) green color.... (not, it's not the system disk). 

And There goes the "**Feature Reques**t": there is **_a n y_** way to make Nemo in mint 19 see the same customizations that I've made in mint 18.3 without re-do the work changing them (hundreds) one by one? Can I copy same hidden file from "old" nemo to the new one, for instance? Or there is a magical extension that can do it ? Because,My God, in multiple selection of a group of folder I normally can't change the icon of the group of selected folders in 1 smart move (the green icon in the properties menu is'nt even selectable) and an possible feature like this one could obviously speed up the work If I am coerced at redo the customizations of the folders (that for me is essential) at any new installation of a new version of the system.

**Expected behaviour**
1 - Possible multiple selection of folders in nemo with the contextual possibility to change the icon fo the entire group of folders.
2 - A trick of some sort to copy from an "old" nemo to a new one the way he see the folders customizations of whatever disk (system, non system, exernal, quantic or even archive disks exinsting in the past or in the future, hard disk based in the "memory of water" effect or dilitium crystals....).

Thank you so much for read this madness

Sergioz
 

**Other information**

**Comment by mtwebster** [comment]
Hi,

What you're asking about should already be the case, but it depends entirely on how you upgraded your system, unfortunately.  Some background:

All of these customizations are accomplished via gvfs.  Gvfs (gnome virtual file system) is sort of a layer between applications like nemo (and many many others) and your actual disk file system.  It provides the capability of navigating via uris (such as `trash///` or `recent:///`) and making external devices easy to mount and navigate.  It also allows programs to add additional metadata to individual files, such as, in your case, custom icons.

For an example, I've got a folder I've set a custom color and emblem on:
https://www.dropbox.com/s/1gyz96k0ughu3bt/Screenshot%20from%202018-07-28%2010-18-22.png?dl=0

I can view its metadata this way:
```
gvfs-info ./bin

mtwebster:~> gvfs-info ./bin
This tool has been deprecated, use 'gio info' instead.
See 'gio help info' for more info.

display name: bin
edit name: bin
name: bin
type: directory
size:  20480
uri: file:///home/mtwebster/bin
attributes:
  standard::type: 2
  standard::name: bin
  standard::display-name: bin
  standard::edit-name: bin
  standard::copy-name: bin
  standard::icon: folder
  standard::content-type: inode/directory
  standard::fast-content-type: inode/directory
  standard::size: 20480
  standard::allocated-size: 20480
  standard::symbolic-icon: folder-symbolic, folder
  etag::value: 1532647094:560853
  id::file: l2054:7867308
  id::filesystem: l2054
  access::can-read: TRUE
  access::can-write: TRUE
  access::can-execute: TRUE
  access::can-delete: TRUE
  access::can-trash: TRUE
  access::can-rename: TRUE
  time::modified: 1532647094
  time::modified-usec: 560853
  time::access: 1532743781
  time::access-usec: 302235
  time::changed: 1532647094
  time::changed-usec: 560853
  unix::device: 2054
  unix::inode: 7867308
  unix::mode: 16877
  unix::nlink: 159
  unix::uid: 1000
  unix::gid: 1000
  unix::rdev: 0
  unix::block-size: 4096
  unix::blocks: 40
  owner::user: mtwebster
  owner::user-real: Michael Webster
  owner::group: mtwebster
  metadata::custom-icon: file:///usr/share/icons/Mint-Y-Aqua/places/48/folder.png
  metadata::emblems: [emblem-favorite]
  metadata::nemo-default-view: OAFIID:Nemo_File_Manager_List_View
  metadata::nemo-icon-view-auto-layout: true
  metadata::nemo-icon-view-tighter-layout: false
  metadata::nemo-list-view-sort-column: name
  metadata::nemo-list-view-sort-reversed: false
  metadata::nemo-list-view-zoom-level: 1
```

As you see at the bottom of this output, there's a bunch of metadata:: entries, one for custom icon, another for emblems.  Nemo looks at this metadata and responds accordingly when displaying the file.

Now, a couple things that would prevent this from working:
- The custom icon or emblem does not exist on the system anymore.  In this case, a default behavior is applied (as if there had never been any custom metadata applied to the file)
- The gvfs database is lost or reset - it's stored in `~/.local/share/gvfs-metadata` on a *per user basis*

For the first problem, missing icons, this is possible if the theme you originally set a custom folder color on no longer exists, or the icon you selected from properties no longer exists.  Moving from Mint 18 to Mint 19 this is more of a potential problem than one might think - with that move, the way icons and themes are handled changed *drastically* (not by us, but by the toolkit - Gtk - that does all the work,) and as a result we had to do a great deal of work on our standard icon themes - Mint-X and Mint-Y.  I'm not entirely certain, but while the icon names may exist still, they might be .svg files instead of .png now, or they may exist in a slightly different directory structure in `/usr/share/icons/*`  In this case, there's really no option but to re-do the work, unfortunately.

The second problem can occur depending on how you migrated to Mint 19.  For instance, when I first setup my machines, I always provide a separate partition for my /home directory.  This way, when I install from a new iso, this folder is left unchanged.  I don't need to back up my data.  I just need to make sure I use the exact same user name during installation (I'm the only user here so it's not an issue.)  Thus, everything in my home folder is unchanged - including files in `~/.local/share/gvfs-metadata`.  So in my case, I didn't lose any folder icon customizations when I upgraded - it looks exactly the same as before my upgrade.

On the other hand, if I just back up my obvious personal folders, like Documents, Videos, Pictures, etc.. and restore them to a new install, then I will have lost that metadata.  *The metadata is tied to to my `.local/share/gvfs-metadata` folder, not the individual files that metadata is applied to.*  Think of it as a database where a file is looked up, and specific info for that file is applied.  The magic is that to programs like Nemo, it simply *appears* like all of this extra metadata is attached directly to a file.

As for fixing your issue, there's not much you can do for now except re-do the work.  The folder-color selector in the context menu already supports multiple selection.  The custom icon method thru the Properties window does not.  I can have a look and see if this can be made possible.

There is a `gvfs-set-attribute` utility that can be used to apply metadata from the command line.  If you're at all handy with scripting, this might be useful for your problem, with lots of files to fix.

Sorry for the long winded response to your long-winded problem - hopefully this helps in the future for you during upgrades.

**Comment by sergiozar** [comment]
Thank you so much for your detailed reply!!
Now I have something to try or, in the worst case, I'll redo the work  **_b u t_** now, thanks to You, I **_understand what is the problem_**, this is so wonderful to me, and, even if I've not the time to become  a coder, for this little magic that You've done my mind and I really really appreciate this replay.
Have a nice weekend
Sergioz :-)

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
