### ISSUE TITLE
Nemo ignrores view settings

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/nemo#1925]
```
 * Cinnamon version 3.8.8, Nemo 3.8.5
 * Distribution - Mint 19 Cinnamon 64bit
 * Graphics hardware *and* driver used: Intel Corporation HD Graphics 630
 * 64 bit
  ```

**Issue**
In Nemo settings, list view sorted according to names was selected.
However, when Nemo ist started by the menu shortcut "places->Downloads"
this setting is ignored and list view ist sorted according to dates.

**Steps to reproduce**
Nemo settings as described
(of course, individual folder settings are disabled i.e. all folder should open as set).
Start Nemo by the menu shortcut places->Downloads.

**Expected behaviour**
Nemo should always respect its settings.

**Other information**
This was already reported on Github "Linuxmint/Cinnamon" (#7749), but it was closed because it should be reported here.

**Comment by xenopeek** [comment]
Downloads and Trash are special cases: to make it easier to find the most recently downloaded / deleted files, the default sort for both is reversed date — changing the default sort in preferences doesn't affect these two. That's by design as intended. But you can click the Name column header in either to sort on Name and that preference is remembered.
