### ISSUE TITLE
Dragging folder to side bar loses custom icon display, Mint 19

### ISSUE THREAD

**Issue by ChooChooAl** [linuxmint/nemo#1933]
```
 * Nemo version (nemo --version) 3.8.5
 * Is issue with desktop or windowed nemo? Windowed Nemo
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)  Mint 19 Cinnamon 64 bit
 * Graphics hardware *and* driver used VirtualBox Linux Host

**Issue**
Dragging a folder, that has a custom icon, to the side bar does not maintain that custom icon.

**Steps to reproduce**
Make any folder.   Right click the folder and go to properties, click the folder icon and find another PNG icon for a custom icon.   I've used one from my own personal folders.   In this case it was the google 'grive' folder that was create to make the Grive2 software work.   
Once the folder shows in Nemo with your custom icon, now drag that folder to the side bar, lets say just below the Downloads folder.    Nemo creates the link there but it does not maintain the custom icon, but rather a generic folder icon that changes depending on the icon theme used.

**Expected behaviour**
The folder icon in the side bar should be identical to the one you customized (that shows okay in the right hand pane of Nemo).

**Other information**
This works in 18.3 nemo 3.6.5 and did in 17.
![nemo_icons_in_sidebar](https://user-images.githubusercontent.com/26556059/44957167-fdbdb680-ae9c-11e8-8934-4fff9cd984e8.png)  Mint 19.
![nemo grive icon in 18 3](https://user-images.githubusercontent.com/26556059/44957179-2cd42800-ae9d-11e8-8137-0110964f1e23.png) Mint 18.3

**Comment by ChooChooAl** [comment]
Edit:  I also tried going through the bookmarks menu item to add the folder.   It does the same thing and does not retain the custom icon.

**Comment by mtwebster** [comment]
This is intentional, as the sidebar is now restricted to symbolic icons, which at this time are determined by the specific bookmark location.

**Comment by stefan123t** [comment]
@mtwebster, thanks for all your great work. However it is the same here since upgrade to linux mint 19.1/2 tara/tina.
nemo 4.2.3 on Linux Mint 19.2 (Cinnamon) shows no emblems / custom coloring of the stock icons in the left pane bookmarks section or the bookmarks pull-down menu anymore.
I suspect the intention here has been to leave customized icons, emblems and colours out of the bookmarks, as there were several issues (in numeric order #177, #747, #1035, #1071) filed against the icon cache not getting updated initially or sometimes.
Can you comment on whether this functionality would be coming back someday, as I relied on coloring of folders for quick bookmark identification ?

**Comment by ChooChooAl** [comment]
Edit my original complaint.   
I said it fails in Mint 19.x cinnamon but worked in 18.3 cinnamon.   It does not always work in 18.3
In 18.3 it works if you click on the bookmarked folder in the sidebar and the icon may stay that way for a while, even opening and closing Nemo.   But sometime down the line it resets to the generic icon.   
So 18.3 had the bug and I understand that 19.x changed the performance to be just generic icons.   
I don't like the generic icons and would like it back, but I leave that up to the management.   
Having said this, I still don't think this issue should be closed.
