### ISSUE TITLE
Cut and paste from trash performs restore instead of move

### ISSUE THREAD

**Issue by ThorStrikesAgain** [linuxmint/nemo#1935]
Linxux mint 19 Tara
Cinnamon 3.8.8
Nemo 3.8.5

**Issue**
Cutting from trash and pasting in a directory does not move to the directory. The file is restored to its original location no matter where you perform the paste operation. This issue has previously been closed because this is supposedly the expected behavior of `gvfs-trash` (ref https://github.com/linuxmint/nemo/issues/1175)

This doesn't make any sense and is **EXTREMELY COUNTER-INTUITIVE**. Casual users will **lose their file(s)**. No matter how `gvfs-trash` works, the files MUST be copied back into the directory where the paste command has been executed.

**Steps to reproduce**
- Delete a file
- Open trash
- Select the file
- Cut
- Open some random directory
- Paste
=> File disappears from trash and is not copied into the expected directory

**Expected behaviour**
The file(s) must be moved to the directory where paste is performed.

Temporary suggestion: If this is too complex to implement, cut and paste from trash must be disabled.

**Comment by CottonEaster** [comment]
Hasn't this been fixed?

**Comment by schaetzc** [comment]
No, this hasn't been fixed. I'm using nemo 4.2.0 and files are still restored to their original location.

There are multiple issues on this case, but they often get closed. Some examples:
https://github.com/linuxmint/nemo/issues/1929
https://github.com/linuxmint/nemo/issues/1927
https://github.com/linuxmint/nemo/issues/1814

I would be really happy to see OP's expected behavior in nemo.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/0599ae2839263db660c793dd53f9ed70abb9258d
