### ISSUE TITLE
Nemo action "Mount Archive" does not work for Arch-based distros

### ISSUE THREAD

**Issue by alexnch** [linuxmint/nemo#1942]
```
 * Nemo version: 3.8.5
 * Distribution: Manjaro
 * 64 bit
 ```

**Issue**
File action "Mount Archive" has no effect in Arch-based distros.
This is caused by `gvfsd-archive`'s absolute path being located in `/usr/lib/gvfsd-archive` instead of `/usr/lib/gvfs/gvfsd-archive`.

**Steps to reproduce**
Open context menu by right clicking on any archive file inside Nemo folder view and choose "Mount Archive" action.

**Expected behaviour**
Archive should be mounted.

**Workaround**
I've created a script file with the path `/usr/lib/gvfs/gvfsd-archive` and the following contents:
```
#!/bin/bash

/usr/lib/gvfsd-archive $@
```

**Other information**
If there is no solution to this problem from within Nemo project, feel free to discard this issue. Perphaps, the workaround should be added to AUR then.

**Comment by mtwebster** [comment]
The action shouldn't have been showing in the menu in the first place if it couldn't find that file.  I've fixed that bug here: 

https://github.com/linuxmint/nemo/commit/b6343036f383f3a5e948d1f995a5e0247cc8e853

As to the specific issue here, I can't say I agree with those files being located in /usr/lib, being that they're executables (though we've broken plenty of filesystem rules ourselves) - I would suggest that this is something the Arch maintainer might handle - changing the dependency and exec lines.

This is a difficult thing to handle on our end - I started implementing OR dependencies for actions (allowing `/usr/lib/gvfsd-archive | /usr/lib/gvfs/gvfsd-archive` with either one satisfying the requirement) but this effort would need to be duplicated for the exec line as well, in a more complicated manner.  I just don't think this problem warrants that much increase in complexity.

Most things this is intended for would be located in /usr/bin or somewhere else in the path, executables located in non-path locations are sort of outliers I think.

**Comment by alexnch** [comment]
Thank you for taking the time to review the issue and leaving a reply.

I was suspecting that this is a distribution-specific problem and diverting focus from the home distro in such a way would not be acceptable. Similar thing happened for Cinnamon's remove application feature, which [had to be re-implemented](https://github.com/rapgenic/cinnamon-remove-application) for Arch and added to AUR as optional package.
