### ISSUE TITLE
Assign two special characters to allow sorting items before and after all sorted names.

### ISSUE THREAD

**Issue by ajhcasual** [linuxmint/nemo#1967]
This is a feature request.

As I described at https://forums.linuxmint.com/viewtopic.php?f=29&t=277342, Nemo currently will sort any file/folder name beginning with a '#' last, when it is set to sort "By Name."  All other symbols that I've tried on a US keyboard are ignored when they are the first character -- Nemo skips those and uses the first occurrence of an alphanumeric character in the name and sorts by that character instead.

I am asking that the '#' continue to have the effect it currently has, even if this was not originally intended.

Further, I would like to see a reasonable symbol chosen to cause files/folders to be sorted before all others, which is to say, it will have the opposite effect of '#' when it is the first character in a file/folder name.  I have no idea what would make the most sense, but something over the number keys on a US keyboard could work.

- '^' would be my first choice, based on it's use in regular expressions.
- '%' would be my second choice, even though that would be a reversal of the meaning as it applies to parameter expansion.  (removes the suffix pattern rather than the prefix pattern)
-'@' would be my third and last choice.  The other candidate characters on the number keys - '!$&*()' have some meaning to the shell so would be annoying to a user who uses the command line interface as well as Nemo.

**Comment by xenopeek** [comment]
Nemo converts names to collation keys (based on your locale) before sorting. This allows for example for natural number sorting e.g., so that "42towels" is sorted before "1024towels". 

Downside comparing collation keys is that some are accustomed to prefixing filenames with some special character to make them sort at the top of the list. That may not give expected outcome. You can instead achieve this in Nemo by pinning a file (from the context menu or the Edit menu select Pin, or press Shift+Ctrl+D) which keeps it at the top of the list.

Files starting with a '.' or '#' are considered special and are always sorted last. Prefixing with '.' makes a file hidden but you can use '#' prefix to make a file sort last.

**Comment by MostHated** [comment]
Aside from pinning, is there no way to make an item logically sort first by name? If not, can there be? I have always used underscore "_" to keep specific files at the top when sorting and would really like to be able to do so with Nemo (or in general, but it seems like that might be a "no-go").

**Comment by MarkJeronimus** [comment]
I have a US locale, and after trying all symbols on my keyboard I found '$' makes a name reliably sort on top. I wonder if anything has changed.

**Comment by mtwebster** [comment]
There are multiple ways to achieve this already. Check out favorites and pinning in Nemo's context menu settings.

**Comment by MarkJeronimus** [comment]
I already use these features, but they are no replacement for reordering directories in Dropbox or a windows share for everyone (Windows users included). '$' conveniently sorts above numbers and letters in ASCII.

**Comment by mbuchichio** [comment]
It's appalling that a stupid simple 'feature' like symbol sorting that has existed forever in other platforms (windows, mac and so on) is not possible on linux. Come on.

**Comment by trozman** [comment]
Agree here. My folder structure is 30 years old and all the systems I use(d) (windows, gdocs, even synology file explorer) put sort _folders on top, not somewhere in between. 
I'm not renaming my whole tree of folders.
Is it possible to make a setting for NEMO to sort special chars on top?

**Comment by Jeremy7701** [comment]
See https://www.unicode.org/reports/tr10/#Introduction for an explanation of misconceptions.
Extract:-
"Collation is not aligned with character sets or repertoires of characters.
 Swedish and German share most of the same characters, for example, but have very different sorting orders".

I find that a prefix of 0- (zero, hyphen) sorts first (in the UK).

**Comment by trozman** [comment]
Thanks, interesting read, but TL;DR. Not because I am willing-fully ignorant in this case, but because for me it is an unnecessary mental burden to understand a complex thing (collation), where a simple solution that worked for ages is at hand: character based sort (or, sort special chars at the top). That's it.
I have no intention to rename hundreds of folders and files. 
I read many other commenters that have a similar issue: through the years, many people formed a habit to add an underscore to a folder name to have it sorted on top.
I love Mint and I'm quite happy with it. But the most of my computer use is with folders and files. This strange sorting system is quite a big friction point for me.
Unfortunately I'm not a developer and can't contribute with the code. But I can contribute with UX suggestions.
