### ISSUE TITLE
It seems excessively hard to copy items into the root of a folder

### ISSUE THREAD

**Issue by CottonEaster** [linuxmint/nemo#1986]
```
 * Nemo version (nemo --version): 3.8.6
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...): Mint 19
 * Graphics hardware *and* driver used: NA
 * 32 or 64 bit: 64
 ```

**Issue**

Imagine was has item S visible in a nemo window, and folder D open - showing its contents - in another nemo window. Copying S to D is hard. If one drags S to D, it is all-too-easy to drag S erroneously into a subfolder of D. Nor does the sidebar allow one to locate where one is within the folder tree. If I make no mistake, this is a serious usability problem. Perhaps one is meant to drag S to an empty part of the display of D's contents. Such a part is not always visible, though.

**Comment by mtwebster** [comment]
I can't agree - it's quite easy to tell when something is going into the view's location or going into a folder inside that view.  If you hover an icon while dragging, the item you're hovering over changes appearance and becomes highlighted (the folder appears to 'open')

In this list view, there really is no way to drag into the view's location except by scrolling down to where there are files and dragging onto a file, instead of a folder.  This is not a new situation or behavior.

The sidebar brackets items when you're over them to show you'll be dragging an item into them.  If your item being dragged is a folder, you can also drag *in between* existing items to add a new bookmark.  This shows as a single line between items.

Are you sure you're not just using a broken gtk theme or one with poor or missing nemo support?

**Comment by CottonEaster** [comment]
> Are you sure you're not just using a broken gtk theme or one with poor or missing nemo support?

I think that rather I am encountering this:

> In this list view, there really is no way to drag into the view's location except by scrolling down to where there are files and dragging onto a file, instead of a folder. This is not a new situation or behavior.

That may not be new but it is I believe considerably less than ideal.

**Comment by metafarion** [comment]
I'm with ghost on this one.  You should be able to drag and drop an item into a directory in list view that contains only directories.  The fact that it's impossible to locate files or whitespace to drop your item on is a problem.  Windows accomplishes this by allowing you to drop items on to the list header row, i.e. Name, Type, Size, Modified, etc.
