### ISSUE TITLE
`Gtk-WARNING` and `Gtk-Message` when opening compression dialog

### ISSUE THREAD

**Issue by FriedrichFroebel** [linuxmint/nemo#1989]
```
 * Nemo version 3.8.6
 * Linux Mint 19 Cinnamon
 * 64 bit
 ```

**Issue**

When compressing a folder, the following output is written to the terminal:

```
(nemo:9846): Gtk-WARNING **: 11:00:03.697: Drawing a gadget with negative dimensions. Did you forget to allocate a size? (node menuitem owner NemoWidgetMenuItem)
Gtk-Message: 11:00:04.221: GtkDialog mapped without a transient parent. This is discouraged.
```

The first message gets repeated over 30 times.

**Steps to reproduce**

* `cd` into a directory.
* `xdg-open .`
* Right click on a folder and choose "Compress".

**Expected behaviour**

No warnings or messages from Gtk.

**Other information**

`pkg-config --modversion gtk+-3.0` returns `3.22.30`.

**Comment by mtwebster** [comment]
The warning should be fixed by 11e6a9b90c5bebbcd00, assuming you have the 'Folder Color Switcher' extension enabled.

The message about a GtkDialog is typical and harmless, when launching the file-roller program it opens a window.  Gtk would like you to tell the window what its parent is (this is for window-manager purposes mainly), but as these are separate processes (and packages, for that matter - nemo and file-roller) this isn't really possible.

This behavior didn't always generate a message, only in more recent gtk versions did they decide to frown upon it.  You can bring it up with them why this is.
