### ISSUE TITLE
How to get get back the bookmarks section in the sidebar?

### ISSUE THREAD

**Issue by Pallieguy** [linuxmint/nemo#1996]
```
 * Nemo version (nemo --version)
1.8.4
 * Is issue with desktop or windowed nemo?
desktop (I think, I had replaced the default Nautilus with it and open via Places on taskbar)
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
Ubuntu 14.04
 * Graphics hardware *and* driver used
MOBO built in graphics card and nvidia-current (192, I think)
 * 32 or 64 bit
64
 ```

**Issue**
When I go Bookmarks->Add Bookmark it's only adding it to "My Computer", the "Bookmarks" section does not exist and won't get created.

**Steps to reproduce**
Add a bookmark

**Expected behaviour**
New bookmarks should go under the Bookmarks section, creating said section if there is not already one

**Other information**

**Comment by wyattbiker** [comment]
Did you click the Show Places button in the button left corner of Nemo?

**Comment by xenopeek** [comment]
You've hopefully long since solved this but for any future readers: in Nemo edit bookmarks drag the bookmark below the horizontal divider line to make the Bookmarks category appear. If all bookmarks are placed above the horizontal divider line the Bookmarks category isn't shown (as it's empty).

![image](https://user-images.githubusercontent.com/21159972/85941500-c5b21e00-b923-11ea-8b73-c74016ecfe52.png)
