### ISSUE TITLE
Nemo ignores Custom settings in Root mode via (Nemo submenu "Open as Root")

### ISSUE THREAD

**Issue by antrrax** [linuxmint/nemo#2008]
```
 * Nemo version (nemo --4.0.6)
 * Is issue with windowed nemo
 * Distribution - (Mint 19.1) Cinnamon
 * Cinnamon
 * 64 bit
* pt-BR
 ```
Custom icons
https://www.mediafire.com/file/s3460ef1nojxtg6/Windows-10-master.zip/file

The problem with this topic has been partially fixed.
https://github.com/linuxmint/mint-19.1-beta/issues/43

If you open the nemo in root mode through the terminal, everything is fine, the icons and themes are right.

The problem is if I open the nemo, right-clicking on an empty space, it will open a submenu. Click on "Open as root". Then Nemo opens with the interface Gnome icons and themes.

**Steps to reproduce**
1 Open Nemo
2 right-clicking on an empty space
3 click "Open as Root"

**Expected behaviour**
Open with my user icons e theme

**Other information**

<a href="https://ibb.co/r4QjjkM"><img src="https://i.ibb.co/WgHhhnF/Captura-de-tela-de-2018-12-20-18-22-37.png" alt="Captura-de-tela-de-2018-12-20-18-22-37" border="0"></a>

**Comment by antrrax** [comment]
Previously I was using the 19.1 beta version updated to final 19.1.

Today I formatted the HD and installed the version: 19.1 final.

With this new installation the translation problem has been corrected, but the icons and custom themes that are in the user folder were not loaded in root mode, nor did the custom settings that I did in the nemo in user mode for root mode were loaded. (this in the Nemo context menu "Open as Root")

-----

Remembering that when I open nemo via terminal in root mode (#sudo nemo), both icons and themes, such as custom settings of my user are also loaded in root mode

**Comment by xenopeek** [comment]
Retested on Linux Mint 20 Cinnamon and I couldn't reproduce it. What I tried:

1. Open Nemo
2. Opened a directory as root from Nemo
3. Closed both
4. Set a new icons theme through system settings
5. Repeated step 1 and 2, they both are using the selected icons theme

![image](https://user-images.githubusercontent.com/21159972/85946205-04a39c00-b943-11ea-939b-ab23fade9d02.png)

**Comment by antrrax** [comment]
But you only tested with the system's native icons and themes.

Do the same test using custom icons and themes that the user placed in the folders below and see how it behaves:

/home/MY_USER/.icons/CUSTOM_iCONS
/home/MY_USER/.themes/CUSTOM_THEME

**Comment by xenopeek** [comment]
When you use the `.icons` directory in _your_ home directory, other users won't be able to use the same icons theme. So when you run Nemo as root—or any other program as root—it won't use that icons theme because you didn't make the icons theme also available for that user.

You have various options to make the icons theme also available to the root user, all of which you need to do as root:

- Create the `.icons` directory in root's home directory (`/root`) and copy the same icons theme there as you have in that directory in your home directory;
- Alternatively make it available to all users by creating the directory `/usr/local/share/icons/` and copy the icons theme there, then you don't need to keep it in your home directory.

If I try either and configure to use the Windows-10-master theme, that works and Nemo uses the same icons theme also when run as root—because root now also has access to the theme.

**Comment by smurphos** [comment]
Another option is to create symlinks in the system area to themes installed in your home directory. 

e.g. - 

`sudo mkdir -p /usr/local/share/themes && sudo ln -s ~/.themes/* /usr/local/share/themes/`
`sudo mkdir -p /usr/local/share/icons  && sudo ln -s ~/.icons/* /usr/local/share/icons/`
