### ISSUE TITLE
Can not completely disable desktop icon auto-arrange

### ISSUE THREAD

**Issue by mikehaertl** [linuxmint/nemo#2015]
```
 * Nemo version: 4.0.6
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution: Mint 19.1 Tessa
 * Graphics hardware *and* driver used:
Graphics:  Device-1: Intel Xeon E3-1200 v3/4th Gen Core Processor Integrated Graphics driver: i915 v: kernel 
           Display: x11 server: X.Org 1.19.6 driver: modesetting unloaded: fbdev,vesa resolution: 1920x1200~60Hz 
           OpenGL: renderer: Mesa DRI Intel Haswell Desktop v: 4.5 Mesa 18.0.5
 * 32 or 64 bit: 64 bit
 ```

**Issue**

I have turned off **Auto-arrange** in the desktop settings. Still the icons get auto-arranged

*  after rebooting, or,
*  whenever the **Direction** setting is changed

![mint_settings_monitor_layout](https://user-images.githubusercontent.com/675062/50535901-f8246480-0b4e-11e9-9bdd-3018f17949ae.png)

**Steps to reproduce**

* Right-click desktop -> Customize
* Set **Auto-arrange** to **off**
* Put some icons somewhere on the desktop
* Either Reboot or change the **Direction**

**Expected behaviour**

The icons should stay on the desktop where you put them.

Instead all icons are auto-arranged vertically or horizontally.

**Other information**

There was another issue (#1819) where the problem seems to have went away by itself. But I see this problem for some time now. I think it started with some Mint 18.x release.

**Comment by zpangwin** [comment]
This could possibly be related to some obscure / unknown setting. I say this because I have Mint 19.1 installed on 2 different computers and see the issue on one but not on the other.

On my dev box, I see the issue described above (Auto-arrange is off but all of my icons get moved and sorted anyway).

On my gaming rig, I do not see the issue (yet) but this install is newer and I have not set everything up the way I like it yet (had to get some degree of confidence in Steam Play/Proton before converting my old Wintendo to a Linux box).

Both boxes are using AMD CPU's. The dev box has an AMD GPU and the gaming rig has an NVidia.  I think the resolutions might also be different. Gaming rig is at 1920x1080. Will try to check dev one later and report back.

I have also messed with a LOT of settings and installed a fair number of packages on the dev box. Haven't done too much on the gaming rig so far (Steam, Sublime Text, Waterfox, PCloud, and a few basics).

**Comment by humanplayer2** [comment]
For what it's worth, I also see this on Ubuntu 19.04. I have disabled the grid (to get the "Resize icon" option) and disabled "Keep aligned", but still loose the layout on boot.

**Comment by mikehaertl** [comment]
For me the issue is gone. There are 2 things I've changed:

* Upgraded to 19.2 Tina
* Fixed a permission problem in `~/.local`. 

The latter sounds like the most likely reason for the issue. I don't know why but some files e.g. in `.local/share/gvfs-metadata/` belonged to `root`. The fix was easy:

```
sudo chown -Rc $USER:$USER $HOME
```
