### ISSUE TITLE
[Feature Request] Built-in support for TMSU tagging system

### ISSUE THREAD

**Issue by lbrunkho** [linuxmint/nemo#2077]
This is more of a long-term feature bc it would require a lot of code changes to implement. This type of feature has been requested before in issues #436 and #1390 but I have found a cli utility that could ease the process significantly. TMSU (aka Tag My Shit Up.) can be found [here](https://github.com/oniony/TMSU). This utility makes a searchable database that can be indexed and also mounts and creates a virtual file system. This works quite well, but it lacks a GUI and file manager integration. Also integrating this into a file manager would allow it to track files when they get moved or deleted.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by DIMFLIX** [comment]
@lbrunkho  If the problem is still relevant for you, I have come up with a small solution. The [nemo-tags plugin](https://github.com/meowrch/nemo-tags) adds full tag support.

Unfortunately, I was unable to implement a drag-and-drop system or create a more attractive interface due to Nemo's limitations. But overall, I think it turned out to be quite usable and even convenient.

I would appreciate a star on GitHub repository as support.

<img width="1086" height="658" alt="Image" src="https://github.com/user-attachments/assets/0f7509ca-5531-4810-b1df-b3ea19be0a72" />
