### ISSUE TITLE
Nemo should focus on downloaded file in Chrome, when clicking on show in folder in Chrome

### ISSUE THREAD

**Issue by wyattbiker** [linuxmint/nemo#2080]
```nemo 4.0.6
Cinnamon 4.0.9
 ```

**Issue**
Does not focus/highlight downloaded Chrome file in Nemo. This means extra steps for user must scroll through the directory to look for the file.

**Steps to reproduce**
- Download a file with Chrome
- Right Click on downloaded file from Chrome status bar
- Click Show In Folder
- Nemo opens up to correct folder but file is not highlighted/focused.  

**Expected behaviour**
Highlight/focus to the downloaded file.

**Comment by xenopeek** [comment]
This appears to have been implemented. I retested on Linux Mint 20 Cinnamon, installed Google Chrome, randomly downloaded a file and afterwards created 100 newer files in the Downloads directory, then went back to Google Chrome and selected "Show in folder" for the previously downloaded file. Nemo opened up with the view scrolled to that file and that file highlighted (it is last in the list because Nemo sorts Downloads directory most recent files first):

![image](https://user-images.githubusercontent.com/21159972/85955355-4bfb4e00-b97e-11ea-9e3e-5e500b0c5f7e.png)
