### ISSUE TITLE
sort order

### ISSUE THREAD

**Issue by damian101** [linuxmint/nemo#2128]
I always use underscores and sometimes exclamation marks to make specific folders appear at the top of the list when sorting by name. That worked in the Explorer on Microsoft Windows and works with Dolphin and the Deepin File Manager on Linux. But in most other file managers on Linux, including Nemo, this doesn't work, because they sort files in a different way. Most Nautilus-based file managers just take the "`ls`-sort-order" and apply natural sorting to it.
I would like to see a sort order similar to what is used in Dolphin and Deepin File Manager, as that is what people are expecting and Windows users are used to. 
The "`ls`-sort-order" also doesn't make much sense normally and might change with distribution and system language.

**Comment by Meru** [comment]
https://github.com/linuxmint/nemo/issues/2085

**Comment by xenopeek** [comment]
Nemo converts names to collation keys before sorting, using functions from https://gitlab.gnome.org/GNOME/glib/-/blob/master/glib/gunicollate.c. Among other reasons the purpose of this is natural number sorting e.g., so that "42towels" is sorted before "1024towels". Downside of this as you've noted is that you can't easily make a directory sort at the the top of the list by prefixing it with some character. As noted you can achieve that instead by pinning it (from the context menu or the Edit menu select Pin, or press Shift+Ctrl+D). 

There is a more detailed discussion in #2135 about Nemo's sorting and possible additional options for that.
