### ISSUE TITLE
Scroll bar obscures last item in list.

### ISSUE THREAD

**Issue by jay-wilkinson** [linuxmint/nemo#2154]
```
 * Nemo version (nemo 4.0.6)
 * Is issue with desktop or windowed nemo? windowed
 * Distribution - (Mint 19.1 Cinnamon)
 * Graphics hardware *and* driver used
> Graphics:
>   Device-1: AMD Curacao PRO [Radeon R7 370 / R9 270/370 OEM] driver: radeon 
>   v: kernel 
>   Display: x11 server: X.Org 1.20.4 driver: ati,radeon 
>   unloaded: fbdev,modesetting,vesa resolution: 1920x1080~60Hz 
>   OpenGL: renderer: AMD PITCAIRN (DRM 2.50.0 4.15.0-47-generic LLVM 8.0.0) 
>   v: 4.5 Mesa 19.0.2
 * 32 or 64 bit
64 bit
 ```

**Issue**

Scroll bar obscures last item in list.

**Steps to reproduce**

Open a folder with enough items to fill the window. Mouse to last item. Unless you sneak up on it very carefully, the scroll bar will expand and cover the last item. (See attached screen shot) 

**Expected behaviour**

All items in window to be unobscured and easily usable.

**Other information**

This happens on other computers with very different video hardware.

![nemo2](https://user-images.githubusercontent.com/49291581/58766836-20bee900-8549-11e9-8aa7-a10121691b3f.png)

**Comment by mtwebster** [comment]
Try turning overlay scrollbars off:

![overlay](https://user-images.githubusercontent.com/262776/58769266-5d9fd580-8573-11e9-8f78-034658fa7cfd.png)

This will use the traditional 'always there' scrollbars instead, and avoid the issue.

As for the issue itself, that's really just the nature of overlay scrolling - I'm not a fan, which is why I usually have them turned off.

**Comment by jay-wilkinson** [comment]
They should turn that off by default if they can't fix it.

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/e8c8b1099112f3d157849c7a1c303110ea144583
