### ISSUE TITLE
Scrollbar in the sidebar overlaps with the eject media button

### ISSUE THREAD

**Issue by morfikov** [linuxmint/nemo#2234]
It's really hard to unmount disks, when the sidebar's scrollbar overlaps with the eject button

![out](https://user-images.githubusercontent.com/3797768/67455027-8c0a7400-f62c-11e9-8318-66955d9a54e9.gif)

```
$ nemo --version
nemo 4.2.3

$ uname -a
Linux morfikownia 5.3.7-amd64 #4 SMP PREEMPT Tue Oct 22 08:26:38 CEST 2019 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux bullseye/sid
Release:        unstable
Codename:       sid
```

**Comment by leigh123linux** [comment]
Try using a theme that supports scrollbar overlay or disable it.

**Comment by morfikov** [comment]
I see. I just disabled the scroll overlay via `GTK_OVERLAY_SCROLLING=0` .

**Comment by Coeur-Noir** [comment]
This issue is still true today, outside of Mint and with any theme.
Here is Ubuntu Budgie 23.04 / vimix-dark-ruby gtk theme : 
![nemo_scrollbar_on_mount_icon](https://github.com/linuxmint/nemo/assets/1895947/fc7374c6-cf80-4016-ba59-2a5481890f13)
Might be enough to « put » the (un)mount icons / buttons a bit further from the right limit of the pane ?
Or to the left of the mount points names ?
