### ISSUE TITLE
(Feature request) "Keep both files" file conflict handling option

### ISSUE THREAD

**Issue by Minabsapi** [linuxmint/nemo#2352]
**Nemo version: 4.2.3**

While I was cleaning and moving some files I discovered there were no handling option to keep both files in Nemo when a file name conflict happened. The only options provided are replacing the file, renaming it manually **everytime**, ignoring (which I wonder the use), or cancel the operation.

Is it possible to add such option, handling the case on every conflict with the "Apply this action for all files" by automatically renaming the file with a pattern such as what can be found with folders: "conflictingfilename (1).txt" ?
It would really make life easier, and I'm really surprised it hasn't been implemented yet

**Comment by www-MKRD-info** [comment]
I WILL PAY $ TO ADD SUCH AUTOMATIC RENAMING, WHICH IS LITERALLY PRESENT ELSEWHERE IN LINUX (FIREFOX DOWNLOADING DUPLICATES, MANUAL DUPLICATION ALTHOUGH I AM NOT IN FAVOR OF "ANOTHER COPY"), AND SAME AS PRESENT IN WINBLOWS.
TO BE CLEAR, I WANT (2), (3), (4), AND NOT "A COPY", "ANOTHER COPY", ETC.
I DO A LOT OF FILE OPERATIONS. THIS WILL IMPROVE MY LIFE.
WHILE WE ARE ON THIS TOPIC, MAYBE ADD AN OPTION INSTEAD OF NUMERIC INCREMENTING TAG, USE A DATE AND/OR TIMESTAMP INSTEAD!!! SAME AS WHAT FREEFILESYNC DOES ON MY SYSTEM.

**Comment by icarter09** [comment]
@www-MKRD-info we appreciate the feedback, but there's no reason be commenting in all caps or adding in extra non-needed information. The team is working hard to implement not only your request, but many others. We welcome any and all pull requests so please feel free to implement the feature request as well. Thanks.

**Comment by www-MKRD-info** [comment]
Changed to the way you like. Wasted tens of seconds, over doing this many, many times times over time, add up in my life. Been waiting for this to be implemented for years. Hence the language.
