### ISSUE TITLE
nemo doesn't handle the INPUT of accented characters for file-/dirnames.

### ISSUE THREAD

**Issue by bjd-pfq** [linuxmint/nemo#2378]
nemo 4.4.2
Linux Mint 19.3 Tricia

I am creating directories from the right-click context menu, and suddenly am highly surprised that nemo doesn't handle the **_input_** of accented characters (like e.g. ä) at all!

(I have these enabled system-wide via AltGraph+character followed by the accent, for instance AltGraph+a followed by "; that works in every application, except nemo)
[note: AltGraph==Right Alt, which is set to the Compose Key in the Keyboard Layout Settings]

Update:
Oddly enough, this works perfectly as it should in nemo-desktop.

**Comment by xenopeek** [comment]
I can't reproduce this with Nemo 4.6.4 on Linux Mint 20 Cinnamon, having also set the compose key to right alt. 

You write it "suddenly" stopped working—do you mean it used to work in Nemo itself instead of only on the desktop, but from some point in time it stopped working altogether in Nemo itself? Does that coincide with any package updates, you can check when upgrades for nemo packages were installed with:
`grep "upgrade.*nemo" /var/log/dpkg.log`

Is there any other system-wide action tied to right alt key that might be interfering?

**Comment by bjd-pfq** [comment]
For me, that is no contest: I am not running Mint 20, and I am not running nemo 4.6.4.  What is the point of having me give a nemo version, when the attempt to replicate is on a newer version, and on top of that on a newer Mint release?  What do you want me to do -- call BUG SOLVED?

There are no other keys or settings interfering. All other applications and editors behave perfectly as they should in this regard (accented characters), only nemo refuses to accept them when I rename a file (via the rename menu option, or via the properties menu option). And it is replicated across system upgrades, kernel upgrades and what not.

I cannot trace back when this started, since I do not very frequently enter accented characters that way. The one thing that stands out is that nemo is singularly the only program refusing thus to accept them. No LC_ settings were changed, even though I did try that approach to make it work again.

**Comment by mtwebster** [comment]
There's no need for that sort of attitude.  4.6 is the latest stable release.  It's perfectly valid to attempt to reproduce the issue against it, since if the bug *is* reproduced, that is the version a fix would be released on.  It's perfectly reasonable to ask you to try it in 4.6 as well.  No one asked you to call the bug 'solved', we're trying to work out causality.

**Comment by bjd-pfq** [comment]
I just wasted 5 minutes of my time, that's why. Asking me to run a Beta is silly. Calling that 'an attitude' sillier even.

**Comment by leigh123linux** [comment]
> I just wasted 5 minutes of my time, that's why. Asking me to run a Beta is silly. Calling that 'an attitude' sillier even.

You are misinformed, mint-20 final is a proper release as of 27/06/20

https://distrowatch.com/?newsid=10953
