### ISSUE TITLE
Remove eject icon when the drive is persistently mounted.

### ISSUE THREAD

**Issue by TheJuiceFR** [linuxmint/nemo#2379]
[Feature request]

I have a drive persistently mounted using fstab, and I'd prefer if the icon to eject the drive wasn't there. 

If the icon were removed, one could still unmount by right clicking the drive, so no functionality is removed.

**Comment by xenopeek** [comment]
What was the mountpoint directory?

**Comment by TheJuiceFR** [comment]
> What was the mountpoint directory?

/media/[My username]/MassStorage, I believe.

**Comment by xenopeek** [comment]
For prestent mounts use a mountpoint other than /media as that mountpoint is for removable media. Hence the eject icon. Try with a mountpoint in a different location, like /MassStorage.

**Comment by smurphos** [comment]
Mmm, /MassStorage probably not a great choice - it's not on Timeshifts' exclusions...

/mnt/MassStorage 

or

/data/MassStorage

are both fine and no eject icon would be displayed.

**Comment by Jeremy7701** [comment]
If you insist on this, I have an empty file called `/home/myuser/.config/nemo/bookmark-metadata` - perhaps it (or a similar file) could hold a list of mount points which shouldn't have an icon shown or otherwise get some special treatment?

Unfortunately, the only standard in mount point names is that there should be a great variation in names.
