### ISSUE TITLE
[Question] rename multiple files.

### ISSUE THREAD

**Issue by VaGNaroK** [linuxmint/nemo#2464]
Would it be possible to have the function inside nemo to rename files in bulk? or some extension?

**Comment by Jeremy7701** [comment]
There is a limited multiple rename "feature".
If you want to rename selected files in a directory and `gprename` suits you, it is possible to run it from nemo.
It needs a helper application, because you need to select a directory in nemo and pass it as a parameter to gprename.

`sudo apt install gprename`
Create a file `/usr/local/bin/gprename-nemo` (which is in your $PATH) containing the following 4 lines:-
`#!/bin/bash`
`function urldecode() { : "${*//+/ }"; echo -e "${_//%/\\x}"; }`
`filePath=$(urldecode "$1")`
`gprename "$(dirname "$filePath")"`
In nemo,  Edit -> Preferences -> Behaviour, scroll down to the bottom and set the Bulk Rename...

![Screenshot from 2020-07-30 20-27-53](https://user-images.githubusercontent.com/52585119/88965988-80c33380-d2a3-11ea-955e-b170ae74f6d9.png)

Selecting more than one file in a directory [2 files are sufficient], right-click for context menu, rename, launches `gprename` for that directory (with no files actually pre-selected).

![Screenshot from 2020-07-30 20-43-30](https://user-images.githubusercontent.com/52585119/88967333-8e79b880-d2a5-11ea-9531-7db5eecd1643.png)

You then select all the files you actually want to process and use the gprename features...
BTW This is taken from some forum - can't give credit to whom it is due...

**Comment by VaGNaroK** [comment]
WOOOWW!! NICE! Thanks dude!

**Comment by SPREEKDOS** [comment]
I would like that feature built-in too
Why it isn't any bulk renamer installed by default with nemo ? and if someone don't like the defualt bulk renamer they could change it in the settings.

**Comment by thom-10** [comment]
It would be a great relive to have an integrated bulk renamer. I hate the need to manually set it up in every fresh install. And whenever I need it it's not there, because I forgot it before.
