### ISSUE TITLE
'Run in terminal' fails when Konsole is the default terminal

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#2468]
```
 * Nemo version (nemo --version) 4.6.4
 * Is issue with desktop or windowed nemo? Both
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 20
 * Graphics hardware *and* driver used: Not relevant
 * 32 or 64 bit: 64
 ```

**Issue**

'Run in terminal' fails - does nothing at all when Konsole is the default terminal. A process is not even spawned, or at least not one that persists.

**Steps to reproduce**

1. `sudo apt install Konsole`
2. Nemo: have Nemo set to ask what to do with executables; locate a bash script; run it; choose 'run in terminal'.

**Expected behaviour**

The script should run in a terminal.

**Other information**

- I see the problem on two Mint Cinnamon computers.

- Gnome terminal and XFCE-terminal work alright when launched in the manner at issue.
 
- This might be a Konsole bug. _However_: the file manager PCManFM has no trouble (on Mint Cinnamon) launching the script in a Konsole terminal; compare #2376 (which proposes a workaround for a similar issue but the workaround did not work for me); and I found not report filed against Konsole.

**Comment by mtwebster** [comment]
The default argument for the terminal in this case is -x, which konsole doesn't support.

You can do:
```
gsettings set org.cinnamon.desktop.default-applications.terminal exec-arg "-e"
```
This will fix the issue with konsole.  Gnome-terminal also supports -e, and I may change the default to that (once I figure out why it's been left at -x).

**Comment by LinuxOnTheDesktop** [comment]
Marvellous. Thank you. That fixes the problem. That said, there is still the following, but presumably it is a peculiarity - or feature? - of Konsole. Take this script:

```
#!/usr/bin/env bash

read -r whatever

exit
```
If I run it in the manner at issue, and then press ctrl-c, I see this:

`Warning: Program '/home/nicholas/NJ/scripts/test/t' crashed.`

**Comment by mtwebster** [comment]
That seems to be how konsole handles scripts that don't exit successfully.

Take your script and run it normally:
```
./test-script
```
type some stuff, hit enter, the script ends.  Try:
```
echo $?
```
This prints the 'exit code' of the previous command.  It should print '0', which is pretty universal for success.

Now follow the same steps, but use ctrl-c instead, and when you run the echo command again, you should get 130 (or non-zero, more importantly) - this signifies that the program didn't exit cleanly, which, by using ctrl-c, is the truth.

The return code is useful in scripting to check if some command completed successfully or not.  Konsole doesn't do this if you run the script in a normal fashion.  It seems to do so only when using the -e option.  This is probably to let you know something went wrong before it closes the window, otherwise you'd never know. It's actually helpful behavior I think.

**Comment by LinuxOnTheDesktop** [comment]
You're on the money with all that (and I should have said that I do know something about exit codes). Thank you. I'll close this issue if you like.

**Comment by HanabishiRecca** [comment]
Btw run in terminal also fails for me with Gnome terminal. `-x` and `-e` doesn't work. And there is a message from the terminal:
```
# Option “-x” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.
```
```
# Option “-e” is deprecated and might be removed in a later version of gnome-terminal.
# Use “-- ” to terminate the options and put the command line to execute after it.
```
`--` arg working for me.

**Comment by icarter09** [comment]
PR #2499

**Comment by mtwebster** [comment]
https://github.com/linuxmint/nemo/commit/a2f15e045b5b2d0581bcc10780b3416ea185faa3
