### ISSUE TITLE
Selecting several files and hitting Enter only opens one of them

### ISSUE THREAD

**Issue by teo1978** [linuxmint/nemo#2478]
```
* Nemo version (nemo --version) 4.4.2
 * Is issue with desktop or windowed nemo? Desktop
 * Distribution - Ubuntu 20.04
 * Graphics hardware *and* driver used: Intel Corporation 3rd Gen Core processor Graphics Controller and NVIDIA Corporation GF117M [GeForce 610M/710M/810M/820M / GT 620M/625M/630M/720M] (don't know about the driver since it doesn't show up in System Info)
 * 64 bit
 ```

**Issue**

**Steps to reproduce**

- Open a folder in Nemo
- Select multiple files
- Hit the Enter key

**Expected behaviour**

Should open all the selected files with their default application (whether it's the same for all or not)

**Observed behavior**

Only opens one of the selected files

**Other information**

**Comment by Jeremy7701** [comment]
No fault could be reproduced in nemo 4.6.4 on LMDE4

Selected multiple PDF files; pressing **enter** caused opening multiple copies of `evince` ["Document Viewer"]
Selected 5 text files; pressing **enter** caused opening of a single copy of `xed` ["Text Editor"] - but with 5 appropriate tabs.

**Comment by ferdnyc** [comment]
@Jeremy7701 

I guess one question would be, what happens if you select three text files and two PDF files, then hit <kbd>Enter</kbd>?

It sounds like @teo1978 may be using an application that advertises as supporting multiple URLs/files (`%F` or `%U` in the `Exec=` line of its `.desktop` file), so they all get passed to it, but then it ignores all but the first one.

I just tried something similar in Nemo 4.6.4 on Fedora 32 — I selected two JPGs, a PNG, a GIF, and a ZIP, and then hit <kbd>Enter</kbd>. What I got was:
* A `file-roller` window containing the ZIP file
* A `gthumb` window with all four images open in it.

So, yeah, it seems like Nemo will do exactly the right thing, if apps are configured properly. It's likely a problem with how the default app is configured on your system (in its `.desktop` file) for one of the file types you had selected, @teo1978. (Or maybe a Nemo 4.4.2 defect that's been fixed since.)

**Comment by Jeremy7701** [comment]
O.K I selected:-
2 text files
1 sqlite file
1 tar.gz file
1 zip file
1 deb file
then pressed enter.
I expected **5** Windows to be opened, but unexpectedly, nemo warned me that **4** seperate applications would be opened, if I continued...
**So there is a tiny bug there...**
Pressing enter did indeed open FIVE windows.

**Comment by ferdnyc** [comment]
Hey, man, counting is _hard_. You've gotta figure out what digit to start from, then keep them all in the right order, be careful not to skip any...

**Comment by mtwebster** [comment]
It said 4 applications, not 4 windows. The zip and tar.gz files are both opened by the same application (usually file-roller).

I'm just explaining what's happening here.  Nemo doesn't think there are 5 applications because there technically aren't - file-roller opens additional windows for multiple files, *but they are all part of the same instance of file-roller*.

2 text files - editor
1 sqlite file - ??
2 archive files - fileroller
1 deb file - gdebi

It's not possible to know how each app will behave, or handle multiple arguments (as mentioned previously), so nemo can't predict how many windows an application might open, it's simply passing file names along to the appropriate handler.
