### ISSUE TITLE
File lookup should not need triple click to open a file.

### ISSUE THREAD

**Issue by silocoder** [linuxmint/nemo#2490]
Nemo 4.6.4
Linuxmint 20

Let's say you start typing in a panel to locate  a file in that directory. In order to open that or any file I have to triple click on it.  Why is that? Confusing and extra clicks. The correct behavior should be just double click. 

This is related to issue #2475 where  you need to refocus on the panel before you can double click on a file.

**Comment by SomeTroglodyte** [comment]
Seems intentional, I have noticed this years ago. Typing to search enters a 'mode' which allows to add to the 'search string', and a click will be consumed to exit that mode. You'll also notice scrolling with mouse wheel is crippled in that mode. I got into the habit to immediately hit ESC when using the feature.

**Comment by Jeremy7701** [comment]
Tried this in using the search key in Nemo 4.6.5 on a **single** pane - double-click on the result opens the file.
In a **double** pane, if you search in the 'live' pane, a double-click is sufficient to open a file.
If you want to search in the deselected pane, you would need to make it the active pane _before_ the search.

So this issue is identical to #2475

**Comment by silocoder** [comment]
This is why i decided to look at Dolphin.  It works perfect. No extra keys or clicks.  And at at that point I decided to may as well switch to Kubuntu Plasma to get the full UX. No regrets.

**Comment by icarter09** [comment]
Duplicate issue
