### ISSUE TITLE
Nemo shows deleted files in trash twice because of timeshift

### ISSUE THREAD

**Issue by oldtomdevel** [linuxmint/nemo#2523]
* Nemo version 4.6.5
 * LM20 Cinnamon 64bit

**Issue**

Nemo shows a file with two(!) entries in trash when that file has been deleted (i.e. moved to trash) under some circumstances as decribed below.
 
**Steps to reproduce**

My configuration is as follows:

* standard Mint installation on a small SSD
* have another big SSD as my personal drive which is permanently mounted by fstab in ~/.DataSSD
* Timeshift is activated and saves its snapshots on the big SSD i.e. the one which is permanently mounted as personal drive.

From my point of view, this configuration is nothing special.

In the folder "/run/timeshift/backup", Timeshift appearently mounts the drive that is used for the snapshots.
This mounting is done after Timeshift has been started. After boot, the folder /run/timeshift does not exist yet.
When Timeshift is finished i.e. the GUI closed or backup finished, the mounting remains.
Timeshift's mounting means that two paths point to the same place:

1. /run/timeshift/backup (this is Timeshifts's mounting point for the big SSD)
2. ~/.DataSSD (this is my own mounting point for the big SSD)

Again, this is nothing special.

However, if you now move some file from within ~/.DataSSD to trash within Nemo and open the trash within Nemo you will see two entries for the deleted file, namely one entry for each of the above mentioned paths. For example, if you move the file ~/.DataSSD/HelpDocs/ExampleFile to trash, Nemo shows two entries:

* ExampleFile - Original Location: /home/[user]/.DataSSD/HelpDocs
* ExampleFile - Original Location: /run/timeshift/backup/HelpDocs

**Expected behaviour**

Of course, there should be only one entry (the first one).
In Timeshift settings, there is no warning like "never store snapshots to a drive that is also mounted somewhere in /home".
Therefore, I consider my configuration as an allowed one.

**Other information**

The effect shows up in Nemo, therefore I have posted it here. I cannot judge, if Nemo or Timeshift misbehaves.
If it is more a Timeshift issue (maybe Timeshift should unmount the snapshot drive when finished?), please forward. Thank you.

**Comment by Jeremy7701** [comment]
Timeshift should only be backing up system files, although you can add some selections of your own, for convenience.

I have a partition [40GB], mounted in fstab for Timeshift in order to stop Timeshift running wild and eating up all my disk space.
I still have a `/run/timeshift/backup` - but its only 4kB and it doesn't give any duplicates problem.

**Comment by oldtomdevel** [comment]
Just to avoid any misunderstanding, I would like to add to the description above that in my installation Timeshift deals with system files only i.e. I have not at all added anything else. I just use one big drive as personal data storage and as Timeshift target as well. But to me that seems to be an admissable configuration that should work.

**Comment by abhidesh128** [comment]
Hii @oldtomdevel...!
As per your description, you have mounted your big SSD inside your home folder i.e., the mount point `~/.DataSSD` is inside your home folder.

See, **when you delete any file in your home folder, it will appear in your trash.** Therefore, when you delete any file from `~/.DataSSD`, as **that folder is inside your home,** that file is shown in your trash.

Now, coming to your confusion, this is happening with you because **the apparent location of `/run/timeshift/backup` is ending up in your `/home`, making the contents of timeshift's directory analogous to contents in your home folder, but, has two different mount points.** Therefore, you can see two entries of a deleted file in your trash.

This is actually common and normal behavior when you mount a directory inside your home folder with two different mount points. Because that causes **two different addresses of the same file.** One address lies on `/home` and other lies on `/run/timeshift/backup`.

The configuration you have set is actually allowed as you said. But may cause confusion because same files will have two addresses when timeshift is running.

**Comment by oldtomdevel** [comment]
Of course, it is logically comprehensible that any file somewhere down in the folder tree of `~/.DataSSD` can be reached via two different mounting points. If it is considered as common and normal behaviour for Nemo to always show both adresses of the file, then there will be no issue for Nemo to solve.

However, the reason for the effect is NOT the fact that the big SSD is mounted inside my home folder.

Now I changed my configuration. I mounted my personal big SSD at the mounting point `/mnt/DataSSD` and only referenced the contents by some softlinks in my actual home folder. When Timeshift starts, it again mounts the target device at `/run/timeshift/backup` what now is identical to `/mnt/DataSSD`. When I afterwards delete some file from the big SSD, it still appears twice in the trash, namely as `/run/timeshift/backup/[subpath to file]` and as `/mnt/DataSSD/[subpath to file]`.

It does not matter where the big SSD is mounted for my personal use. The effect of double entries in trash is caused by the fact that the SSD is not only the target device for Timeshift but also used for my personal data storage.

As the effect of double entries is really annoying, there is still an issue from my point of view.

Linux Mint should strongly advise (e.g. in the welcome screen that asks the user to activate Timeshift) not to use any drive as Timeshift's target device that is also used somehow for user data.
It is obvious that you can eliminate the annoying effect by the command `sudo umount /run/timeshift/backup`. The same can be achieved by a quick reboot (as this deletes the whole folder `/run/timeshift`).

**However, the most elegant solution would be Timeshift itself doing the unmounting after having finished its snapshot.**
see also https://github.com/teejee2008/timeshift/issues/653

**Comment by abhidesh128** [comment]
@oldtomdevel I agree with you.

Timeshift should unmount the drive used for backup automatically.

One thing to tell you, I observed that when you move something on a drive in trash, it is saved in a hidden folder named .Trash-1000 _(may be named differently, check by showing hidden files)_ on the same drive. It also stores paths of deleted files in that folder.

That's why, even if you mount that drive on another location rather than inside your home, when you delete something, it will be stored in .Trash-1000 hidden folder with two addresses.

In file manager, when you click on trash icon, it reads the info of .Trash-1000 folder. Hence it will read two addresses of same file. Perhaps this is the reason of your problem.

I think this is not Nemo's issue, but it's Timeshift causing this problem. This will only be solved if Timeshift unmounts the drive after use. 

>However, the most elegant solution would be Timeshift itself doing the unmounting after having finished its snapshot.
see also teejee2008/timeshift#653

Good deal.👍

**Comment by icarter09** [comment]
@oldtomdevel I'm close this ticket since the issue looks to be with Timeshift. Here's a link for where you can create the new ticket [Timeshift](https://github.com/teejee2008/timeshift/issues)? Thanks.
