### ISSUE TITLE
The modification date appears twice in Nemo parameters

### ISSUE THREAD

**Issue by InfoLibre** [linuxmint/nemo#2544]
```
 * Nemo version 4.6.5
 * Mint 20 Cinnamon
 * 64 bit
 ```

**Issue**

The modification date appears twice in parameters :

![gestionnaire de fichiers_41](https://user-images.githubusercontent.com/3955499/97713156-be607400-1abf-11eb-804b-9abace56345e.png)

![Capture d’écran du 2020-10-30 10-04-07](https://user-images.githubusercontent.com/3955499/97713163-c0c2ce00-1abf-11eb-8173-2bbc38ddb05b.png)

Wrong french translation ?

**Comment by mtwebster** [comment]
Yes they're distinct - one shows the time, one shows just the date - they've been translated the identically. The created date also has this. 

https://translations.launchpad.net/linuxmint/latest/+pots/nemo/fr/+translate?batch=10&show=all&search=modified

**Comment by Jeremy7701** [comment]
If I use the Nemo media list view plugin, the dates and times are shown as datestamps (ie identically) in list view:-

![Screenshot from 2020-10-30 22-49-35](https://user-images.githubusercontent.com/52585119/97764492-bd066a00-1b06-11eb-94ee-1b11641a7b50.png)
![Screenshot from 2020-10-30 22-43-51](https://user-images.githubusercontent.com/52585119/97764505-c7c0ff00-1b06-11eb-8561-09c483aaee0c.png)

**Comment by InfoLibre** [comment]
So, the right translation should be "Date de modification" and "Date et heure de modification".

**Comment by AO-LocLab** [comment]
@mtwebster Thanks for your input. If one actually is for the date only and the other for the time only, the English strings should read that much. Could you please confirm each strings usage?
The issue seems to stem from the current English wording:
"Date Modified" string #168 located in src/nemo-image-properties-page.c:388 libnemo-private/nemo-column-utilities.c:72
"Modified date" string 1270 located in gresources/nemo-file-management-properties.glade:2734
Having to quasi-identical strings in English seems to be the problem. I would think that this issue is also present in other languages.
Do we have other strings where we write date instead of time?

The translations were identical, and rightfully so. There was no error in the French translation @InfoLibre :)

**Comment by mtwebster** [comment]
The additional "Modified date" in the glade file refers to Tooltip details:

![Image](https://github.com/user-attachments/assets/f63a9102-0cb9-4191-aec6-923e7a3bab87)
I'll add some context to these (which should show up in Launchpad also)

------
It looks like you've got things worked out now on LP with translations for the column labels:

![Image](https://github.com/user-attachments/assets/ac557bfe-e7d9-445d-b6fe-77c627d9f52a)

![Image](https://github.com/user-attachments/assets/d1653380-88b2-470e-a0f9-ce455a75acf2)

and

![Image](https://github.com/user-attachments/assets/e14c84b2-bd54-4a39-8c9f-404f962a2968)

**Comment by AO-LocLab** [comment]
Thanks @mtwebster Neither of the two strings on the screenshots above is the one InfoLibre was referring to, which was "Modified date" string 1270 located in gresources/nemo-file-management-properties.glade:2734 . So their suggestion to change that string, since this is Glade, should not affect the translation for the Column list item.
Which two strings show in the Column list, and for which string the English reads date when it’s really time, please? :)

**Comment by mtwebster** [comment]
The strings in nemo-column-utilities.c are what get used to populate the List Columns page in preferences as well as the list view itself.

The only things that are identical are the descriptions (I'm not sure they're ever used). The labels are distinct and always have been:

![Image](https://github.com/user-attachments/assets/d6511a13-8498-477f-913e-0d6cbee6ff0e)

The translations package for Cinnamon/nemo is still using the duplicated strings:
```
[01:49:11 PM] mtwebster@mintbox3:~/bin/cinnamon-translations[master]> git grep -B4 -A4 "Date de modification" -- po-export/nemo/nemo-fr.po 
po-export/nemo/nemo-fr.po-
po-export/nemo/nemo-fr.po-#: src/nemo-image-properties-page.c:388
po-export/nemo/nemo-fr.po-#: libnemo-private/nemo-column-utilities.c:72
po-export/nemo/nemo-fr.po-msgid "Date Modified"
po-export/nemo/nemo-fr.po:msgstr "Date de modification"
po-export/nemo/nemo-fr.po-
po-export/nemo/nemo-fr.po-#: src/nemo-image-properties-page.c:392
po-export/nemo/nemo-fr.po-msgid "Exposure Time"
po-export/nemo/nemo-fr.po-msgstr "Temps d'exposition"
--
po-export/nemo/nemo-fr.po-msgstr "La date à laquelle le fichier a été modifié."
po-export/nemo/nemo-fr.po-
po-export/nemo/nemo-fr.po-#: libnemo-private/nemo-column-utilities.c:79
po-export/nemo/nemo-fr.po-msgid "Modified - Time"
po-export/nemo/nemo-fr.po:msgstr "Date de modification"
po-export/nemo/nemo-fr.po-
po-export/nemo/nemo-fr.po-#: libnemo-private/nemo-column-utilities.c:88
po-export/nemo/nemo-fr.po-msgid "Date Created"
po-export/nemo/nemo-fr.po-msgstr "Date de création"
--
po-export/nemo/nemo-fr.po-msgstr "Type de fichier détaillé"
po-export/nemo/nemo-fr.po-
po-export/nemo/nemo-fr.po-#: gresources/nemo-file-management-properties.glade:2734
po-export/nemo/nemo-fr.po-msgid "Modified date"
po-export/nemo/nemo-fr.po:msgstr "Date de modification"
po-export/nemo/nemo-fr.po-
po-export/nemo/nemo-fr.po-#: gresources/nemo-file-management-properties.glade:2749
po-export/nemo/nemo-fr.po-msgid "Created date"
po-export/nemo/nemo-fr.po-msgstr "Date de création"
[01:49:12 PM] mtwebster@mintbox3:~/bin/cinnamon-translations[master]> 
```

**Comment by AO-LocLab** [comment]
Thanks @mtwebster 
Everything seems in order in Launchpad translations. InfoLibre had modified the Glade string, which was not the right string. It seems that we have a discrepancy between what’s in Launchpad translations and the current Mint version. It’ll be fixed with the next language pack update.
