### ISSUE TITLE
broken behaviour of F2 shortcut (rename)

### ISSUE THREAD

**Issue by mkdy** [linuxmint/nemo#2591]
```
 * nemo 4.8.2
 * Distribution - Arch 64 bit
 ```

**Issue**
So, the latest update has broke the behavior of F2 shortcut.
In the back old days after pressing F2 _twice in a row_ the whole filename (including extension suffix) was selected, and it was super-fancy.
Now it only selects everything but the extension suffix.

**Steps to reproduce**
Select file, press F2 twice.

**Expected behaviour**
The whole name is selected, not only the prefix.

**Comment by Bugfollower** [comment]
Also with:
* nemo 5.0.3
* Distributions linux mint 20 to 20.2

Works fine with linux mint 19.3 .
Very annoying when replacing the whole file name by pasting with Ctrl-V.
Keep that feature working, it is good.
Leaves the impression that mint 20 is less reliable than mint 19.3 .
So, I have still linux mint 19.3 on my hard disk, and mint 20.2 on an external disk, to test it.

Works fine with... nautilus working on the same linux mint 20.2 system, beside of nemo and downloaded because of that little issue.

**Comment by mtwebster** [comment]
> Leaves the impression that mint 20 is less reliable than mint 19.3 

That's being a bit dramatic I think.

As a workaround until the fix is released, shift-F2 will start renaming with the entire filename selected.
