### ISSUE TITLE
why the order of files or folders changes

### ISSUE THREAD

**Issue by candrapersada** [linuxmint/nemo#2649]
why the order of files or folders changes when using add to favorites?

nemo 4.8.4

**Comment by Jeremy7701** [comment]
Because Favourites take priority.
Although there is a option to sort folders before files, there is no option to choose where favourites should go.
So favourite folders/files, ordinary folders/files.

I used to have a Desktop folder called `Links` where I kept a selection of symbolic links.
It worked like a kind of non-integrated favourites, but without any disturbance to the target folders/files.
