### ISSUE TITLE
Inconsistent mouse hovering highlight in some type of files

### ISSUE THREAD

**Issue by UltraBurstXD** [linuxmint/nemo#2690]
```
 * Nemo version: 4.6.5
 * Desktop
 * Distribution - Ubuntu Budgie 20.10
 * Intel HD Graphics
 * 64 bit
 ```

**Issue**
When I hover in some type of files, they are either obstructed or hidden.

Before:
![Screenshot from 2021-03-08 10-04-02](https://user-images.githubusercontent.com/55871338/110381152-c3cb5d80-8061-11eb-84a3-3d9f050615a9.png)

On hover event:

Hidden
![Screenshot from 2021-03-08 09-22-53](https://user-images.githubusercontent.com/55871338/110381268-e3628600-8061-11eb-8ece-9e2e8d22b9d8.png)

Obstructed
![Screenshot from 2021-03-08 10-00-27](https://user-images.githubusercontent.com/55871338/110381276-e52c4980-8061-11eb-8ce1-eb59932f9912.png)

**Steps to reproduce**
1. Just hover in text file or any other file with white (or variant) background.

**Expected behaviour**
The file should be highlighted a little on user's hover event.

**Other information**
In some cases some type of files like *.bmp, etc., aren't highlighted at all. They remain 'indifferent'.

**Comment by JosephMcc** [comment]
I don't know. This doesn't look like a Nemo issue to me. Nemo highlights anything you hover over in the icon view. Here it does even on a .bmp file. Since those render a thumbnail of the image, the amount the highlight shows depends on the image. The problem here is mostly down to using an icon theme that is so low contrast against the background that the highlight effect makes it blend into the background.

**Comment by UltraBurstXD** [comment]
Oh..! That makes sense...
