### ISSUE TITLE
nemo.desktop.in: app desktop entry should use `Nemo` instead of `Files` as the entry Name

### ISSUE THREAD

**Issue by allanlaal** [linuxmint/nemo#2793]
**Issue**

Nemo's own desktop entry file `data/nemo.desktop.in` sets its name as `Files`:

	[Desktop Entry]
	Name=Files

**Steps to reproduce**

visible in master: https://github.com/linuxmint/nemo/blob/master/data/nemo.desktop.in

**Expected behaviour**

Nemo desktop entry name (in all languages) should be Nemo. Using generic names means its going to be mixed up with [others](https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/1938621)

**Other information**

DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=21.04
DISTRIB_CODENAME=hirsute
DISTRIB_DESCRIPTION="Ubuntu 21.04"

nemo:
  Installed: 4.8.6-1
  Candidate: 4.8.6-1
  Version table:
 *** 4.8.6-1 500
        500 http://fi.archive.ubuntu.com/ubuntu hirsute/universe amd64 Packages

64bit
gfx not applicable for this issue

also filed downstream for Ubuntu as: https://bugs.launchpad.net/ubuntu/+source/nemo/+bug/1938620

**Comment by allanlaal** [comment]
PR 4a5f703 fixes the Name in all languages

PR d3551d4 only fixes English and default fallback

**Comment by mtwebster** [comment]
Our users don't care what the file manager's official name is. It's the file manager. Just like the text editor mint uses is called 'Text Editor' instead of 'xed' and 'Image Viewer' instead of xviewer. You may get a similar response from the gnome devs.

- In Cinnamon, duplicate entries get disambiguated automatically in our gui - for example you'd get Files (Nemo) and Files (Nautilus).
-  A _typical_ user won't have multiples of the same application installed, anyhow.
- In many cases, `OnlyShowIn` will prevent additional apps from showing in different desktops (though Cinnamon makes exceptions for the few remaining gnome apps that use this mechanism, such as gnome-terminal).
