### ISSUE TITLE
[Question] Nemo open directory in terminal command

### ISSUE THREAD

**Issue by Davidy22** [linuxmint/nemo#2833]
I'm writing in support for opening a directory in terminal from nemo, but I'm having some amount of trouble figuring out exactly what nemo is sending to the terminal. I did some smaller tests, standard input shows nothing, argv[1] has nothing, source diving tells me that the message is formed by g_spawn_async() but going online to look it up tells me nothing. Before I tried anything else that didn't work, I figured I'd come here to just ask the devs here directly what message is being sent to the system default terminal, what terminal command or whatever it is.

**Comment by mtwebster** [comment]
Are you talking about this?
https://github.com/linuxmint/nemo/blob/master/src/nemo-view.c#L7154

The path to open a terminal in is passed to that function, which is used as the `working_directory` argument - this sets PWD for the program being launched I think.

arg[1] only exists because non-static string arrays (gchar **) need to be terminated by `NULL`.

So basically it's opened the defined terminal in the given directory.
https://docs.gtk.org/glib/func.spawn_async.html

The actual terminal program used is stored in gsettings which is a user-wide settings registry. You can install dconf-editor to browse and change all settings. The user changes it in cinnamon settings 'Preferred applications'.

**Comment by Davidy22** [comment]
Oh I might have lacked context, I'm fixing a bug in a terminal program where opening in terminal from nemo doesn't open the directory in the terminal program, was trying to find how the directory was being passed. By argv[1] I meant first argument on the command line because I thought it might be something like an invocation of `[terminal] [directory]` but that wasn't it.

Current working directory didn't come to me at all. Now I just need to figure out how to distinguish between "Open in terminal" from nemo and opening the program from the start menu or terminal so I only spawn a new terminal tab when opening from nemo, but I think that's my problem and not nemo's.
