### ISSUE TITLE
Nemo order files backwards in ~/Downloads [ Nemo 1.8.0-1 ]

### ISSUE THREAD

**Issue by Prozium** [linuxmint/nemo#292]
I have an issue with Nemo my files placed in ~/Downloads are being ordered backwards eg 3 2 1, If i move thos files into another directory then the files will be ordered properly

How to reproduce
1) Go to ~/Downloads
2) Create a empty document and name it 1, do it again name it 2 do it again name it 3
3) Now the files should be listed 3 2 1 - If not then go backwards to your home dir and then go back to Downloads, and it should be listed 3 2 1

4) Now try create a folder
5) Select file and cut 1,2,3 and paste it in the new directory now the files should be ordered properly, if not go back and go back to the folder and it should be ordered correct

I am running Arch Linux

**Comment by Vahan86** [comment]
I can reproduce this issue in Cinnamon 3.0.7 (Nemo 3.0.6). For Downloads and Trash folders the "Reversed Order" options is enabled by default.

**Comment by xenopeek** [comment]
Nautilus implements "last modified" and "first modified" as separate sort options. The default for downloads and trash is last modified (show files most recently downloaded, or trashed, first) which seems sensible as a default.

**Comment by Vahan86** [comment]
The issue is still relevant to Cinnamon 4.2.4 (Nemo 4.2.3)

**Comment by xenopeek** [comment]
Nemo defaults to showing the most recently downloaded files first in Downloads and the most recently deleted files first in Trash. That is by design, making it easier to find files just downloaded or just deleted (they will be at the top). This can be changed through the View > Arrange Items menu:

![image](https://user-images.githubusercontent.com/21159972/85838826-6c6ab300-b79a-11ea-8c53-e9b1abc067ad.png)
