### ISSUE TITLE
Nemo on Fedora Workstation

### ISSUE THREAD

**Issue by dennisr40** [linuxmint/nemo#2987]
Nemo Icon does not show until the .desktop file is corrected.
**sudo gedit /usr/share/applications/nemo.desktop**
remove line 
**OnlyShowIn=X-Cinnamon;**

**Comment by didierm** [comment]
This has aggravated me for many years (I alternatively assigned a GNOME keyboard hotkey to Nemo).

As usual, only after finally finding the solution myself today (by examining the (331 lines) .desktop file and noticing the self-explanatory **OnlyShowIn** field), I found this issue.

FYI,  sudo-less fix : 
`sed 's/OnlyShowIn=/OnlyShowIn=GNOME;/g' /usr/share/applications/nemo.desktop > ~/.local/share/applications/nemo.desktop
`
_(re-mentioning @leigh123linux as package maintainer)_

**Comment by leigh123linux** [comment]
IMO nemo shouldn't be automatically displayed in gnome.

**Comment by didierm** [comment]
@leigh123linux Thanks for your reply.
(not questioning your authority and just a FYI : without the modification, an installed nemo cannot be found/launched via the GNOME GUI, and can only be started from a terminal or directly via ALT-F2, which might be a tad unintuitive for a file manager)

**Comment by mtwebster** [comment]
Some more reasoning behind this - 

Both Gnome and Cinnamon call their file managers 'Files', because for an average user looking in the menu, they don't care what the app is really called, they want to manage their files. And, at least for Cinnamon, it and Nemo are pretty tightly integrated if used together, so we tend to treat it as a core part of the desktop. At the same time we assume Nautilus to be a core part of Gnome Shell, so it just makes sense to only have the appropriate one visible by default.

Cinnamon's menu will distinguish two "Files" entries by appending the actual app name, but I don't think any other desktops do this. Imagine you're a second user on a machine - you use Cinnamon, the other person prefers Gnome.  Both can be installed so both users can be happy, but neither wants to see the other's file manager next to the one they (their desktop) prefers.

In Cinnamon, it's a pretty simple thing to add another menu entry that will be visible, to launch some non-default file manager (there's a menu editor available in Cinnamon's start menu settings). I'm pretty sure Gnome still has a menu editor as well, so we just leave things at that.

**Comment by didierm** [comment]
@mtwebster Thank you for your candid explanation.
In accordance with Cinnamon's described behaviour, I updated the one-liner : 
`sed -r 's/^OnlyShowIn=.*//;s/(^Name.*)(=Files$)/\1=Files (Nemo)/' /usr/share/applications/nemo.desktop > ~/.local/share/applications/nemo.desktop `

This : 
1. allows for Nemo to show as a Nautilus Files alternative in Gnome ;
2. modifies its name to "Files (Nemo)" , discriminating from standard Nautilus "Files" ;
3. adds the modified desktop file in the user's applications folder, alleviating the need for a dedicated menu editor.

HTH other people looking for this.
