### ISSUE TITLE
Feature Request: Scroll past last item in view

### ISSUE THREAD

**Issue by gkatev** [linuxmint/nemo#2998]
Hi, I would like to suggest the addition of a setting, which when enabled, would allow scrolling past the last item in the folder. I mostly have list view in mind, but it could be applied to icon and compact view as well.

The functionality I have in mind would work the same way as it does in code editors, where (if enabled) you can continue scrolling even after EOF is reached, until (usually) only the last one line is visible at the top, and the rest is empty space. Please let me know if I haven't explained it adequately!

- Such a feature would help when working in directories with so many items that they take up the entire window (height wise)
  - Especially when the window takes up the whole monitor (height wise), working on the last items in the folder is uncomfortable. Implementing further scrolling would allow to bring these items towards the center

- Furthermore, it would solve the problem caused when trying to select the last item in the folder and the horizontal scroll bar inteferes #2154, #2837

- Finally, it would offer some help when trying to drag and drop a file into a folder that is full of folders (!) #1986; scrolling past the last item would create the necessary empty space

**Comment by Drugwash2** [comment]
Not to mention that, if correctly implemented it would allow an option that is otherwise unreachable: **Create New Document**.
What I'm referring to is a bit more complicated. The issue is that in a (partly) expanded tree view one has no ability whatsoever to create a new document in an expanded folder. That option is missing in the context menu (together with the option to create new folder) and can only be accessed in an empty space inside a folder. An empty row at the end of an expanded folder would allow those two options, unless it's the last folder in the view in which case the extra scroll would take action.
The only condition would be that the empty row under expanded folder and empty space past last folder belong exclusively to their respective folders, not to the base folder.

**Comment by mtwebster** [comment]
Selecting last item in the list view: https://github.com/linuxmint/nemo/commit/e8c8b1099112f3d157849c7a1c303110ea144583

**Comment by gkatev** [comment]
Thanks for these improvements! For the record, these 2 commits (only) address the secondary points of my suggestion.

The primary point was to allow scrolling past the last item, to aid in working with folders with many items, so that the eyes of the user comfortably remain at the center of the screen, rather than all they way at the bottom when working with the last item(s). Exactly the same idea as "Scroll past end-of-file" in code editors.

The secondary points was that, as a side-effect, this would also help with drag-n-drop, and selecting the last item.

The secondary issues are now fixed, but I'd still like to keep the idea of my primary point into the mix, if that is a desirable feature. Feel free to re-open or keep closed as you see fit.
