### ISSUE TITLE
There are (still) arefacts when pasting text into Nemo's bar

### ISSUE THREAD

**Issue by LinuxOnTheDesktop** [linuxmint/nemo#3070]
```
 * Nemo version: 5.4.5
 * Is issue with desktop or windowed nemo? Windowed
 * Distribution: Mint 21
 * Graphics hardware *and* driver used: Intel; Mesa
 * 32 or 64 bit: 64.
 ```

**Issue**

Pasting a string that starts with a quotation-mark produces weird and undesired results.

**Steps to reproduce**
1. Paste this string into the Nemo bar: `'/home/fred/VirtualBox VMs/Win10 Home`.
2. See the result: `/home/fred/JL/scripts/'/home/fred/VirtualBox VMs/Win10 Home`.

`/home/fred/JL/scripts/` was the directory that Nemo was showing at the time of the paste.

**Expected behaviour**

The result

`'/home/fred/VirtualBox VMs/Win10 Home`

or else (better?)

`/home/fred/VirtualBox VMs/Win10 Home`

It seems that one gets the problematic result even if the pasted string contains no space.

**Other information**

Cf. #2244.

It is _easy_ accidentally to paste into Nemo a string that starts with a quotation-mark.

**Comment by Jeremy7701** [comment]
This is the same behaviour as copy and pasting a piece of text anywhere else and so nemo is behaving correctly.

Perhaps you would like to see some kind of auto-correct function?

**Comment by LinuxOnTheDesktop** [comment]
> This is the same behaviour as copy and pasting a piece of text anywhere else

Sorry, but it is not. Nemo is combining the path that is within the pasted text with the path that Nemo is showing already. By contrast, if I paste the text at issue into a text editor, or into LibreOffice Writer, then the pasted text gets reproduced _verbatim_.

**Comment by mtwebster** [comment]
The behavior you're running into is actually a 'feature':

If the path you enter there is an absolute one (leading `/`) it navigates directly to that location.

If there's no leading slash, Nemo assumes you've entered a relative path, it appends it to the current location. You can observe this also by clearing the entry and typing in a folder name in the current location - it will attempt to autocomplete it from the current location.

I suppose we could strip any leading or trailing punctuation, but `'foobar` is actually a valid filename, so that's probably not a good idea. I guarantee 100% if we were to do that we'd get a bug report about this.


ref: https://github.com/linuxmint/nemo/blob/master/src/nemo-location-entry.c#L330-L347
