### ISSUE TITLE
Date/Time column display is untidy

### ISSUE THREAD

**Issue by QmwJlHuSg9pa** [linuxmint/nemo#3116]
```
 * Nemo version -- 5.2.4
 * Distribution -- Fedora Silverblue 36 (GNOME 43)
 * Hardware -- AMD Radeon RX 580, amdgpu
 * 64 bit
 ```

**Issue**
"Date {Created,Modified,Accessed}" and "{Created,Modified} - Time" fields may render date and time at inconsistent widths if non-monospaced font in use by system.

**Steps to reproduce**

1. Ensure current system theme is using a non-monospaced font.
2. Within Nemo:
    1. Edit -> Preferences -> Display -> Date -> Format: [set to ISO format]
    2. Open a folder with Nemo.
    3. Set current view to "List View".
    4. Add a "Date Created" column.

**Expected behaviour**
Date and time columns should display in a monospaced variant (if available to system). This would greatly increase readability.

Perhaps account for non-existent monospaced variants -- rely upon a list of common fallback fonts?

Examples of before/after desired monospaced output (for Date/Time columns only):
![cantarell-11](https://user-images.githubusercontent.com/1274826/201110378-8e532852-dbff-467c-b298-9548248e8e8b.png) ![cantarell-mono-11](https://user-images.githubusercontent.com/1274826/201110370-ed1d9641-7c44-4cf0-9c92-ef2dba91500c.png)

**Other information**
Applies to more than just the ISO format for date/time display, but is most egregious there.

**Comment by QmwJlHuSg9pa** [comment]
I have realised I made a sort of mistake -- "Cantarell Mono" doesn't exist, so in my "after" screenshot, the system is utilising an _unidentified_ fallback font for `org.gnome.desktop.interface font-name`.

Meanwhile, `org.gnome.desktop.interface monospace-font-name` defaults to "Source Code Pro", which matches the font in your experiment; definitely more visually jarring going that route.

**Comment by BaconCatBug** [comment]
In Nemo 6.2.0, the Date Modified et. al. columns which are affected by the new "Display" > "Use a Monospace Font" option are not respecting the "Monospace Font" cinnamon system setting. Can we please have this option respect that setting, or have a setting in nemo to specify a specific monospaced font?

**Comment by ion201** [comment]
I think this feature needs to be disabled by default. I just updated and the modified font looked like a bug since the mono and regular fonts are vastly different. 

There's also this reddit post from another confused user this morning; in this case the monospaced font doesn't line up at all since the system language has a mix of 3 and 4 letter month abbreviations: https://www.reddit.com/r/linuxmint/comments/zwck6z/police_issue_in_file_explorer_after_upgrade_to/

**Comment by erik-mansson** [comment]
(Started commenting on #3164 but then realized this duplicate issue is older, and duplicates some of my observations about the Ubuntu vs Ubuntu Mono fonts.)

I was struck by this when upgrading Linux Mint Debian Edition, getting nemo 5.6.3 and Cinnamon 5.6.7. A few lines up in Nemo's monospace-font-finding algorithm, https://github.com/linuxmint/nemo/blob/master/libnemo-private/nemo-global-preferences.c#L358 , it is said to reject a monospaced font if the first word in its name doesn't match the first word in the main font's name.

So, when the system default font is "Ubuntu" Nemo picks "Ubuntu Mono" for monospace. However, that font does in my opinion look annoyingly different: Its character height is much smaller and this is clearly contrasted between the columns for filename and date in Nemo's list view mode. (Playing around with monospace fonts in Libre Office, I notice that Ubuntu and Ubuntu Mono agree quite well in horizontal average character size, but that seems less important for Nemo's usage.)
The fact that the system default monospace font  (in `cinnamon-settings fonts`) is instead configured as "Monospace" seems like a hint to me that I'm not alone in finding "Ubuntu Mono" problematic. But Nemo ignores that setting. The lines 383-399 about falling back to "Monospace" thus won't happen, because the Ubuntu Mono was already chosen.

Composite of screenshots (sorry for the non-English, just look at the character heights):
![Nemo font exmples](https://user-images.githubusercontent.com/16100116/215911922-45bc63c0-6c34-4520-9ae7-f1d1c41d3f44.png)

As shown in the above composite of screenshots, I can change my system default away from Ubuntu to a random choice of "Tinos" to confirm that Nemo then picks "Monospace" instead of "Ubuntu Mono". Would it make sense to let Nemo use the system monospace font instead, so that the user has some control over it?

However, as perhaps the original issue reporter showed, there are of course fonts which **do** have a nice monospaced-partner, in which case the system monospace might be worse. In my screenshot the "Roboto" font looks similar enough to "Ubuntu" for me to consider changing the system default, and I get a matching character height with "Roboto Mono" (surprisingly [not part of fonts-roboto package](https://askubuntu.com/questions/984563/how-to-download-and-install-the-roboto-mono-font) but can be downloaded).

In the end, I'm happier for now by just disabling Nemo's monospaced date option, but anyway wanted to add to this discussion about issues with the monospace font-selection.
