### ISSUE TITLE
Desktop: Overlap of Text of Adjacent Icons 

### ISSUE THREAD

**Issue by MiY4Gi** [linuxmint/nemo#316]
There are too many people complaining about the lack of a grid layout on the desktop, however I noticed that the Keep-Aligned option on the desktop approximates a grid fairly well. I've got a major issue with it though. The icon text (below the icons) displays around 20 letters per line (text wrapping), so that the texts of two adjacent icons often overlap. Therefore, I would like two configuration options which overcome this issue. 

Firstly, I would like an option to vary the column width of the Keep-Aligned option. Stated differently, I would like the horizontal distance between the icons (and their text) to be adjustable.  

Secondly, I would like an option to specify the number of letters to display on one line for icon text. Stated differently, I would like the icon text field-width to be adjustable.

Alternately (or temporarily), you can just reduce the icon text field-width to 75px (or 12 letters) and increase the column width by another 5-10px. That should prevent the overlap.

**Comment by Vahan86** [comment]
I can't reproduce the overlap issue in Nemo 3.0.6.

**Comment by feren** [comment]
@Vahan86 I seem only able to produce it on a Live CD here (they overlap ubiquity's shortcut)

**Comment by JosephMcc** [comment]
You mean like so:
![selection_043](https://cloud.githubusercontent.com/assets/2231759/20072975/4ecd7598-a4df-11e6-9fd9-1901ea8c59bc.png)

**Comment by Vahan86** [comment]
Sorry, I misunderstood the issue posted by @MiY4Gi.
This is an issue for me as well.

**Comment by Swiftpaw** [comment]
All we need is for the desktop to be treated in the same way that Nemo treats browsing a folder's contents inside a Nemo window, in a perfect grid.  I think users would prefer this to be the default behavior of their desktop icons, to keep them always aligned in a grid like Windows and most other desktops do, but you can have an option to turn this off (again, like in Windows).

The problem is the "Keep Aligned" option isn't satisfactory because it only keeps icons separated into columns, not BOTH columns and rows like the "Align to grid" option in Windows does, and like Nemo/Nautilus does when viewing a folder's contents inside a file browser window.

**Comment by Vahan86** [comment]
Still an issue in Cinnamon 4.2 when horizontal grid spacing is set to minimum.

![Screenshot from 2019-12-08 16-55-36](https://user-images.githubusercontent.com/12819058/70389677-0c6a1600-19dc-11ea-9194-2e8d81983e25.png)

**Comment by icarter09** [comment]
Is this a Nemo issue or a Cinnamon-Desktop issue?

**Comment by icarter09** [comment]
Nemo v4.6.4
Mint 19.3 64bit 

I'm not able to reproduce this issue. What I'm seeing is that long file names, whether they are just one long or many words, are now ellipse so the name no longer overlaps. If someone is still getting this issue, let me know what I need to adjust to reproduce the issue. Thanks.

**Comment by aledef** [comment]
Hi,
this issue is not been solved yet.
I get the same bahaviour on Linux Mint 21.3 with Cinnamon 6.0.4 

Please, thake a look at the attached image.

![Schermata del 2024-02-12 19-15-31](https://github.com/linuxmint/nemo/assets/3217018/7ebba7f7-de6d-4802-a618-013a21dbec9c)

To reproduce:
1. right click on the desktop > Customise, reduce icon spacing to minimum
2. create some random files on desktop and give them long names
3. Put them adjacent to each other.

Thanks!
