### ISSUE TITLE
How to make preview bigger

### ISSUE THREAD

**Issue by SujithManjavana** [linuxmint/nemo#3239]
```
 * Nemo version 5.6.4
 * Distribution - Mint 21.1

 ```

**Issue**
When selecting a file to upload from Chrome, how can we zoom or increase the image preview size?  It's challenging to find the target file when the folder contains similarly named files. Please add an option to preview the file properly before uploading it to Chrome.

**Steps to reproduce**

**Expected behaviour**

**Other information**

**Comment by leigh123linux** [comment]
GTK3 is responsible for the file picker.

**Comment by Drugwash2** [comment]
> GTK3 is responsible for the file picker.

And who is responsible for the preview widget as per **[this](https://docs.gtk.org/gtk3/method.FileChooser.set_preview_widget.html)**...?

> Sets an application-supplied widget to use to display a custom preview of the currently selected file.

Application-supplied means - if I'm not mistaken - that in this particular case Nemo is the application that supplies the widget. If so, is it not possible to provide the widget with certain facilities such as custom size, zoom and/or others?

**Comment by leigh123linux** [comment]
> > GTK3 is responsible for the file picker.
> 
> And who is responsible for the preview widget as per **[this](https://docs.gtk.org/gtk3/method.FileChooser.set_preview_widget.html)**...?
> 
> > Sets an application-supplied widget to use to display a custom preview of the currently selected file.
> 
> Application-supplied means - if I'm not mistaken - that in this particular case Nemo is the application that supplies the widget. If so, is it not possible to provide the widget with certain facilities such as custom size, zoom and/or others?

You are mistaken, remove nemo if you don't believe me.

**Comment by Drugwash2** [comment]
Ah yes, it's a bit confusing. Indeed each application would have to provide its own widget when they use the GTK native file picker dialog, which means the system could virtually have a countless number of different dialogs.

I wonder if GTK itself could be hooked into internally in order to provide a unique preview widget regardless of any application-provided widget. But that would likely open a whole new can of worms.

Personally I use Double Commander for a file manager, as an old Total Commander user under Windows previously. So I could easily remove Nemo if needed - but why bother. 😄
