### ISSUE TITLE
Unneccessary limitation preventing Nemo from launching in Gnome-shell.

### ISSUE THREAD

**Issue by mcoyle1960** [linuxmint/nemo#3267]
### Distribution

Fedora 38

### Package version

5.8.4

### Frequency

Always

### Bug description

In the file '/usr/share/applications/nemo.desktop', there is a line:

`OnlyShowIn=X-Cinnamon;Budgie`

That prevents this excellent file manager from easily running in gnome. I know anecdotally that many gnome users love Nemo. I see no specific dependencies to warrant this limitation, especially since I have been a happy gnome/nemo user for years.

### Steps to reproduce

sudo nemo /usr/share/applications/nemo.desktop

Currently line: 121

### Expected behavior

By commenting out his line, gnome-shell can find and launch Nemo.

**Comment by mtwebster** [comment]
Nemo doesn't have that line. It's added by the fedora maintainer.

Nemo source:
https://github.com/linuxmint/nemo/blob/master/data/nemo.desktop.in#L118

Fedora build:
https://src.fedoraproject.org/rpms/nemo/blob/rawhide/f/nemo.spec#_97

One reason for this is that the Gnome devs only want a single file manager showing up in their launcher, and to be able to call it 'Files' or whatever - the user doesn't typically care about what its real name is. MATE does this for their Caja file manager, as does Xfce with Thunar.

It's a way of partitioning off multiple desktops being installed. We should probably do this ourselves instead of the maintainer...
