### ISSUE TITLE
Upgrade to LM 21.2 Linux Mint Victoria - nemo failing on SMB recursive searches

### ISSUE THREAD

**Issue by TimeJunkie01** [linuxmint/nemo#3273]
### Distribution

21.2

### Package version

5.8.4

### Frequency

Always

### Bug description

Nemo (file explorer) no longer does recursive file searches on SMB mount to my Synology NAS.
Synology is running the most current DSM 7.2
(https://forums.linuxmint.com/viewtopic.php?t=400404)

### Steps to reproduce

Any simple recursive search on SMB mount failed. Local mounts are fine.

### Expected behavior

This was working previously in 21.1.

**Comment by TimeJunkie01** [comment]
I am happy to load and test any fork.

**Comment by mtwebster** [comment]
New packages here with the fix if you want to try:
https://github.com/linuxmint/nemo/releases/tag/master.mint21

Download packages.tar.gz, extract the .deb files (except the -dbg  you probably don't need) and in a terminal:
```
sudo dpkg -i *.deb
```
Once a new version is tagged it will show up in the update manager like normal (as 'cinnamon-nemo').

**Comment by TimeJunkie01** [comment]
Works!! (only reboot required)

Great Job!

Thank You!

**Comment by dayvid3** [comment]
The same issue is happening with Fedora Cinnamon Nemo

**Comment by AchillesBoi** [comment]
Can we reopen this? Why was it closed if the issue persists? It is Sep 18, 2023 and the bug has not yet been fixed. The only fix we have is to download [this package](https://github.com/linuxmint/nemo/releases/tag/master.mint21) but it breaks thumbnail previews.

It is surprising that this issue was not only closed but there has been no update since LM 21.2 released. This is a major bug! Any basic work computer connected to an SMB server that relies on searching its files is pretty much F'd. I'm left with no option than to downgrade 6 machines to LM 21.1 until a fix is released.

Please mark this issue as OPEN.

**Comment by jemehlbox** [comment]
Dear AchillesBoi,
if you are talking about the bug, that Nemo can't open a share on a Synology NAS by double clicking, I have found, that Nemo 5.8.5 reintroduces this bug. For me it works on 21.1 and on 21.2 with Nemo 5.8.4. Yesterday (9/23) I installed 5.8.5 and it stopped working. I timeshifted back, so its working again. I searched for this bug and found this thread. 
I created an account just now, so please forgive me, if I do something stupid. :-)

**Comment by cduncan-rbi** [comment]
CONFIRMATION: Nemo v5.8.5 works when doing recursive file searches on SMB mount to my Synology NAS.
Thank You!
