### ISSUE TITLE
Way to disable Multi-Threading with Thumbnails?

### ISSUE THREAD

**Issue by jonnyabu1** [linuxmint/nemo#3287]
### Distribution

Manjaro

### Package version

5.8.4

### Frequency

Always

### Bug description

Since 5.8, I get very slow response times from directories with lots of thumbnails.  Typically I could open a directory, and copy files to it, and go back up a directory and be done in a second. 

Now I have to wait a few seconds when I open a directory while it "catches up" and if I try to move too fast ( as I used to ) it even can go long enough that the popup to Wait or Kill Nemo comes up while it tries to catch up and process what I told it to do.

I suspected it was the new multi-threading and tested by disabling showing thumbnails.  It then returned to being a speedy process to move files without seconds or more of delay.  I was able to zoom through actions speedily again.

I'm not sure if it's b/c I move files to a HDD ( for storage ) vs being a SSD where that may not manifest with the greater speed.  

I know in theory it's faster to be multi-threaded, but here it makes things slower by quite a few seconds or more.  Can I disable multi-threading, or can that be an option in a future release?

### Steps to reproduce

Open a folder with lots of thumbnails.  Perhaps it must be on a HDD, I'm not sure.  Try to perform a copy or move action on that folder and then go back to the previous directory

### Expected behavior

Previous to 5.8 I could open a folder, copy files, and move back up a directory in a second.  Now I have to wait for things to catch up and if I go too fast Nemo can hang and ask if I want to kill it or wait.

### Additional information

Ryzen 7 5800X
32GB RAM
1TB SSD - 4TB HDD

**Comment by Jeremy7701** [comment]
I have the same CPU (and RAM) and although it  "only" has 8 cores, all userland software interprets this as 16 cores - because each core can run two threads concurrently.
I'm on LMDE5 - so I'm looking forward to multi-threaded thumbnailing when it arrives.
Also, with 32GB RAM, I would expect that would be sufficient to cache many thousands of thumbnails, so disk speed need not be a major factor.

**Comment by mtwebster** [comment]
Ah I misread the specs for that cpu, yes this is based on vcores not cores.

Disk speed is a factor when generating thumbnails because they get saved in ~/.cache/thumbnails before Nemo uses them. It's also a factor when loading those thumbnails, either the first time they're generated, or subsequent visits to the same folder.

**Comment by Jeremy7701** [comment]
Does nemo remove old or unused thumbnails from `~/.cache/thumbnails` ?
Should I periodically run a job to remove thumbnails more than a few weeks old in the interests of keeping the cache small?

**Comment by mtwebster** [comment]
They're monitored by the 'csd-housekeeping' process (https://github.com/linuxmint/cinnamon-settings-daemon/blob/master/plugins/housekeeping/csd-housekeeping-manager.c), and by default any older than 180 days are removed.

You can change this with dconf-editor:
![image](https://github.com/linuxmint/nemo/assets/262776/9a960cdf-455f-4126-97c0-65058324f1ea)
