### ISSUE TITLE
Nemo can not launch terminal when Blackbox is set as prefered terminal in application preferences.

### ISSUE THREAD

**Issue by ritulahkar** [linuxmint/nemo#3372]
### Distribution

21.3

### Package version

nemo 6.0.2

### Frequency

Always

### Bug description

I have blackbox installed as flatpak and set to prefered terminal. Nemo can not launch it. But it works fine with default terminal.

### Steps to reproduce

1. install Blackbox as flatpak
2. set it as prefered terminal
3. open nemo
4. try open in terminal option anywhere.

### Expected behavior

It should have open the terminal

**Comment by rcalixte** [comment]
So mixed results here. You can workaround this for now by running `gsettings set org.cinnamon.desktop.default-applications.terminal exec '/var/lib/flatpak/exports/bin/com.raggesilver.BlackBox'`. (This is assuming you have Black Box globally installed via Flatpak and not just for your user account.)

The reason this is mixed results is because although the terminal launches, it does not seem to be accepting the working directory correctly. This seems like it might be an issue with the application itself but I could figure out why that would be since it supports the exact same parameters as other terminals.

**Comment by rcalixte** [comment]
I've self-assigned this to see if we can at least get the terminal to launch. (Via testing, it seems that there's an issue with the working directory being passed to the containerized application. I _think_ it's related to the fact that the invocation for the terminal is the flatpak binary first and therefore, that is stealing the environment and not passing it to the application. Assuming this is true, I'm not sure of a good fix for that at the moment.)
