### ISSUE TITLE
[Feature request] Tags for files and folders?

### ISSUE THREAD

**Issue by mcintyre94** [linuxmint/nemo#338]
The new OS X tags look really neat, and I think they'd be really useful here. Would it be possible to implement this in Nemo?

OS X implementation:
http://d35lb3dl296zwu.cloudfront.net/uploads/photo/image/12133/wwdc2013_0176.jpg

Old Nautilus implementation:
http://www.iloveubuntu.net/nautilus-receives-tags-ubuntu-1204-lts

**Comment by Triplethread** [comment]
absolutely necessary for the overview!!

**Comment by icefapper** [comment]
#1390

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by ChristianSilvermoon** [comment]
I would suggest the use of Extended Filesystem Attirbiutes via `user.xdg.tags`, which is what already used by [Dolphin](https://invent.kde.org/system/dolphin) for the same purpose.

**Comment by Ao1Pointblank** [comment]
I know how to assign tags to a file, with a command like:

``exiftool -IPTC:Keywords="tag1" -IPTC:Keywords="tag2" ~/Desktop/image.png``

Is the hard part making the tags searchable?
I've seen that one guy in all the other related feature requests, with his nemo extension. 
I tried it, thinking that would be the solution, but the UI bar for it is too intrusive and ever-present.
Applications like Gthumb can search by exif tags as well. I'd love to see this come to Nemo soon, instead of just getting forgotten about.
