### ISSUE TITLE
xdg-user-dirs not showing up on the sidebar of nemo

### ISSUE THREAD

**Issue by Fozzyishere** [linuxmint/nemo#3384]
### Distribution

Arch Linux

### Package version

6.0.2

### Frequency

Always

### Bug description

As the title said, nemo doesn't display xdg-user-dirs on the left navigation sidebar. The only one that shows up is Desktop.

### Steps to reproduce

- Open nemo through either wofi or typing nemo in terminal

### Expected behavior

- navigation sidebar should show all xdg-user-dirs (photo taken from nautilus)
![image](https://github.com/linuxmint/nemo/assets/101717395/293bc5d8-a5a2-4b6b-8ee4-630358d7606d)

### Additional information

This seems to be a duplicate of #610. Reinstalling and updating xdg-users-dir didn't do anything. Seems like only nemo is affected by this because I tried installing both Dolphin and Nautilus and xdg-user-dirs shows on their navigation bar. 

#### Some extra information:

DE: Hyprland

Content of user-dirs.dirs:

```
# This file is written by xdg-user-dirs-update
# If you want to change or add directories, just edit the line you're
# interested in. All local changes will be retained on the next run.
# Format is XDG_xxx_DIR="$HOME/yyy", where yyy is a shell-escaped
# homedir-relative path, or XDG_xxx_DIR="/yyy", where /yyy is an
# absolute path. No other format is supported.
# 
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/Downloads"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/Public"
XDG_DOCUMENTS_DIR="$HOME/Documents"
XDG_MUSIC_DIR="$HOME/Music"
XDG_PICTURES_DIR="$HOME/Pictures"
XDG_VIDEOS_DIR="$HOME/Videos"

```

**Comment by Fozzyishere** [comment]
After researching some online forums, that area on the sidebar is called Places. Some people have had the same issue with it when they change their user-dirs (#1947) which I didn't do. A workaround to this is to make bookmarks of user-dirs. Although not the fix I wanted, it's a good band-aid solution.
![image](https://github.com/linuxmint/nemo/assets/101717395/618dd61a-3435-4ce2-a66e-1d16df475a38)

**Comment by Ikkibird** [comment]
Hi @Fozzyishere :wave:,

I had a similar problem, and figured that you can move the manually created bookmarks to the _My Computer_ section by going inside the _Bookmarks_ menu (at the top of the window), then _Edit bookmarks…_, and dragging the horizontal line item below them.

I hope that will be useful to you.

Have a nice day,

**Comment by nonetrix** [comment]
> After researching some online forums, that area on the sidebar is called Places. Some people have had the same issue with it when they change their user-dirs ([#1947](https://github.com/linuxmint/nemo/issues/1947)) which I didn't do. A workaround to this is to make bookmarks of user-dirs. Although not the fix I wanted, it's a good band-aid solution. ![image](https://github.com/linuxmint/nemo/assets/101717395/618dd61a-3435-4ce2-a66e-1d16df475a38)

This has to be some dumb file that gets saved, this happens in every file manager and every file picker for me. Everywhere gaslights me and says they should be hard coded, but they clearly aren't because if I don't run xdg-user-dirs before opening a file manager they're missing forever, generating them before opening one seemingly makes things work fine. Only real fix I've found is nuking my install. I tried adding bookmarks, but apparently these are separate from the """"""""""""built-in"""""""""""" ones so appear in a separate section at least in Nautilus and seemingly PCManFM

<img width="185" height="496" alt="Image" src="https://github.com/user-attachments/assets/fd8cb111-6732-4f9d-b15d-1481842e8e74" />

I feel like I am going insane sorry if I sound heated, this has been a issue I've randomly had in diy distros for years. This is horrible user experience and needs to be rethought entirely no hate to any developers

**Comment by Jeremy7701** [comment]
You can choose your own bookmarks.
This avoids putting everything into /home, if you have some extra mountpoints.
For instance select:-
```
XDG_DESKTOP_DIR="$HOME/Desktop"
XDG_DOWNLOAD_DIR="$HOME/"
XDG_TEMPLATES_DIR="$HOME/Templates"
XDG_PUBLICSHARE_DIR="$HOME/"
XDG_DOCUMENTS_DIR="$HOME/"
XDG_MUSIC_DIR="$HOME/"
XDG_PICTURES_DIR="$HOME/"
XDG_VIDEOS_DIR="$HOME/"
```
Then add any extra bookmarks by using Bookmarks -> edit bookmarks.

**Comment by nonetrix** [comment]
Sorry for crashout I deleted it after I realized I was being dumb, and not right place to complain as it's a issue with every file manager seemingly. But setting bookmarks is kinda a bandaid fix as it's not in the same location, they're has to be some file that is being written that messes it up if you haven't ran xdg-user-dirs-update at least once before opening any file manager/picker. I still stand by the fact this is a horrible user experience, because this isn't documented anywhere how to really fix it besides nuking install and doing it right I could probably find root of issue if I figured out every file it's loading somehow
