### ISSUE TITLE
(intentional behavior?) Folders with names ending in ~ are not hidden, yet files with names ending in ~ are hidden

### ISSUE THREAD

**Issue by NintendoManiac64** [linuxmint/nemo#3429]
### Distribution

Mint Cinnamon live ISO, versions 21.3 and 22(.0) beta

### Package version

6.0.2; 6.2.1

### Frequency

Always

### Bug description

Folders with names ending in ~ are not hidden, yet files ending in ~ are hidden

### Steps to reproduce

1. Create a new folder and name it something like `folder~`

2. Create a new file and name it something like `file~`

3. Refresh the folder view and observe how only the file has become hidden.

### Expected behavior

Both the file and the folder with names ending in ~ should become hidden

### Additional information

For all I know this sort of behavior is actually intentional? I say this because the [exact same thing actually occurs in Xfce's Thunar as well](https://gitlab.xfce.org/xfce/thunar/-/issues/1384)

![hidden](https://github.com/linuxmint/nemo/assets/11896003/d6288545-0d0f-4162-a551-35a2122c7f8f) ![unhidden](https://github.com/linuxmint/nemo/assets/11896003/74828376-d54d-404f-8a3d-a6a8e4d938fa)

**Comment by rcalixte** [comment]
This is intentional behavior. The tilde suffix/extension is a special case for files, typically used to denote temporary and/or backup files. There is already a special notation to indicate whether a directory or file should be hidden and that is the period (.) character. This is why the status of the directory is not affected by the tilde suffix.
