### ISSUE TITLE
Creating a new empty document creates a document that contains 1 byte

### ISSUE THREAD

**Issue by MarioMS08** [linuxmint/nemo#3450]
### Distribution

Mint 22 (upgraded from 21.3)

### Package version

nemo 6.2.8

### Frequency

Always

### Bug description

When creating a new empty document via right-click > `Create New Document` > `Empty Document`, the supposedly empty document contains 1 byte (`0x0A`, line feed).

### Steps to reproduce

See above.

### Expected behavior

It should be empty.

**Comment by leigh123linux** [comment]
It's intentional, see

https://github.com/linuxmint/nemo/commit/7c67dc922c5924edd4de5f414d87eb9eb28b852a

**Comment by MarioMS08** [comment]
Oh, okay.

It's just earlier (before I submit this issue), I created a file called `.gitignore`, then a popup shown up that I need to choose a default app for it. But, just now, it's all okay. Probably the Nemo's auto-detecting file thingy acted up, I guess?

I also (after submitting this issue) cleared the thumbnail cache in `~/.cache/thumbnails` because there was a delay everytime I delete a file.

**Comment by superian** [comment]
Ah, I didn't find this when I looked before reporting it as a bug, and ah2, it is new behaviour.

It may be intentional, but "x-zerosize" describes exactly what it has been up to now and what, clearly, it should be. _A file with contents is not empty!_  

If I append a file created via something calling it an 'empty' file to another one, I should be able expect that the original file does not change in size.

How many lines does an 'empty' file have?

`$ls -lha
-rw-rw-r--   1 user user    1 Aug 30 19:31  onebyte
-rw-rw-r--   1 user user    0 Aug 30 19:31  zerobyte
$ wc onebyte 
1 0 1 onebyte
$ wc zerobyte 
0 0 0 zerobyte
`

.. one more than a truly empty file, it seems.

If I read the discussion linked to in the change correctly, this comes because a version of one text editor was confused when asked to edit an empty file. That's a bug in the editor, not in Nemo. If I create an empty file via touch, it doesn't create a one byte file.

**Comment by xvybihal** [comment]
Horrible decision. You call it Empty document and then create NOT EMPTY document.

Ad. to https://github.com/linuxmint/nemo/commit/7c67dc922c5924edd4de5f414d87eb9eb28b852a commit message
> Adding a newline is something an editor would do anyhow, once
> the file is given actual content.

This is simply not true!
