### ISSUE TITLE
No translation possible for menu items: copy, cut, paste

### ISSUE THREAD

**Issue by spectas** [linuxmint/nemo#391]
Hi everybody, I realize that the menu items "copy", "cut" and "paste" are all in English and can't be translated via Launchpad. They are really important items, so they should be translated, too.

The menu items are visible in the main menu "Edit", but also in the menu visible when right-clicking on a file.

Tested on: nemo 1.8.5 - nightly (1.8.5-20130916010206-raring)

Kind regards!
Spectas

**Comment by bitboy85** [comment]
Just in case someone else is affected:
I have the same issue on linuxmint 18.3 Cinnamon. Nemo Version is 3.6.5+sylvia amd64.

First use synaptic to install the package language-pack-gnome-de instead of de choose your locale.
after that, enter the following commands in a terminal and reboot.

`sudo dpkg-reconfigure locales` 

`sudo update-locale LANG=de_DE.UTF-8 `

`sudo locale-gen --purge --no-archive `

`sudo update-initramfs -u -k all `
