### ISSUE TITLE
Nemo always handles _NETSCAPE_URL  instead of XdndDirectSave

### ISSUE THREAD

**Issue by evilpie** [linuxmint/nemo#407]
I implemented XdndDirectSave in Firefox, but as long as we support _NETSCAPE_URL, nemo never tries to use XdndDirectSave. XdndDirectSave probably just needs a higher priority.

**Comment by Vahan86** [comment]
@evilpie, is this still an issue for you with Nemo 3.2?

**Comment by Vahan86** [comment]
@JosepMcc, can we close this issue?

**Comment by evilpie** [comment]
This bug still exists.

**Comment by evilpie** [comment]
Here
https://github.com/linuxmint/nemo/blob/17734bf9523a63e528ed20218831eaeaef16e5a4/libnemo-private/nemo-icon-dnd.c#L76
NEMO_ICON_DND_XDNDDIRECTSAVE_TYPE comes after NEMO_ICON_DND_NETSCAPE_URL_TYPE.

The appropriately named function get_data_on_first_target_we_support selects  the first one, and so it's broken. I think just changing the order should be enough.

**Comment by mtwebster** [comment]
Here is what I get when I inspect the context from an image dragged from firefox:
```
atom: text/x-moz-url
atom: _NETSCAPE_URL
atom: text/x-moz-url-data
atom: text/x-moz-url-desc
atom: application/x-moz-custom-clipdata
atom: text/_moz_htmlcontext
atom: text/_moz_htmlinfo
atom: text/html
atom: text/unicode
atom: text/plain;charset=utf-8
atom: text/plain
atom: application/x-moz-nativeimage
atom: application/x-moz-file-promise
atom: application/x-moz-file-promise-url
atom: application/x-moz-file-promise-dest-filename
```

There should be `XdndDirectSave0`

For comparison, chrome:
```
atom: STRING
atom: UTF8_STRING
atom: application/octet-stream
atom: chromium/x-renderer-taint
atom: TEXT
atom: text/html
atom: text/plain
atom: text/x-moz-url
atom: XdndDirectSave0
```
Chrome works fine - dragging an image from the browser into nemo downloads and creates the file locally.  Whereas with firefox, it always selects `_NETSCAPE_URL` because it has no other choice.

I'm no expert on how inter-process dnd works, maybe I'm missing something here.

**Comment by evilpie** [comment]
Oh, I am very sorry, this Firefox doesn't actually support XdndDirectSave0 yet. I made a push to our CI system (treeherder) and provide a link to a build with this feature when it's ready.

I think Chrome works here, because none of those types before XdndDirectSave0 are actually in the `GtkTargetEntry drop_types` list, so XdndDirectSave0 is selected.

**Comment by evilpie** [comment]
[Download link](https://queue.taskcluster.net/v1/task/NH1QnRxqQ2WKLxrQz7Mhug/runs/0/artifacts/public/build/target.tar.bz2) from [treeherder](https://treeherder.mozilla.org/#/jobs?repo=try&revision=6cb32874dbd61d9b3104e25faf8e67932b3d24d6&selectedJob=201016383). I verified that this build allows drag&drop image downloading with Thunar.

**Comment by mtwebster** [comment]
So, that version appears to work properly - I get:
```
atom: text/x-moz-url
atom: _NETSCAPE_URL
atom: text/x-moz-url-data
atom: text/x-moz-url-desc
atom: application/x-moz-custom-clipdata
atom: text/_moz_htmlcontext
atom: text/_moz_htmlinfo
atom: text/html
atom: text/unicode
atom: text/plain;charset=utf-8
atom: text/plain
atom: application/x-moz-nativeimage
atom: application/x-moz-file-promise
atom: XdndDirectSave0
atom: application/x-moz-file-promise-url
atom: application/x-moz-file-promise-dest-filename
```
The netscape atom is higher than the Xdnd one, but since I've re-ordered them in nemo's code, the Xdnd type gets used.

An observation (and it maybe correct, expected behavior):  This direct save functionality seems to only exhibit itself in specific situations in firefox.

For instance, if I do a google image search, dragging a resultant image does not work (It uses NETSCAPE_URL and provides a link)

If I click on a result, where it brings up a black view strip with the image along with a subset of similar items, I can drag on either the primary image or even one of the 'thumbnails' out of the subset, it works properly, using Xdnd.

If I go to this site: https://homepages.cae.wisc.edu/~ece533/images/ (just a random site I found with pure image links,) dragging a link uses only the _NETSCAPE_URL method, even though it's a link to an image.  Part of me thinks 'of course this would be the case' but another thinks it should know what I want, I guess, since the link is an image.  However, I know pure links like that are a rarity anymore, and more often there's some generator on the other side to issue the image when you click on it.

Anyhow, now that I have more understanding, this shouldn't adversely affect current behavior so I'll get it merged.  I just need to verify the same behavior in all view types, and the desktop.  I also may have ctrl and/or shift repurposed to save a link in these cases where xdnd would kick in.

When will this make its way into a ff release?

**Comment by evilpie** [comment]
> When will this make its way into a ff release?

Barring any issues, this will be in the next Nightly version of Firefox, and ship with Firefox 64 (currently planned for [2018-12-11](https://wiki.mozilla.org/Release_Management/Calendar)).
