### ISSUE TITLE
Feature Request: Support TortoiseHG

### ISSUE THREAD

**Issue by monoceros84** [linuxmint/nemo#411]
Hi,

since Nemo was established as the default file manager we are waiting for a TortoiseHG support. Versioning is essential for a lot of colleagues of mine (including me) and we are more and more switching back to Nautilus even though Nemo is the better tool over all. It's simply too annoying to basically work in Nemo and having to browse to the same folders for versioning with Nautilus several times a day. Not even speaking about not having an overview about changed or added files while working with them. Consequently, we do all our stuff in Nautilus again :(

All one can find on Google is a forum thread of somebody wishing the same, more than a year ago, and a comment on Nemo's very own site:
http://forums.linuxmint.com/viewtopic.php?f=47&t=118677
http://cinnamon.linuxmint.com/?p=198  (search for 'Mercurial')

Really hope to get this in the near future.

Cheers,
Mathias

**Comment by grizzlyfred** [comment]
... which works, but isn't pulled for lack of debian packaging. I would package if I knew what to add...

**Comment by grizzlyfred** [comment]
With 17.2 "Rafeala" stuck in a funny situation:
- Had to build mercurial 3.4.2 from source, because "official" ubuntu ppas are outdated and the two versions of tortoisehg and mercurial in ther repos do not match (and one has to switch between the release and the snapshot-stable repos as they are partially empty)
- TortoiseHg 3.4.1 from their repo "sort of" worked, but not with the symlink as the proposed, only after setup.py install and some minor dependency issues. at least I can start "thg" from the shell again.

For nemo/nautilus integration I am stuck again:
I had to symlink the path to the icons from the directory, thg is looking in to the realpath in my home dir, where I made the build.

I am also a dropbox user, and now I have a situation, where a "sudo nemo" would show me, that some plugins are loaded and I have dropbox and mercurial status overlays and context menu.

But when I run "nemo" as a normal user, I get nothing on stdout, so something is preventing the start of the nemo/nautilus-python extension, I would guess, but I have no clue in which logfile to log.
Probably someting has root ownership and no execute permissions for the user, but what?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
