### ISSUE TITLE
columns not resizeable in slim window (nemo 2.0.0)

### ISSUE THREAD

**Issue by VolMi** [linuxmint/nemo#413]
I'd like to resize the name column, here
![nemo_columns](https://f.cloud.github.com/assets/1189207/1319894/8cd162ac-3320-11e3-8f20-544ccaca0c60.png)
But I can't.

**Comment by xenopeek** [comment]
This issue about unresizable columns was probably fixed longer ago but at least I can confirm it is fixed in Nemo 3.0.6.

Having a directory with a very long name, I can scroll the pane to see the columns currently not in view and I can resize any columns (even to make them larger than the pane size). Tested both with a slim window and dual pane view. Tested on Linux Mint 18 Cinnamon and on Ubuntu 16.04 by adding Cinnamon Nightly PPA.
