### ISSUE TITLE
Nemo 2.0 does not render desktop correctly with Compiz

### ISSUE THREAD

**Issue by gunwald** [linuxmint/nemo#418]
I am using Ubuntu without Unity but with Compizan Nemo as file manager. Since the update to Nemo 2.0 it does not render the desktop correctly anymore. Instead of the background picture I see a black background and every window movement leaves a strange effect on the desktop: For a screenshot and more discussion: http://askubuntu.com/questions/358584

**Comment by lukefromdc** [comment]
This problem seemed to disappear with the combination of compiz patched to declare "frameGtkExtents" as supported (for CSD transparency/rounded corner support, recent versions of GTK 3 and Nemo 3.0 or above, not sure what fixed it. Rolling back GTK 3 all the way to 3.14 did not re-break it in a test I just ran, so the compiz patch or other recent compiz changes may have had something to do with it. 

With GTK 3.21 a just as severe problem comes up with ALL window-managers, caused by a single line in the source that Nautilus got rid of way back in the 3.7.9 to 3.7.91 prerelease versions. A PR to apply this to Nemo exists:
https://github.com/linuxmint/nemo/pull/1235
Since that takes out the main desktop rendering difference from Nautilus I suspect it would fix this too if vanilla Ubuntu compiz (unpatched)  is still having trouble with Nemo.
