### ISSUE TITLE
Feature Request: Support Folder/File Labels like in Mac finder or Marlin file manager

### ISSUE THREAD

**Issue by mahajanudit** [linuxmint/nemo#436]
I believe Nemo now has become what we can safely say a complete file manager. I have not experienced any bug ( I am using it in Ubuntu 13.10 Unity), and the functionality it offers is complete as well.
Now to increase its utility across users I think we should enhance its functionality and features.. Something like ability to add labels to folders/files something similar to Mac finder or Marlin file manager as shown in the screenshot below.

![2013-02-10-150535_1366x768_scrot](https://f.cloud.github.com/assets/2698052/1452262/54e35b10-42c6-11e3-88e1-f9573e670883.png)

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by DIMFLIX** [comment]
@Pointedstick @corbin-auriti @mahajanudit @anandrkris   If the problem is still relevant for you, I have come up with a small solution. The [nemo-tags plugin](https://github.com/meowrch/nemo-tags) adds full tag support.

Unfortunately, I was unable to implement a drag-and-drop system or create a more attractive interface due to Nemo's limitations. But overall, I think it turned out to be quite usable and even convenient.

I would appreciate a star on GitHub repository as support.

<img width="1086" height="658" alt="Image" src="https://github.com/user-attachments/assets/b9809994-95ab-4de9-8f22-c4279d4f749c" />
