### ISSUE TITLE
Recent Places in Nemo - Files & Folders

### ISSUE THREAD

**Issue by anandrkris** [linuxmint/nemo#540]
I am not sure if this feature existed earlier or if this is planned to be pulled from Nautilus. Anyways, simply put, recent files shown in Cinnamon Menu to be accessed and viewed inside Nemo.
It can also be accessed using "recent:///" in location tool bar)
http://iloveubuntu.net/nautilus-gains-recent-entry-its-sidebar-ubuntu-1210

![screenshot from 2014-02-15 00 39 51](https://f.cloud.github.com/assets/4663298/2174137/b4cf64be-95ab-11e3-9eba-66eb94eae20a.png)

I am posting this based on below user request in forums.
http://forums.linuxmint.com/viewtopic.php?f=90&t=158451

Update: This should list **both** recent files and folders accessed.

**Comment by Xerus2000** [comment]
I know this issue is really old, but I am honestly missing something like this since I often navigate back to places I recently visited. I think it could be implemented like this:
- whenever Nemo is closed, add the folder to the recently used ones
- when the user stays in one folder for a longer period of time(maybe something like 2-10 minutes, could be configurable), add it
- don't add folders which are bookmarked or otherwise already accessible in the sidebar

**Comment by JosephMcc** [comment]
Many thanks for contributing to Nemo. Your suggestion was reviewed.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by GitHubIsToxic** [comment]
I was really really disappointed to see that this key usability feature is missing when I upgraded to Mint Cinnamon 19.

Why was this ticket closed??

**Comment by angerangel** [comment]
Recent folders is a must have of any recent file manager. 
Where can I activate it in Nemo?

**Comment by smurphos** [comment]
> Recent folders is not feasible at this time.
> 
> If I have a file I'm trying to get at, that's 10 folders deep in a hierarchy, how do I know which of those folders to list? I certainly don't want all of them.

@mtwebster perhaps an option to have a recent folders entry in the side panel  that simply parses the location of recent files entries in the same way as to _copy to_ & _move to_ browse option would be a possible workaround?

**Comment by angerangel** [comment]
I just found that Linux Mint added it in Nemo, but this is option is not in NEMO settings. 
Go to the control panel, select PRIVACY, and select on on RECENT FILES:
![privacy](https://user-images.githubusercontent.com/2284567/48986073-1c37f480-f110-11e8-9844-1368871a3710.png)
![recentfiles](https://user-images.githubusercontent.com/2284567/48986085-57d2be80-f110-11e8-972a-c315ed12bea3.png)

**Comment by GitHubIsToxic** [comment]
It appears this feature only works in a very small selection of software that comes with Linux Mint?
The "Recent" item is missing in Xed, Firefox, Thunderbird, and just about every other program I've tried.
I was surprised to actually see it working on my machine recently, but I forgot in which application.

GTK applications (such as GIMP) also have a recent item (titled "Recently Used"), and so do my own wxWidgets-based software, but the dialog is entirely different (layout & look), and I'm not sure it shares implementation details.

@angerangel, can you tell me in which application you took the second screenshot? I'd like to verify if I can reproduce that.

**Comment by mtwebster** [comment]
The file open/save dialogs are provided by Gtk.  Though we can control to a certain degree what gets shown in those sidebars on an app-by-app basis, the decision of whether or not to show a recent entry is not one of them.

Gimp is likely using an older major version of Gtk, so that's probably why it looks different.

Any of the potential places for recent files to appear is dependent on the switch in cinnamon-settings->Privacy being active or not.  (This controls something that gtk and possibly other toolkits know to watch for.)

---

To address the lack of recent 'folders' in Nemo, we currently get the recent view that we have 'free of charge' - there's no effort on our part, we simply navigate to `recent:///` and the backend (gvfs) that serves up our files (this backend also keeps track of metadata for folder views, custom icons, etc... - think of it as a wrapper for your filesystem).  This backend gives a list of recent files as if it was just a normal folder.  This backend currently filters out folders.

To have a view that consists only of folders, or a mix of both files and folders, we'd need to implement that ourselves, something that just hasn't been a very high priority until now - it's not very difficult, but neither is it trivial to do.  I will have a look at it for 4.2 though.

**Comment by angerangel** [comment]
> @angerangel, can you tell me in which application you took the second screenshot? I'd like to verify if I can reproduce that.

Menu-> Control panel -> Click on "Privacy" icon

**Comment by GitHubIsToxic** [comment]
@angerangel: I mean the 2nd screenshot, the one showing the "recent" item in the dialog.

It does seem that on my system the recent files list rarely (never?) shows more recent files than the last ~24 hours? Even though I have it set to 5 days in privacy settings. Can anyone confirm this, or is it just my system?

**Comment by Filbuntu** [comment]
@mtwebster 
> To have a view that consists only of folders, or a **mix of both files and folders**, we'd need to implement that ourselves, something that just hasn't been a very high priority until now - it's not very difficult, but neither is it trivial to do. **I will have a look at it** for 4.2 though.

Thanks in advance for having a look at a view that consists of a **mix of both files and folders**, especially for "Save as" dialogues.

**Comment by FibroJedi** [comment]
Sorry to resurface this, but this seems the only truly correct place to find info on including Folders as well as Files in "Recent". Has this been implemented, because I can't find the setting for it if it has. My "Recent" only shows files. If it hasn't then is it still being considered? If it has please help me to feel less stupid and let me know where the setting is, thanks!

**Comment by Jeremy7701** [comment]
An install of Mint/LMDE4 comes with a default Cinnamon setting of "privacy"  =  "Remember recently accessed files".
Tracking file access is a strange application of privacy.
So its necessary to disable this "privacy" setting and delete the associated nemo bookmark.
Perhaps the default should be **forget  recently accessed files**?

**Comment by FibroJedi** [comment]
But that would stop all recent files being listed at all wouldn't it? When I want to show files and folders?

**Comment by Jeremy7701** [comment]
It just prevents the collection of a list of filenames you have accessed via nemo from being collected.
Presumably, "remember recently accessed files" gives a performance gain if you regularly re-open files and/or a possible usability gain for long paths?

**Comment by FibroJedi** [comment]
It certainly makes searching for things I use regularly quicker (there are a couple of things I open nearly every day for example), but as I said, I don't think that's the solution to "showing files and folders in recent" if Mint no longer catalogues recent things?
