### ISSUE TITLE
Path bar disappears

### ISSUE THREAD

**Issue by pmarcelll** [linuxmint/nemo#60]
If the path of a folder is too long,  the path bar disappears and the Location/Search duo becomes a pop-up menu. After going back to the parent folder, everything stays the same (the path bar doesn't appear and the pop-up menu doesn't change back to the two separate icon)

(Sorry, if it's hard to understand, i can't explain it better in English.)

**Comment by xenopeek** [comment]
This issue about too long pathnames was probably fixed longer ago but at least I can confirm it is fixed in Nemo 3.0.6 and the path bar doesn't disappear.

Too long pathnames are made to fit with ellipses replacing the middle part. Screenshot showing me having moved to the long pathname directory and back.
![nemo 3 0 6 long pathname](https://cloud.githubusercontent.com/assets/21159972/17967268/74f05806-6ac6-11e6-9e6b-79014fb5727e.png)
