### ISSUE TITLE
Search ignores hidden files and folders

### ISSUE THREAD

**Issue by HifeFish** [linuxmint/nemo#604]
There is no way to include hidden files and subfolders into a search (even if they are generally set to be visible).

System: Ubuntu 14.04, Nemo 2.2.1

**Comment by petermoo** [comment]
Nemo search turned out to be useless to me. When searching for settings files and other files, I do not know if one of the directories happens to have a . in the file name. The command line "find" finds the relevant files, Nemo does not.

Nemo search is effectively wrong. Switching on the "show hidden files" is not applied to search. The results are misleading, missing critical files.

A Nemo search should search the same files as shown in the browse window.

**Comment by xenopeek** [comment]
Still happening on Nemo 3.0.6. Toggling to show hidden files and then searching doesn't find any matching hidden files or matching files in hidden directories. Counter-intuitive as the pane is showing hidden files and directories before you start searching.

**Comment by NeverUsedID** [comment]
Same here. Linux Mint 18 - Nemo 3.0.6.
Nemo search is nice and fast, but don't show content of hidden folders.

**Comment by NeverUsedID** [comment]
Reproduced on 3.2.2.

**Comment by andrewufrank** [comment]
still not fixed - what is so difficult with this? the error occurs still in nemo 3.2.2 on debian stretch (up to date). 
use of catfish is a workaround. do not forget to check "hidden files" in catfish!

**Comment by NeverUsedID** [comment]
Reproduced on 3.6.4. Linux mint 18.3

**Comment by mgarcia-org** [comment]
3.8.3 still not fixed..  :-1:

**Comment by Extarys** [comment]
3.8.5 still not showing hidden files.

**Comment by NikoKrause** [comment]
The fix https://github.com/linuxmint/nemo/commit/8a60207ead934fa036658903281050f19e701087 has been applied after 3.8.5, i.e. it will be available in 3.8.6 (probably not until Mint 19.1).

**Comment by Extarys** [comment]
Thanks! Just saw the commit, my mistake.

**Comment by string-areeb** [comment]
Now it shows the hidden files even when show hidden files is turned off

**Comment by Extarys** [comment]
I moved away from Mint to test Manjaro and I now use Gnome Files so I won't be able to test this for a while.

**Comment by QmwJlHuSg9pa** [comment]
Not sure if this is a regression or separate bug:

Fedora 37 Silverblue x86_64

With v5.6.4 (Fedora RPM) I definitely notice that I am unable to search hidden files (with "Show Hidden Files" enabled), unless they directly contained within the current directory. I.e. searching for a hidden file `.test-hidden` works, but the following expected results do not appear: `dir/.test-hidden`, `.dir-hidden/test`.

**Comment by mtwebster** [comment]
@QmwJlHuSg9pa this works ok for me - do you have 'Search folders recursively' enabled?

![image](https://github.com/linuxmint/nemo/assets/262776/b84b04b8-6c2d-4779-a3d2-23b7ba16c94d)

**Comment by QmwJlHuSg9pa** [comment]
Thanks, that was the fix.

Now, there's no way I was going to associate this (horizontally flipped) "Return key" button with "Search recursively". Maybe I had curiously toggled it at some point and forgotten about it? I'm not even sure what the default state is.

Here's why it is unobvious: All(?) other buttons in the basic Nemo experience handle GUI stuff like switching layout state and toggling search bars. It is _not_ expected that the _next_ button in the flow would toggle search parameters, rather than some other part of the GUI.

In this instance, a text label with checkbox would do wonders -- like I mentioned, I strongly associate the current symbol with "Return key". I could imagine the current symbol being a stand-in for "ignore new lines" (at least, if it were applicable to "Search content". Nor have I actually used the "case sensitive" toggle button -- again, this could be a text-labelled checkbox, rather than looking like it might modify some part of the GUI. I understand such changes would cause headaches, and perhaps require the search interface undergoing some sort of visual redesign.

Also, I suggest forcing recursive search for every newly opened window, by default. There could be a toggle for this new behaviour in Preferences. Rationale: Recursive search is my expected session default; I can see myself disabling it temporarily via the existing toggle, if I _know_ I want something(s) in the current directory.

**Comment by Jeremy7701** [comment]
The default setting is to search recursively.
