### ISSUE TITLE
Codes in nemo_actions don't seem to work

### ISSUE THREAD

**Issue by SlurmMcKenzie** [linuxmint/nemo#679]
I want nemo to return the path of the directory where I click on my context menu entry. I tried 

Exec=<myscript.py %P> 

following https://github.com/linuxmint/nemo/blob/master/files/usr/share/nemo/actions/sample.nemo_action, and I tried other variations (%F, %D etc.). I always get back the path to the script which is executed, not that of the current directory.

I use Ubuntu 14.04 with Nemo 1.8.4. Any idea what I do wrong?

**Comment by xenopeek** [comment]
We believe this issue is fixed. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.

**Comment by SlurmMcKenzie** [comment]
Thanks!
