### ISSUE TITLE
thumbnails: default to GNOME_DESKTOP_THUMBNAIL_SIZE_LARGE

### ISSUE THREAD

**Issue by azizLIGHT** [linuxmint/nemo#771]
In Icon view, zoomed in, thumbnails look blurry and pixellated when we use Nemo's generated thumbnails of 128 pixels (normal). There doesn't seem to be a way to let Nemo use 256 pixel thumbnails (large). They have to be done manually using scripts, rather than on load. 

I'm not too sure but I think the relevant lines are in libnemo-private/nemo-thumbnails.c at line 141 and 197: 
https://github.com/linuxmint/nemo/blob/c8cb24b7d9a1ed18cd2f46b25826f6f98116983e/libnemo-private/nemo-thumbnails.c#L141
https://github.com/linuxmint/nemo/blob/c8cb24b7d9a1ed18cd2f46b25826f6f98116983e/libnemo-private/nemo-thumbnails.c#L197

**Comment by Starcross** [comment]
I can confirm this works. Switching these two lines to GNOME_DESKTOP_THUMBNAIL_SIZE_LARGE results in 256px thumbnails. I believe these values are hard coded into the gnome thumbnail factory (which isn't ideal either)
Some more common file formats, such as jpeg seem to get generated on the fly in nemo, matching the size exactly to the thumbnail preview. This is great, a much better way of viewing thumbnails so you see the correct size for the icon displayed (1:1)

**Comment by azizLIGHT** [comment]
Sorry, I'm not a programmer by any means. I don't know how to exactly go from changing it in those two lines to actually getting the large thumbnails in practice. For regular users, will this be incorporated in as a fix?

**Comment by Starcross** [comment]
I just noticed there is also a reference to the thumbnail size in nemo_remove_thumbnail_for_file(), so this should probably also be updated to ensure the thumbs can be deleted.

Your question was partly answered in another issue (https://github.com/linuxmint/nemo/issues/522) 
You can download the source, edit it, and run dpkg-buildpackage in the source directory. I did find quite a few additional packages were required in mint though.

Once you have the packages it creates, they can be installed by running 'sudo dpkg --install *.deb'. Note the packages will be created in the parent directory. You will probably want to ignore future  nemo updates, as these will overwrite the changes

Whether this change or similar gets incorporated into nemo will depend on what the developers decide. Which is why we try to persuade them here ;)

If you're still stuck I uploaded mine:
http://www.starcross.eu/photos/downloads/nemo_2.6.7_amd64-largethumbs.tar.gz

**Comment by icarter09** [comment]
@azizLIGHT are you still experiencing this issue?

**Comment by Starcross** [comment]
Yes, this appears to have been changed as of commit dedd5f8eeb7a7bfea9de94caf7875146b941f849

I tested this on Mint 19.3 and thumbnails are 256 pixels, appearing in the 'large' .cache folder

It would be nice to have this as a user configurable option, or even automatic based on the icon/thumbnail size. This issue is fixed though.

**Comment by icarter09** [comment]
@Starcross thanks for the update. I'm going to close this ticket since the issue is fixed, but feel free to create a feature request ticket for your suggestion (if you haven't already) for having it as user configurable option. Thanks.

**Comment by azizLIGHT** [comment]
I tested on Mint 19.2 and also confirm what @Starcross says. The thumbnails are now in ~/.cache/thumbnails/large and are 256 pixels max. They can be smaller if the original picture was small, depending on height/width.
