### ISSUE TITLE
Nemo thumbnail directory should be ~/.cache/thumbnails/

### ISSUE THREAD

**Issue by geckolinux** [linuxmint/nemo#772]
Hello,

It appears that Nemo looks for thumbnails in ~/.thumbnails. This doesn't work with gsf-office-thumbnailer for LibreOffice / MS Office file thumbnails, because it creates them in ~/.cache/thumbnails .  I think that is the new "standard" location for thumbnails, so Nemo should probably use it by default.

As a temporary workaround to fix office document thumbs in Nemo:

```
rm -R ~/.thumbnails
ln -s ~/.cache/thumbnails/ ~/.thumbnails
```

**Comment by xenopeek** [comment]
We believe this issue is fixed. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
