### ISSUE TITLE
Problem with mouse selection in icon view (nemo 2.4.4)

### ISSUE THREAD

**Issue by gfbett** [linuxmint/nemo#790]
I'm having a weird behaviour using the icon views on nemo, I'm unable to select an item, either by single clicking it, or open it by double clicking on it. 
Doing multiple selection using click and drag works ok, but if I want to select just one item, nothing happens when I click over one icon (either a folder or a file). 
If I switch to list view, everything works as expected, but on icon view I have this issue. 
Another weird thing is that in the about box, if I move the mouse around,  it behaves as I had the left mouse button pushed down, selecting the text as the pointer moves. 

Is there any way to generate a log or view debug output?

**Comment by Vahan86** [comment]
@gfbett, is this still an issue for you in Nemo 3.0.6?

**Comment by gfbett** [comment]
At the moment I don't have a Mint installation where I can check this properly. 
On a quick try in Ubuntu 16.04 (Nemo version 2.8.6) it didn't happen, but the original issue was kind of random, so I'm not completely sure that is not reproducible any longer.

**Comment by Vahan86** [comment]
@JosephMcc, can we close this issue?

**Comment by cinnamoner** [comment]
Closing an issue is just a technicality. Why would you ask such a question? I don't get it. Is it so important or what?

**Comment by JosephMcc** [comment]
> Closing an issue is just a technicality. Why would you ask such a question? I don't get it. Is it so important or what?

Because we don't need the issues filled with junk bug reports that are either invalid or don't provide enough basic information to go on. I for one appreciate getting the help with trying to get proper feedback from users. @Vahan86 has been a big help with this.

We've also received complaints from users in the past that feel like we don't maintain this well because we don't handle this sort of thing.
