### ISSUE TITLE
F9 - create a folder, F10 - file

### ISSUE THREAD

**Issue by azjio** [linuxmint/nemo#852]
Necessary for quick work with a file manager Nemo.
Create hotkeys:
F9 - create a folder. To perform a combination of Ctrl+Shift+N need two hands
F10 - Create an empty file

**Comment by mykolaj** [comment]
Just of curiosity, can you please tell why you choose exactly these keys for the operations? And what would be your suggestion to do with already existing standard across GTK hotkey F10  - Open menu bar - which by the way is already adopted by a lot of people who use GTK/Cinnamon every day?
To create a new folder F7 key would be way more familiar because of historical reasons - because F7 key has been used for a long time to create a new folder in titans like Norton/Volkov commander, Far manager, Total commander, Midnight commander and many more.

**Comment by azjio** [comment]
The main thing - the presence of. And that is not composed of a complex combination of 3 keys, not to break your fingers. The operation is very frequent, and should be comfortable

**Comment by Vahan86** [comment]
For now the mentioned two hotkeys are in use: F9 - show/hide sidebar, F10 - open menu bar.

**Comment by shadowxnex** [comment]
It would be nice if users will be able to change hotkeys for such actions.

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.
