### ISSUE TITLE
[Bug] An issue of drag'n'drop a file/folder onto an entry of bookmarks 

### ISSUE THREAD

**Issue by AlvinJian** [linuxmint/nemo#858]
[symptom]
Sometimes drag'n'drop a file or folder onto an entry of Bookmarks, which is exactly in the same partition of that dragging file/folder, causes nemo to copy file/folder instead of moving it. 

The only workaround I found is to go in that Bookmark or enter(browse) its parent folder by nemo at first, then go back to drag'n'drop the file/folder onto that Bookmark, and everything work fine(i.e. nemo move the file into the bookmark). 

If nemo is killed, the same issue will happen again.

**Comment by oscarus** [comment]
This has been happening to me as well. In addition to files being copied instead of moved when dragging them, I've also noticed that the custom icons I set for some bookmarks are not loaded until I use the workaround described by AlvinJian.

Once the workaround is used, the custom icons and the dragging behavior work as expected until Nemo is killed.

**Comment by damian101** [comment]
I hope this will get fixed one day...

**Comment by icarter09** [comment]
@damian101 what version of nemo are you experiencing this issue on?

**Comment by damian101** [comment]
@icarter09 I couldn't recreate the issue in Nemo 4.4.2. Seems like it has been fixed.

**Comment by icarter09** [comment]
@damian101 thanks for the update.
