### ISSUE TITLE
Copy to other pane

### ISSUE THREAD

**Issue by mellobob** [linuxmint/nemo#899]
My linux mint just got updated and it appears that the "copy to other pane" option is gone. This is, of course, only active when there are 2 panes open in nemo.

**Comment by JosephMcc** [comment]
Go to Edit->Preferences and on the Display tab at the bottom, check "Show all available options in the context menus". You need to either log in and out to update nemo or open a terminal and use nemo -q, then start nemo like normal.

**Comment by mellobob** [comment]
Thanks. Works just fine now. Unfortunate that the upgrade borked the options.

**Comment by mellobob** [comment]
Just discovered the simple reason I couldn't find the option before filing this. If the  settings window is too short the menu bar <views behavior ...> is not visible. I think this happens when the text scale factor is set > 1.

**Comment by ben2talk** [comment]
Great - same here using my HDTV at 4 metres I scaled text up.

**Comment by xenopeek** [comment]
We believe this issue is fixed. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
