### ISSUE TITLE
[Feature Request] Improve File-Chooser Dialogue

### ISSUE THREAD

**Issue by ManIVIctorious** [linuxmint/nemo#907]
The thing that bugs me the most is that you can't type a command and hit enter. You have to use the mouse to navigate to the OK button, which is a bit annoying.

The design could be improved too, IMHO the File-Chooser Dialogue is far too big, also i am not sure if it is displayed correctly on my systems since there is a strange icon in its center...

<a href="http://de.tinypic.com?ref=dlg7sj" target="_blank"><img src="http://i60.tinypic.com/dlg7sj.png" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by mtwebster** [comment]
Something's definitely wrong - that window should be at least half as wide... have you tried a different theme (Control theme).

Can you kill nemo, then run from a terminal, I'd like to see if there are any warnings when you open the dialog - 

`nemo --quit && nemo`

Please pastebin any output that may occur when you use the dialog.  I'll fix the enter key issue.

Thanks!

**Comment by mtwebster** [comment]
UX problems fixed by https://github.com/linuxmint/nemo/commit/e041adabb42c1911884e8bbd85252d54743429ca

I'll wait for feedback about the window size issue, I've never seen that or seen it reported though.

**Comment by ManIVIctorious** [comment]
I am currently not at home, but will send the requested logs tomorrow evening

**Comment by ManIVIctorious** [comment]
Okay, i hope i have done it right, just started `nemo 2> nemo.log` and opened a pdf two times with the filechooser dialogue. After that i uploaded the file to pastebin.

<script src="http://pastebin.com/embed_js.php?i=y8ANS3Hc"></script>

I am using gtk-3.16 on Arch Linux, if that matters, just let me know if you need more information.

**Comment by Vahan86** [comment]
@ManIVIctorious, is this issue still relevant to Nemo 3.0.6?

**Comment by ManIVIctorious** [comment]
Sorry, forgot about that one...
The issue seems to be fixed in nemo 3.2.0
Although the size of the dialogue is still the same, but imo functionality is much more important than design

**Comment by JosephMcc** [comment]
I have a feeling the  width of the window is being controlled by the line of text between the scrolled window and the input box. It's much longer translated into your language than it is in English. Word wrap is enabled on that label but on initial opening it seems to want to show it all on one line.

**Comment by dg1727** [comment]
So that anyone following along can tell which window this is:  

This is the "Open with" window, which can be opened (for example) by right-clicking just about any file in Nemo, then choosing Open With > Other Application...

A.  Since the long line of text in question is two sentences, why not just put an explicit line break between the 2 sentences?  This should let the window be narrower.  

B.  As for the 
>strange icon in its center

... maybe that icon & its caption should be removed?  
- The caption "No applications found" seems unneeded when the window was opened by right-clicking a file of unknown type, since in that case the user is likely to gather the concept "No applications found" from the fact that the window appeared in the first place (and the sentence "Select an application..." near the top of the window); 
- Whether the filetype was known or unknown, the caption "No applications found" seems to contradict the fact that there is a list of applications shown to the left; 
- I think the user is expecting that the icon & caption in the center of the window will change depending on which application in the left-hand list is clicked on, but the icon & caption appear to have nothing to do with clicking on items in the left-hand list.  In fact, the listbox selection bar that highlights the clicked-on app goes right through the center icon & caption as though having (1) the list, & (2) the icon, in the same container box was an oversight.  

C.  On my computer, the titlebar of this "Open with" window (Cinnamon desktop environment, Atlanta window-borders theme, and one of the color variations on the Mint-X icon theme) has a circle-slash icon.  Maybe this was intentional, meaning "No applications found," but usually when this icon appears, it means "the window requested an icon which is unintentionally missing from the icons theme".  Therefore I hope a different icon can be chosen here.  Maybe just a "blank piece of paper" icon, generically representing a file on disk, if nobody has a better idea of which icon to use.  

Cinnamon 3.2.7, Nemo 3.2.2
