### ISSUE TITLE
default-sort-order is fixed only 'modification date'.

### ISSUE THREAD

**Issue by dante2k** [linuxmint/nemo#950]
Hello.

I have a problem about order of sort.
I CAN NOT set 'preferences-views-arrage items-by name' when i checked 'preferences-behavior-Ignore per-folder view preferences'.
I can not set any items without 'By modification date'.
I have a no problem when i do not check 'Ignore per-folder view preferences'.
thanks for reading.
please check this issue.

**Comment by arnholt** [comment]
I have had this same problem for 6+ months as well.  File sort order is permanently set to modification date.
Modifying "default-sort-order" in dconf-editor has NO effect.
Modifying the setting within the app has NO effect.
The workaround is to uncheck "ignore per-folder view preferences".

Cinnamon team, Nemo is *great*, and THANK YOU for making this software available. Please fix this bug.  I'm sure it is due to a missing write function call after the setting is changed.  Thanks.

**Comment by kendon** [comment]
+1
This is driving me crazy.

**Comment by u2n** [comment]
This bug was fixed but no update here. Nemo team might need a little help with housekeeping.

**Comment by xenopeek** [comment]
Thanks @u2n. We believe this issue is fixed. If the issue happens again, please test against the latest Nemo version (3.6.5 currently), go through troubleshooting (see our [guide](http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/)) and create a new issue if the responsible component proves to be Nemo.
