### ISSUE TITLE
Files / Folders can be named when starting typing to soon after creation

### ISSUE THREAD

**Issue by ochmenonemo** [linuxmint/nemo#973]
System: Linux Mint 17.2. Cinnamon
1. I create a new file or folder f.e. on the desktop or in another folder. 
2. I want to give it a name. If I wait 1 second or longer after I created the file I can start typing in without any problem. 
3. Since in 90 % + of the cases I just start typing in the desired name instead of waiting, there appears a problem: instead of naming the file / folder, a little text field opens in the bottom corner where the gets written into. the file / folder is then created unnamed. In other cases there is neither text entered as the filename or the text box in the bottom right corner appears - nothing happens and the file remains unnamed.

**Comment by icarter09** [comment]
@ochmenonemo are you still experiencing this issue?

**Comment by ochmenonemo** [comment]
It was fixed in ~ 2016 I would say. With 19.2. it reappeared again but 
way less frequently then back then.

**Comment by xenopeek** [comment]
This can be reproduced on 4.6.4 if one starts typing immediately before the new file is shown in the files list. In that case focus moves to the quick search field—as it should when you type in the files list—but it does move back to rename the new file after it is created and shown in the files list. The long and short of this is you can't rename a file that doesn't exist yet. If instead of typing a new name I press Alt+Left to go one directory back immediately after creating a new file, the new file gets created as expected and doesn't get focus for renaming. I think keyboard input shouldn't be disabled for creating a new file.

**Comment by ochmenonemo** [comment]
still happens today. example: when opening a new folder (anywhere) and instantly start to write, often the first letter(s) are either missed or as described above are getting into the a  unwantingly opening search field in the bottom right
