### ISSUE TITLE
[Feature Request] Copy Files dialogue features

### ISSUE THREAD

**Issue by mossarelli** [linuxmint/nemo#986]
"Copying/Cutting Paste files and folder"'s dialogue for the system when using Nemo would do good with the following features:
- A pause button for halting an operation to allow for resuming (The stop button does not pause).
- Current file indicator inside the progress bar or under.
- Current folder to folder indicator.

Thank you for a nice, customizable file browser with a lot of features.

If these requests are already planned or denied in future build, please remove this thread gently.

**Comment by brouillon** [comment]
Agree, also don't queue delete and rename operation.

**Comment by alium** [comment]
from https://github.com/linuxmint/Cinnamon/issues/4694:

Please implement a 'smarter' queuing system for file operations. The current implementation (as of 17.2) is really annoying. I find myself performing duplicate delete and move operations of the same files because I keep forgetting that they're queued due to having a long copy operation going on. The queue currently allows duplicate operations to be in the queue waiting, which later results in annoying pop-ups.

Changes requested:
1) Identical operations{delete, move, and possibly copy} on the identical files that have not yet been started should not be allowed, as it should be obvious that they cannot be completed.
2) Not all file operations are equal. 'DELETE' and 'MOVE(within the same partition/drive)' should have the highest priority (or better yet, NOT QUEUED AT ALL) since those operations should only take milliseconds to perform.
3) If multiple hard drives are present, the queue should allow for performing multiple copy operations in parallel if they are being performed on drives that are independent of each other (since there is no penalty on those cases).
4) If there are multiple copies in the queue, give the smaller files higher priority since they would leave the queue faster (thus giving the illusion of faster responsiveness, by having the File explorer display closer to the end state quicker).
5) Allow disabling of this feature. I like the idea of queuing large copy operations, but, this currently blocks small/quick file operations, and so is not usable in its current form. I don't see a means to turn it off.

**Comment by Vahan86** [comment]
@JosephMcc, can we mark this issue as a feature request?

**Comment by icarter09** [comment]
Many thanks for submitting your feature request for Nemo. Your feature request has been documented and will be reviewed by the Linux Mint team.

For more information on our workflow and feature requests, read https://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/faq.html.

**Comment by Atalanttore** [comment]
A pause button (for halting an operation to allow for resuming) is still missing in Nemo.

**Comment by metal450** [comment]
Not sure why they closed this when it's not actually been resolved...
